### ISSUE TITLE
Azure Topic Subscription Names Limited to 50 Characters

### ISSUE THREAD

**Issue by onesadjam** [Particular/NServiceBus#1300]
When using Azure Service Bus to manage PubSub, the name of the subscription to a topic is limited to 50 characters.  The naming convention for topic subscriptions is [endpoint queue name].[message type].  We have rather descriptive queue and message names, and ran into this limitation.  The endpoint continued to run even though the subscription could not be made.  

Recommendations:
- Fail fast if the topic subscription cannot be made
- Lobby Microsoft to increase the string length of topic subscription names :-)

**Comment by aanttila** [comment]
Since the original User Voice was closed because it was submitted to the wrong team, I've created a new request here:
[https://feedback.azure.com/forums/216926-service-bus/suggestions/18552391-increase-the-maximum-length-of-the-name-of-a-topic](https://feedback.azure.com/forums/216926-service-bus/suggestions/18552391-increase-the-maximum-length-of-the-name-of-a-topic)
