### ISSUE TITLE
Add support for controlling the MSMQ Message label for outgoing messages

### ISSUE THREAD

**Issue by gbiellem** [Particular/NServiceBus#1338]
Can now be controlled by convention at configuration time. Full doco here http://docs.particular.net/nservicebus/msmq/transportconfig#configuration-msmq-label

**Comment by mackie1001** [comment]
Is there a way of customising this in the latest version? I guess it would require something a bit lower level than IMutateOutgoingTransportMessages.

**Comment by andreasohlund** [comment]
I believe that its valid for us to provide details that makes debugging using the native tools for each transport easier. Eg we set channel and connection info in RabbitMQ to make it easier for admins to see what's going on. Since label is visible in both the native msmq mmc plugin and queue explore I believe this a valid request.

Reopening this one

**Comment by mackie1001** [comment]
It could be as simple at just having an optional TransportMessage header ("Msmq.Label"?) that if set will becomes the MSMQ message label.

**Comment by WilkoSki** [comment]
As Andreas has inferred its a no-brainer.  Just default the message label to the message type but also provide an extension method for IBus to allow users to customise the message label if they wish.

If you were writing something using raw msmq you'd always label the message for traceability.

Having something in the message label would ease support tasks and fault finding no end.

**Comment by WilkoSki** [comment]
Any update on when this is likely to hit a production build.  On the surface it is a rather trivial task to set the message label and it would be so useful when using the OS MSMQ tools as well as tools like Queue Explorer.
