### ISSUE TITLE
Enable hosting multiple nsb-runtimes in the same appdomain

### ISSUE THREAD

**Issue by lcorneliussen** [Particular/NServiceBus#1357]
NSB has a lot of statics that make it hard to have multiple instances running in one appdomain (also for integration tests).

A new ambient context `NsbRuntime.Current` with a possibility to resolve and register singletons (wrapping the container) could help moving away slightly.

``` csharp
using (NsbRuntime.New()){
    // ConfigureNsb....
}
```

**Comment by konstantint** [comment]
This issue seems to come up in Google for a relevant query, hence let me add note here as well.

We have a project, which makes use of about 20 or so endpoints. This is rather inconvenient in development for obvious reasons. In addition, we are using NSB v4, hence "multi-hosting" is impossible, even though a single appdomain would not be a problem. Finally, the mapping between messages and endpoints is coded in a way, which does not lend to natural "re-routing" of the messages without stumbling upon problems.

A combination of two tricks, though, helps in this situation:
 - Firstly, make a separate project which references all the endpoint subprojects, references all the necessary handlers, keeps all the necessary config entries, does a `DefineEndpointName("aggregatequeue")`, and listens for messages on that queue.
 - Secondly, add a fairly simple piece of code, which listens to all the actual service message queues and forwards all messages from them into that `aggregatedqueue`.
