### ISSUE TITLE
Dealing with a message handler that is unresponsive

### ISSUE THREAD

**Issue by thirkcircus** [Particular/NServiceBus#1702]
Creating issue as per skype discussion with @SimonCropp ...

What happens if a dev writes a msg handler that has Thread.Sleep(forever) in it?
Or if the msg handler sync calls a badly behaved service with a stupidly long timeout.

Is there any way to terminate runaway/rogue threads in the host?

When using the DTC this is obviously handled by DTC with a timeout.  But I would expect this to be a problem common to all non-DTC brokered transports - would be preferable to have this handled at an NSB level rather than within msg handlers.

**Comment by danielmarbach** [comment]
With v6 implementors of handlers have to possibility to use cooperative cancellation provided by the .NET framework for their custom code. In the future, we might even expose the cancellation token source and token provided by the transport for each message received. From the perspective of rogue message handler detection there is not much we can do since each transport has its own way of dealing with long running operations (peek lock, no restriction, transaction timeouts...). Closing this.
