### ISSUE TITLE
AssemblyScanner round 2

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#1742]
We are not done yet!

What's left to do:
- [x] Skip assemblies that do not reference NServiceBus.dll;
- [ ] Delay loading of message metadatas
- [ ] make `MessageMapper` lazy. delete `MessageMapper.Initialize` and dive down the rabbit hole
- [ ] make `XmlMessageSerializer` lazy. delete `XmlMessageSerializer.Initialize`. and dive down the rabbit hole
- [x] look at usages of `Configure.TypesToScan`. it will now only contain types from assemblies that reference NServiceBus.dll. As such need to confirm that no assumptions are made about it having types from assemblies that dont reference NServiceBus.dll
- [ ] since `MessageMapper` and `XmlMessageSerializer` will be lazy they also need to be threadsafe in how they cache type information

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers @johnsimons @SimonCropp Should we close this issue? It's soon three years old and at first glance some of the bullet points have been addressed while I'm not sure other points are still valid at all. Since there is currently no deeper reason to refactor it, we can close it as well and raise a new issue when required?

**Comment by danielmarbach** [comment]
Ticked of two boxes which are done. 

#3991 and #3988 are consequences of

>  look at usages of Configure.TypesToScan. it will now only contain types from assemblies that reference NServiceBus.dll. As such need to confirm that no assumptions are made about it having types from assemblies that dont reference NServiceBus.dll

I propose we close this and do not do anymore changes for v6.

**Comment by SimonCropp** [comment]
No objection to closing
