### ISSUE TITLE
Allow MessageID to be set by users

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#1779]
Add MessageId to SendProperties to allow message id's to be set by users

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/SendOptions.cs#L5

We need this to allow users to make use of the builtindedup features of the underlying infrastructure. (like AzureServiceBus)

Full discussion here:

https://groups.google.com/forum/#!msg/particularsoftware/wsusY1_99RQ/X4VKNA98-8cJ

**Comment by udidahan** [comment]
> This also causes quirks with the logging and diagnostics

@abombss are you talking about the built-in logging and diagnostics in the platform or your own?

**Comment by abombss** [comment]
I don't think this actually works we couldn't get it to work by just
setting a header. Second if it did the question I have is when is this
applied to the transport message? The issue with logging is having two id's
in the pipeline. Most diagnostics report message ID in the context, which
one? And if its not the id that ends up on the actual brokered message all
log correlation on the sending endpoint won't work.

**Comment by ramonsmits** [comment]
@abombss You would do logging based on the ID of the message/data that is received. Do you have a requirement where you want to log something for the message that is staged/worked on to send before that message is final?

**Comment by ramonsmits** [comment]
@abombss I did a push of POC I made showing message mutator + outbox + deterministic message id's working with deduplication working even for concurrent processing.

https://github.com/ramonsmits/NServiceBus-Samples/tree/master/MessageIdMutator.v5

I did not gave this priority to add as a decent sample with good documentation.

In V5 it has one drawback and that is that the handler can be invoked more than once when concurrent processing is allowed even if the outbox is enabled. If this handler is not idemponent OR when is does not enlist in the same transaction as the outbox than more than once can occur.

This can be prevented by keeping the concurrency set to 1 but if you have multiple instances and applying competing consumer that the same issue can occur.

Not entirely sure how V6 does it. In V6 there seems to be an outbox transaction so then the outbox can do an INSERT for a specific message ID and then handler for the same ID can be synchronous but I don't know if that also locks INSERT for other ID's. Also, this wouldn't work if the persistence does not support transactions. Maybe @SzymonPobiega can provide some details about the outboxtransaction in V6.

We could solve this by first claiming a lease in the outbox, if acquired then process the message and if not than abort. FLR will make sure the transport message is retried and if still not being able to get the lease to move it to SLR. SLR will be able to process it when the lease expires. Also, when an exception occurs than the handler should drop the lease so FLR / SLR is able to consume the message ASAP when it fails. We can probably do some UPDATE rowcount / INSERT duplicate key trickery to reduce roundtrips and transactions to optimize for the happy flow (no dupes)

**Comment by ramonsmits** [comment]
Some additional details after sync with @SeanFeldman . The reason why the POC works is because it uses the MessageMutator and not the TransportMessageMutator. The message ID must be set before the TransportMessage is created in V5. We did not test yet with V6 but after a quick test it is strange that you are unable to modify this at this stage. We will verify this behavior in V6 and decide if an attribute like the MessageID should still be able to be modified. I think it should as my opinion is that it should not be able to change anymore once the physical message is created which is different per transport as it is part of the conversion for it to not change might is be used anywhere during conversion.

**Comment by ramonsmits** [comment]
The outbox currently in V5 is focused on dedupe of the same physical message where we rely on the fact that the transport is transactional(ish, like a lease). If we have two different physical message but with the same body (technicallly different, functionaly the same) then as mentioned the handlers are potentially invoked more than once when concurrency processing is possible either due to increasing the maximum concurrency level or having multiple instances (competing consumer). However, this is not an issue when persistance in the handler is transactional as when the outbox record is inserted, the operation fails and the transaction will be rolled back. However, if there is any non transactional logic then this can potentially have unintended effects.

**Comment by ramonsmits** [comment]
Regarding ASB, ASB does dedupe on its message ID if the queue was created with ** RequiresDuplicateDetection** set to true. Now ASB will dedupe for a configured period which is max. 7 days. It also does dedupe per partition so when relying on ASB for dedupe either not set the partition key as then the message ID is used as partition key or use deterministic partition key based on the message ID.

ASB does dedupe of physical messages that share the same ID but as a receiver you still need dedupe to have exact-once processing.

**Comment by ramonsmits** [comment]
Would we categorize current outbox behavior in V5 when the user overrides the message ID as a bug due to handlers potentially being invoked more than once in environments that allow concurrent processing?

**Comment by SeanFeldman** [comment]
@ramonsmits I was able to use `IMutateOutgoingTransportMessages` to update message id via headers. It worked for NSB v5. Not sure why it didn't work when we tried before... 

`TransportMessage` [`Id` property](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/TransportMessage.cs#L71) is just a getter for the value in the header `NServiceBus.Headers.MessageId`. That header is always assigned a value [here](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/TransportMessage.cs#L23) or [here](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/TransportMessage.cs#L47) therefore we should be able to set the message ID from `IMutateOutgoingTransportMessages`, similar to what's done in `IMutateOutgoingMessages`.

**Comment by abombss** [comment]
Thanks for the followup, i will need a few days to play with the code and
check. As for it not working this was 2 years ago on nsb v4.

**Comment by andreasohlund** [comment]
This is now fully supported in v6 using `sendOptions.SetMessageId("MyCustomId")`

I've raised a doco issue to better document this

https://github.com/Particular/docs.particular.net/issues/1651
