### ISSUE TITLE
Subscriptions should respect specific type

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#1942]
repro https://github.com/Particular/BugsRepro/tree/master/1942SubscriptionsShouldRespectSpecificType

so I have a mapping in the subscriber

```
<add Assembly="Publisher.Messages" Type="Publisher.Messages.OneEvent" Endpoint="Publisher" />
```

Note I am explicitly saying I am interested in `OneEvent`. 

And in the subscriber I have a handler

```
public class EventHandler : IHandleMessages<IMyEvent>
{
    public IBus Bus { get; set; }

    public void Handle(IMyEvent message)
    {
        Debug.Assert(message is OneEvent);
    }
}
```

In the publisher I do this

```
        Bus.Publish(new OneEvent());
        Bus.Publish(new TwoEvent());
```

Now because the subscriber has said in the mapping "i am interested in OneEvent" then it should only receive `OneEvent`. However it receives both `OneEvent` and `TwoEvent`

So the logic we currently have for subscriptions is
- look through the mappings
- for any of the types check if we have handlers  **for the base types** 
- subscribe to the base types

This has unintended side effects as I have shown above.

To further illustrate how this is wrong a user should not expect these 3 mappings to behave the same way

```
<add Assembly="Publisher.Messages" Type="Publisher.Messages.TwoEvent" Endpoint="Publisher" />

<add Assembly="Publisher.Messages" Type="Publisher.Messages.OneEvent" Endpoint="Publisher" />

<add Assembly="Publisher.Messages" Type="Publisher.Messages.IMyEvent" Endpoint="Publisher" />
```

If we are interpreting both `TwoEvent` and `OneEvent` to mean `IMyEvent` we should throw an exception in the first two cases to avoid allowing the user to ambiguous+misleading configuration

**Comment by johnsimons** [comment]
@SimonCropp can you please move this one to requirements and label it as a concern, it doesn't look like we reached an agreement so it makes sense to flush it out over there.

**Comment by danielmarbach** [comment]
@SimonCropp any ideas how to move this forward?

**Comment by SimonCropp** [comment]
@danielmarbach nope.

**Comment by danielmarbach** [comment]
Should we close this or hash out a strategy to address it?

**Comment by SzymonPobiega** [comment]
So the way the new routing taps into the old config (`MessageEndpointMappings`), is similar to V5 behavior: if you configure a route for type `X`, it will be also configured for all known message types that `X` derives from (including `IMyEvent` in this case).

Then, as previously, auto subscribe will subscribe based on the handlers discovered (`IMyEvent`).

IMO the best thing we can do is document the fact that when you specify a MEM for type `X`, it includes all types it derives from. Question here would be, what if `EventOne` and `EventTwo` have different publishers? If I specify both and have a handler for `IMyEvent`, where the subscribe message goes?

In the new `Publishers` API there is no inheritence magic so when you do `busConfig.Publishers().AddStatic(typeof(EventOne), "SomeEndpoint")` it won't register a route for `IMyEvent`.

**Comment by udidahan** [comment]
These are really edge cases - not a priority right now.

**Comment by SzymonPobiega** [comment]
@udidahan if the fix is just a doco clarification, I'd say it is worth doing.

**Comment by timbussmann** [comment]
@andreasohlund and I agree that this is a bug. 

Possible fixes:
* Throw on "suspicious" mappings (mapping and handler mismatch): While this works for the sample given by simon, it doesn't work when there are three events deriving from the same interface and you you're only subscribing to the first two events. Then it's a perfectly valid use case to have a `IHandleMessages<IMyEvent>()`.
* Subscriber should not receive sibling messages. E.g. when subscribing to `OneEvent` it shouldn't receive `TwoEvent` but when subscribing to `IMyEvent` it should receive both.

**Comment by timbussmann** [comment]
so with the new routing behavior the sample from @SimonCropp would behavior as following:

* When using autosubscription: the handler would receive no events, because there is no publisher configured for `IMyEvent`. 
  * If there would be a route for `IMyEvent`, it would receive both `OneEvent` and `TwoEvent`.
  * If there is an additional handler for `OneEvent`, the endpoint would only receive `OneEvent`.
* When using manual subscriptions. e.g. `endpoint.Subscribe<OneEvent>()`, it would only receive `OneEvent`.

@Particular/nservicebus-maintainers @SimonCropp I think we can close this?

**Comment by SimonCropp** [comment]
@timbussmann 

> the handler would receive no events 

isnt that a serious breaking change?

**Comment by timbussmann** [comment]
it is a breaking change, yes. We discussed a lot about routing inheritance (e.g. that IMyEvent can "inherit" the routes from OneEvent) and we decided to stop doing that in favour of a clearer rule about message routing. All current routing scenarios are still possible but may require additional routing configuration. Since this only affects very specific edge cases like described here (you're interested in OneEvent, but only have a hander for IMyEvent) and scenarios with multiple publishers for events which belong to the same message hierarchy, we agreed that this breaking change is acceptable. See the full discussion and description of the routing rules here: https://github.com/Particular/NServiceBus/issues/3911 (this comment should summarize most of the behavior: https://github.com/Particular/NServiceBus/issues/3911#issuecomment-235274881).

**Comment by SimonCropp** [comment]
so given if someone using v5 has the setup i mentioned the new v6 behavior would be message loss?

**Comment by timbussmann** [comment]
since autosubscribe doesn't have a route for `IMyEvent`, yes. /cc @SzymonPobiega (this seems to the argument for the proposed v5 backward compat?) @bording @DavidBoike

**Comment by andreasohlund** [comment]
I'm with @SimonCropp this new behavior, albeit for a corner case, would practically mean message loss since if you update to v6 you would no longer get the events you would get in v5?

**Comment by SzymonPobiega** [comment]
I think my last couple of comments on #3911 are aligned with what @SimonCropp said. TL;DR
 * Yes, it is a message loss if somebody did not follow the upgrade guide carefully
 * When looking at MEMs as description of message ownership it makes sense to "inherit" the routes **both up and down** the type inheritance chain
 * For a given message type hierarchy, it should (ideally) be allowed to map only a single level i.e. either `IMyEvent` or (`OneEvent` and `TwoEvent`)

**Comment by andreasohlund** [comment]
>Yes, it is a message loss if somebody did not follow the upgrade guide carefully

Unfortunately I don't think that is acceptable, me and @danielmarbach had the same approach to the removed .retries queue but after talking to @udidahan we came to realize that it isn't ok to require users to read doco in order to avoid message loss and the decision was made to reintroduce a empty satellite for this version. I can't see how this is any different? (and I think more likely to happen compared to unclean shutdowns leaving messages in the .retries queue)

**Comment by timbussmann** [comment]
Yeah, although I think the scenario is incorrect in the first place, if that is supported in v5 the upgrade story must avoid message loss scenarios.

**Comment by SimonCropp** [comment]
If this should not be supported... would it be viable to throw on the subscriber if there is no exact handler when we subscribe in the mapping?

**Comment by timbussmann** [comment]
> If this should not be supported... would it be viable to throw on the subscriber if there is no exact handler when we subscribe in the mapping?

That may be worth investing whether to would work for all supported scenarios. The benefit with that approach would be that MEM and code first routing APIs would share the same behavior. /cc @DavidBoike @bording

**Comment by SzymonPobiega** [comment]
Let's move this disucussion over to https://github.com/Particular/NServiceBus/issues/3911 because we are discussing the same thing in two places.

**Comment by timbussmann** [comment]
so if I understood correctly, v6 contains the same behavior/bug as stated in the initial description again for MEM (while the code first routing api has the behavior described in https://github.com/Particular/NServiceBus/issues/1942#issuecomment-240695629 ). Should we close this as `won't fix` then if the goal is to get rid of MEM in v7? @SzymonPobiega @SimonCropp @Particular/nservicebus-maintainers

**Comment by SzymonPobiega** [comment]
After talking with @andreasohlund in the routing TF we decided to keep the V6 handling of message endpoint mappings as close to V5 as possible to minimize the risk of message loss or other problems. Since MEMs are scheduled to be removed in future and the fix for this issue is not trivial I propose to close this one with `won't fix`. @SimonCropp ?

**Comment by danielmarbach** [comment]
Closing this with Won't Fix based on https://github.com/Particular/NServiceBus/issues/1942#issuecomment-244848397
