### ISSUE TITLE
Support authenticated flag in MSMQ queue

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2239]
To restrict who can send to a queue, the queue needs to have the authenticated flag **on**, see
 ![capture](https://cloud.githubusercontent.com/assets/122651/3622616/9993b216-0e39-11e4-8879-9c2147e8b536.JPG)
and the sending code needs to set authenticated property of a messagequeue instance to true.

**Comment by DavidTuke** [comment]
Any update progress on this issue
Necessary to secure an ESB setup to ensure no spoofing can occur inside an AD managed domain

**Comment by johnsimons** [comment]
@DavidTuke what version of NServiceBus do you need this fix for ?

**Comment by DavidTuke** [comment]
Hi John;

Can this be updated in V5;

Currently on V4.  We will move to V5 if this is present and operational;

Security of internal transport very important to get in place for our Customer;

External security is via AS4 Messaging Protocols – all good there.
External Security Consultants are recommending we move to “Authenticated Sender” in internal MSMQ messaging;
Hence we need to be able to set this in NServiceBus configuration.

Thanks for the prompt response!

Regards,

David Tuke
Enterprise Architect

[Logo - Oban - small]

Oban Pty Ltd | Ground Floor 19-23 Prospect St | Box Hill 3128 | Australia
ABN 18 163 365 080
T: +61 3 9044 1702 | M: 0408 017 962 | F: +61 3 9044 1799
E: David.Tuke@obansolutions.com.au<mailto:David.Tuke@obansolutions.com.au> | W: www.obansolutions.com.au<http://www.obansolutions.com.au>

***NOTICE***
This e-mail may contain confidential or legally privileged material and if you are not the intended recipient, you are advised that Oban Pty Ltd does not consent to you reading or copying the material and does not waive any confidentiality or legal privilege associated with it. This e-mail may also contain material which is protected by copyright and if you are not the intended recipient, you are advised that Oban Pty Ltd has not consented to your reproduction of the material and there is no intention to provide you with an implied licence to exercise any of the rights of the copyright owner or an authorised licensee. If you have received this e-mail in error, please advise Oban Pty Ltd immediately by return e-mail or by telephone on 61-3-9236-1900.
The recipient of this e-mail is solely responsible for conducting such tests and virus scanning as may be necessary, before using any attachment, to ensure that the attachment does not contain any virus and that use of the attached materials will in no way corrupt the recipient's data or systems or those of any other person.

**Comment by johnsimons** [comment]
@davidalpert thanks for the info, I'm raising this internally, hope to get an answer to you very soon,

**Comment by johnsimons** [comment]
@indualagarsamy can you get back to @DavidTuke on the scheduling for this issue?

**Comment by indualagarsamy** [comment]
@DavidTuke - We are currently analyzing this issue. One of the main things that we have to consider is backwards compatibility and how turning on this authentication can impact existing customers. Especially if they have messages in the queue and they upgrade to use this new authentication setting, those messages could end up in DLQ, etc. This requires some analysis on our end to ensure that we have good documentation in place and to also have an upgrade guide for users that would like to use this feature.  We'll keep you posted on the progress of this issue. I'll have an update for you by next week. cc / @johnsimons

**Comment by indualagarsamy** [comment]
@DavidTuke - Are you using ActiveDirectory integration with MSMQ at the moment?

**Comment by indualagarsamy** [comment]
Hey @DavidTuke - Thanks for your patience.  I wanted to keep you posted on my findings:

After I started to dig into the details of this issue, I no longer believe that the `Authenticated` checkbox is valid option when AD integration is turned off. 
- When sending messages using the `UseAuthentication` property set on the message, MSMQ uses the certificate in AD for that user account to be used to sign the message. Once this message is delivered to the destination, and on the receiver, AD checks the certificate to validate the sender. Even when using AD, [there are additional details to ensure that this works properly](http://blogs.msdn.com/b/johnbreakwell/archive/2009/01/23/how-to-send-authenticated-msmq-messages-without-using-a-domain-account.aspx) as the sender could be a service running as LocalSystem. 
- While it is possible to use an external certificate to sign the message when MSMQ is in Workgroup mode, the receiving side would need to know to use that cert! And this would result in an error. In order to use the external certificate to do custom authentication, we'd need to turn the `Authenticated` check box off and do some custom check on the receiving side to ensure that the message is valid. 
See the section `External Certificates in Workgroup Mode` in [this article](http://winterdom.com/2011/09/msmq-and-external-certificates).

NServiceBus does not support MSMQ with Active Directory turned on as AD integration sometimes changes how MSMQ does addressing and IFAIK machine names are replaced with GUID's and a few other issues.
I am also trying to do some analysis on what it would take on our side to allow an external certificate and the authentication based on that. 

Would using SqlTransport be an option for you?

**Comment by johnsimons** [comment]
@indualagarsamy how do we proceed here? Can we close this one ?

**Comment by johnsimons** [comment]
@indualagarsamy I'm closing this one as won't fix, because of the reasons you have provided, if you think it should be fixed, please reopen it.

**Comment by indualagarsamy** [comment]
@johnsimons - sounds good.
