### ISSUE TITLE
Add API for disabling AutoSubscribe

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2318]
currently we have this

```
    Configure.With(b => b.DisableFeature<AutoSubscribe>());
```

would be better and more consistent to have

```
    Configure.With(b => b.AutoSubscribe(settings => settings.Disable()));
```

**Comment by SzymonPobiega** [comment]
After having a discussion with @dvdstelt 
 * `AutoSubscribePlainMessages` should be removed because it encourages bad developer behavior. If a user wants to subscribe to a command, he should explicitly use `busSession.Subscribe`
 * There is more features that do not have an explicit API (e.g. SLRs)
 * Having a `Disable` method on the settings object can be confusing because users can write code like this

```
busConfig.AutoSubscribe().Disable();
busConfig.AutoSubscribe().DoNotAutoSubscribeSagas();
```

in which case it is not clear if the feature is disabled or only configured for autosubcribe to handlers (invocation order can matter).

**Comment by SzymonPobiega** [comment]
Un-assigning myself from this as I don't know what should be the next steps.

**Comment by andreasohlund** [comment]
Since we want to get the Subscribe/Unsubscribe methods out of the face of the users how about we do:

```

var explicitSubscriptionControl = config.DisableAutomaticSubscriptions();


explicitSubscriptionControl.Subscribe<OrderPlaced>();

```

that prevents users mixing auto and explicit subscriptions?

**Comment by SzymonPobiega** [comment]
How about `EnsureSubscribed`? I guess we should send a reply to each `Subscribe` message to let the subscriber know it has been successfully subscribed and can run happily.

**Comment by timbussmann** [comment]
I like @andreasohlund suggestion, seems like a nice move forward to remove subscribe operations from the session.

**Comment by timbussmann** [comment]
@SzymonPobiega what problem would this solve? Sounds like a dedicated issue to me?

**Comment by SzymonPobiega** [comment]
@timbussmann currently when you call `Subscribe` or rely on autosubscribe, the subscriptions on broker transport the subscriptions are ensured to be created. If there is a problem creating them, the endpoint will not start (autosubscribe) or the call to `Subscribe` will throw. This is not the case when using MDPS.

Now if we are moving towards a better, config time API, it makes sense to align these guarantees somehow or distinguish them on the API level.

On the other hand, I like what @andreasohlund proposed as a quick and easy win because it makes the API much better without deep changes to the core.

**Comment by timbussmann** [comment]
@SzymonPobiega that's definitely an interesting idea, but this seems to go somehow against the concept of messaging? This approach would couple endpoint startup time to the subscription-response and requires the publisher to be up and running, causing quite some coupling? How about raising this as a new issue to think it through?
