### ISSUE TITLE
Implement IAmStartedByMessages<T> as an explicit handler separate from IHandleMessages<T>

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#2389]
To simplify handler logic for case when Saga is started by a message T vs when it's handling a message of T during saga in flight, implement ```IAmStartedByMessages<T>``` explicitely in the following way:

```c#
public class InvoiceProcessingSaga : Saga<SomeSagaData>, 
IAmStartedByMessages<Message> /*Start*/, 
IHandleMessages<Message>/*Handle*/
    {
        public void Start(Message message)
        {
        }
        public void Handle(Message message)
        {
        }
  }      
```

A few benefits of this will be
 1. Explicit invocation of handlers and no ambiguity (saga started by message, or started by message and handles it later as well)
 * Initialization of saga data can be moved to ```Start()``` and separated from ```Handle()``` code, having less conditions in ```Handle()``` to verify message is just started vs in flight. 

//cc @johnsimons @indualagarsamy

**Comment by johnsimons** [comment]
Is this something we want to introduce as part of the changes already happening in #2669 ?
Not talking about doing in the same PR but in the same release.
@danielmarbach thoughts ?

**Comment by johnsimons** [comment]
Also, I wonder if
```c#
public void New(CreateInvoice message)
```
is more explicit ?

Would we execute both in order, New followed by Handle ? or just New//Start ?

**Comment by danielmarbach** [comment]
@johnsimons Here my thought:

I think we agreed on the larger saga improvement story already. So the question is in the sense of making messages auto start the sagas by default and opt-out from it I'd say we don't new to adjust the interfaces I introduced in #2669 to New/Start or anything else because we'll remove them anyway... Right?

**Comment by johnsimons** [comment]
@danielmarbach regardless how we going to address that, we still have the issue that @SeanFeldman describes here

**Comment by danielmarbach** [comment]
@johnsimons well the depends on how you look at it. If the majority of the cases is in the future will be auto-starting and we remove the `IAmStarted...` interfaces I'd say the confusion is minimized or gone

**Comment by johnsimons** [comment]
@Particular/engineers thoughts on this idea from @SeanFeldman  ?

Should we do it ? Vote

**Comment by andreasohlund** [comment]
I rather go in the direction of "all messages can always start the saga" which as @danielmarbach points out would make this a non issue.

I'm -1

**Comment by indualagarsamy** [comment]
From a high level design concept, a saga is something that deals with multiple messages. If we go with that, then the user should just have to indicate just what messages participate in a saga. I think its a safer default to have the first message involved to auto start the saga if its' not already started. This is something people forget to do in the current state. They have multiple messages, but not mark the other as IAmStartedByMessages<T> and instead have IHandleMessages<T> and then when that message arrive out of order, they are screwed. Auto starting sagas is a safer default.  I think that's what @andreasohlund and @danielmarbach are implying. I like that approach much better. I am -1 for this interface change.

**Comment by johnsimons** [comment]
We are not going this way instead we are making all messages can start a saga.

**Comment by johnsimons** [comment]
@danielmarbach @andreasohlund please add a reference to issue regarding "all messages can start a saga", I could not find it.

**Comment by mauroservienti** [comment]
> we are making all messages can start a saga.

Is the above really what customers and we want? Does it mean that I will be able to send a `CancelOrderCommand` to a non existing saga and a new one will be fired up?

**Comment by andreasohlund** [comment]
>CancelOrderCommand to a non existing saga and a new one will be fired up?

What if the PlaceOrderCommand gets stuck in SLR/Error queue and the website allows the users to click cancel order?

In short: Should users really assume that cancel comes before PlaceOrder?

**Comment by mauroservienti** [comment]
That is the exact scenario, if `Cancel` comes before `Create` and with `Cancel` we create a new Saga by default we charge on the user code consistency checks that actually are done by the `IAmStartedBy` thing. I like the idea of having an explicit way, the interface, to express that something can start a saga and something cannot, we can also build visualizations around that.

**Comment by danielmarbach** [comment]
@mauroservienti the majority of cases order should not be assumed and therefore most of the `IHandleMessages` implementations on the sagas should actually be `IAmStartedBy`. Our idea is to change so that a message is assumed to start the saga and the user can opt out from that behavior by config.

**Comment by mauroservienti** [comment]
@danielmarbach maybe I am missing the big picture, so please correct me if I am wrong. I'm not assuming order at all, but in most scenarios, business scenarios, order is important, you cannot `ship` a non exiting `order`.

So imagine that the endpoint handling order is: `ShipOrder`, `CreateOrder`

With current NServiceBus version `ShipOrder` will be rejected, and queued again, because only `CreateOrder` is handled as `IAmStartedByMessages<CreateOrder>`.

With the new version? As far as I have understood `ShipOrder` can create a new saga instance, but there is nothing to ship, so now the saga user code needs to check this new condition a manually throw because from the business point of view you cannot ship something that does not exist yet.

Am I missing something?

**Comment by indualagarsamy** [comment]
@mauroservienti - In messaging systems, one should not /cannot assume the order of processing. So, you should assume that either of the messages i.e. ShipOrder or CreateOrder could be handled first. In situations where you are waiting that both messages occurred, it shouldn't be a problem and yes users should do that. Otherwise, they'd lose a message. i.e. ShipOrder came in first and there's no order, code will invoke SagaNotFound handler. That's a common mistake people do. But automatically starting the saga, we protect our users a little with the message out of order scenario. Does that make sense?

**Comment by danielmarbach** [comment]
You’re scenario can be achieved as well with the new API. They can opt-out
by saying ShipOrder should not start the saga. We are only inverting the
way we do it.



*From:* Mauro Servienti [mailto:notifications@github.com]
*Sent:* Montag, 20. April 2015 11:30
*To:* Particular/NServiceBus
*Cc:* Daniel Marbach
*Subject:* Re: [NServiceBus] Implement IAmStartedByMessages<T> as an
explicit handler separate from IHandleMessages<T> (#2389)



@danielmarbach <https://github.com/danielmarbach> maybe I am missing the
big picture, so please correct me if I am wrong. I'm not assuming order at
all, but in most scenarios, business scenarios, order is important, you
cannot ship a non exiting order.

So imagine that the endpoint handling order is: ShipOrder, CreateOrder

With current NServiceBus version ShipOrder will be rejected, and queued
again, because only CreateOrder is handled as
IAmStartedByMessages<CreateOrder>.

With the new version? As far as I have understood ShipOrder can create a
new saga instance, but there is nothing to ship, so now the saga user code
needs to check this new condition a manually throw because from the
business point of view you cannot ship something that does not exist yet.

Am I missing something?

—
Reply to this email directly or view it on GitHub
<https://github.com/Particular/NServiceBus/issues/2389#issuecomment-94406642>
.

**Comment by mauroservienti** [comment]
> You’re scenario can be achieved as well with the new API. They can opt-out
by saying ShipOrder should not start the saga. We are only inverting the
way we do it.

So it is a huge breaking change, this is the only thing I am pointing at, I'm not assuming order at all. I would personally prefer the opposite, introduce the new behavior and let me opt-in, not force me to opt-out

**Comment by indualagarsamy** [comment]
@mauroservienti does raise a good point. 
@danielmarbach @andreasohlund - what about this scenario. Say a message comes in for which a saga has been marked complete, currently we invoke SagaNotFound handlers. In the new model, it will always start a phantom saga. Users will now have to switch / set the configuration for this behavior. I can how that can be confusing as well. This setting, is that going to be at the saga level or at the endpoint level? Is there a different issue where I should be discussing this?

**Comment by SeanFeldman** [comment]
We're talking about being very explicit and clear about intentions with NSB. Example: rather than deriving endpoint name from a namespace, we ask user to set it explicitly through `BusConfiguration`. Yet with `Sagas` we're not enforcing a way to clearly indicate what starts a saga. I tend to gravitate toward a scenario where a business process starts with a clear message.
