### ISSUE TITLE
Make the saga id generation scheme pluggable

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2445]
Since the current hardcoded scheme is Combguid which is ideal for sqlserver but less ideal for other stores like RavenDB. We also need an option when the user can specify a func of message since that will allow them to use one of the message properties as their saga id. This will allow for a special type of "single correlation id" saga where everything is synced around that one id.

This opens up scenarios like:
- Skipping the unique document in raven and save 1 write and 1 extra read per saga
- Allow us to use the eventstore to store sagas (since it doesn't have cross stream "consistency")

cc @jbogard 

This one depends on:

https://github.com/Particular/NServiceBus/issues/2444

**Comment by SeanFeldman** [comment]
Azure persistence performance is severely affected by this due to inability to set the partition key to the saga id. With customers that have multiple instances of a saga or multiple sagas are hitting the limitation of azure storage where querying on anything other than partition key is causing a full table scan, degrading the performance.

**Comment by Scooletz** [comment]
https://github.com/Particular/NServiceBus/issues/2445#issuecomment-175232382 has been addressed by https://github.com/Particular/PlatformDevelopment/issues/634 @SeanFeldman
