### ISSUE TITLE
Dump logs when acceptance tests fail

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#2524]
Right now we don't capture logs. We should buffer the logs and dump them if the test fails

**Comment by danielmarbach** [comment]
The context contains all the logs capture and we also trace all logs, see https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTesting/ContextAppender.cs#L110 Do we really need that feature since when you debug an acceptance test you can dump the content of the context manually. Isn't that enough?
