### ISSUE TITLE
Make AcceptanceTest framework easier to adopt in new solutions

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#2636]
At the moment, even after we pull down the `NServiceBus.AcceptanceTesting` framework nuget, it still is some effort to try and define the contexts, the test setup harness, etc. 
What can we do to try and minimize that?

cc / @andreasohlund

**Comment by johnsimons** [comment]
@indualagarsamy lots of things can be done to improve the situation.
We need to start prototype a new api and see how it goes, maybe start a slack channel where we can discuss options?

Also since the AT framework is plan for one day to be released to our users, maybe open a requirements issue instead?

**Comment by johnsimons** [comment]
@indualagarsamy this is a very generic issue, can we close this and raise it in requirements?
