### ISSUE TITLE
ASP.NET vNext folder security has changed

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2649]
Our assumptions where to save logging files may need to be re-evaluated if we are to support ASP.NET vNext.

### Current assumptions
We use `HttpContext.Current.Server.MapPath("~/App_Data/")` for websites

**Comment by johnsimons** [comment]
@SimonCropp do you mind documenting our current assumptions ?
@yvesgoeleven You have raised this concern in slack, do you mind expanding on this and explain what is going to break ?

**Comment by SimonCropp** [comment]
@johnsimons http://docs.particular.net/nservicebus/logging-in-nservicebus#rolling-file

**Comment by yvesgoeleven** [comment]
After thinking it a bit through, the issue I see is going to lead to a whole list of issues we will have to deal with if we want to support vnext, this is just one 

PS: I'll note some of my thinking down here, but maybe the list needs to move somewhere else to keep up to date as we learn more about the consequences

What in fact happens in vnext is that the website application folder is split into 2 parts: approot (which contains sources & packages and is secured down) & wwwroot (which contains files and is easily accessible).  HttpContext.Current.Server does not exist anymore either, you need to use and implementation of IHostingEnvironment now, which gives you the location of the webroot folder. We probably need to move logging output to somewhere below this webroot folder.

Secondly compilation happens at runtime now as well, using Roslyn, based on the project.json file for dependency definitions combined with files & packages in the approot folder. This will break the way we do assembly scanning and dynamic assembly loading, as there are no assemblies to scan anymore or they are in the nuget packages underneath the approot folder (which is not easily accessible as far as I know up till now). 

Next to the load location issue, I haven't been able to figure out how to load assemblies that haven't been referenced in the project.json file either. Mainly because of the fact that asemblies of their dependencies are not present in the load context when roslyn tries to compile. (guess there must be a way to dynamically download dependent nuget packages & tell roslyn to use those dependencies, but I don't know how yet). As we rely on dynamic assembly loading a lot, we will also need to figure this out...

There is probably more, we will have to investigate vnext a bit more imo... a lot has changed

**Comment by johnsimons** [comment]
From what I gather it seems there are quite a few little changes to make our code CoreCLR compliant.

I'll close this issue and open individual issues as we hit them.

**Comment by yvesgoeleven** [comment]
Makes sense, also learned yesterday that config sections no longer exist
