### ISSUE TITLE
Support for multiple [Unique] attributes on a single saga data instance

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#2662]
Currently we enforce that a `ContainsSagaData` instance has only one property decorated with the `Unique` attribute.

--

moved from https://github.com/Particular/NServiceBus.RavenDB/issues/60

**Comment by andreasohlund** [comment]
Since v5 already makes correlated properties "auto unique" https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Sagas/TypeBasedSagaMetaModel.cs#L77 I'd say we should obsolete the `Unique` attribute and instead add either a new [NonUnique] attribute or even better a fluent option to make a correlated prop non unique. 

This new proposed fluent api has already been discussed here:

https://github.com/Particular/NServiceBus/issues/2080#issuecomment-59037539

With this in mind is this one still relevant?

**Comment by mauroservienti** [comment]
Are these correlated properties used by the NServiceBus.RavenDB package? because the concern is there, I opened the issue there but @synhershko sent me here.

**Comment by andreasohlund** [comment]
Not currently. I've raised an issue to track this https://github.com/Particular/NServiceBus.RavenDB/issues/64

**Comment by mauroservienti** [comment]
ok, thanks. I'll close this one.
