### ISSUE TITLE
Create an option to throw an exception if there is no subscriber

### ISSUE THREAD

**Issue by pablocastilla** [Particular/NServiceBus#2688]
Hi!

In our current project we would prefer to have an option to throw an exception if there is no subscriber for an event. We only have events that have subscribers, sometimes we forgot to define an endpoint and for us it is an error, but for NSB is a normal behavior.

Maybe it is useful also for others.

**Comment by SimonCropp** [comment]
@pablocastilla so, just to be clear, when u call `Publish` on a given endpoint, if it doesnt find any subscribers you want to exception

**Comment by johnsimons** [comment]
Hi @pablocastilla 

Yes, that would be useful for certain scenarios, however because the NServiceBus framework supports broker transports as well and those have pub/sub natively, it is not possible to include such a feature in a generic "frameworkish" way.

The good news is that if you are using a transport that does not include pub/sub natively, we can provide you with the means to achieve this in your code base.
So what transport are you using @pablocastilla ? And what version of NServiceBus are you on ?

**Comment by pablocastilla** [comment]
Ooooooooook, I understand the issue.

We are using MSMQ. We have already implemented our own ISubscriptionStorage to do so, but I thought it could be useful for others, but I didn't realize that we could have other transports.

**Comment by johnsimons** [comment]
@pablocastilla if you tell me your NServiceBus version we can help you achieve this ?

**Comment by pablocastilla** [comment]
Thanks so much, we are using 5.2 but we don't need it at this point. We have  implemented a ISubscriptionStorage for having the subscription in database without autosubscription and with scaleout. So we throw an exception if no subscription is found.

**Comment by johnsimons** [comment]
Cool @pablocastilla, no worries :smile:
