### ISSUE TITLE
Deprecate IAuthorizeSubscriptions

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2725]
### Reasons
Because brokers do not need to send a Subscribe/Unsubscribe message to the publisher, `IAuthorizeSubscriptions` is never invoked for these transports, making it misleading.

This feature also does not provide any meaningful incremental security for a solution.

### Way forward
Guiding users to use a behavior/custom substorage implementation instead if they happen to be using it.

**Comment by SimonCropp** [comment]
@johnsimons so where is the guidance?

**Comment by SimonCropp** [comment]
Wouldnt it be better to rename it  IAuthorizeMsmqSubscriptions? And only enable for the transport?

**Comment by johnsimons** [comment]
@SimonCropp 
> so where is the guidance?

Not done yet, want to do it ?

**Comment by udidahan** [comment]
If the guidance hasn't been done, should this issue really be closed?

**Comment by johnsimons** [comment]
Issue raised in docs

**Comment by SimonCropp** [comment]
So as far as I can tell the main problem of this feature is that people are using in a context they should not. I think rather than removing the feature we could address those concerns in a different way. How about a combination of

 * Create a new `IAuthorizeMsmqSubscriptions` (or similar for other transports that support it)
 * Obsolete with warning `IAuthorizeSubscriptions` and point to the above
 * Add better (ne any) documentation about how this feature works

**Comment by danielmarbach** [comment]
@johnsimons @SimonCropp What is required to push the doco and implement the [proposed changes](https://github.com/Particular/NServiceBus/issues/2725#issuecomment-98553781) in V6?

**Comment by johnsimons** [comment]
@danielmarbach this issue came to live because of #987, as far as I understand the coding is done, all is left is to provide some guidance, see https://github.com/Particular/docs.particular.net/issues/613.

That said I wonder if the guidance should be an on-demand effort instead.

**Comment by andreasohlund** [comment]
Doco is complete, closing this
