### ISSUE TITLE
Make contexts mockable

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2744]
So I just tried to unit test a custom behavior and it was very difficult to a context instance to pass into it. The reason is that there are significant numbers of parameters and state to create a context.

So should our context classes be mockable?

**Comment by andreasohlund** [comment]
From the work I'm seeing we're moving towards contexts with no properties at all on them (just passing the parent context in) so I'd say we should hold off with this one to validate my statement first?

**Comment by andreasohlund** [comment]
@timbussmann this seems to have been addressed in v6?

**Comment by timbussmann** [comment]
I think we addressed this by
* using interfaces which are easier to fake/mock
* we provide basic testable implementations in the core solution (`TestableXyContext`) and with the `NServiceBus.Testing` package otherwise

Closing this. Please feel free to reopen if you think the currently available solutions are not good enough.
