### ISSUE TITLE
Obsolete all WellKnownStepIds

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#2783]
Currently the way we provide WellKnownStepIds is flawed. We obsoleted a few, some just disappeared and for a majority of steps we don't provide WellKnownStepIds. We need a uniform way to handle it.

### Arguments for removal of WellKnownStepIds

* Extending the pipeline is an advanced thing. Only a small portion of our users actually need to do it. And if they do they mostly only extend which means inheriting from the right strongly typed context in a given stage is enough.
* Only a really small portion of the small portion of the users will replace existing behaviors. Although it is possible, the implications of replacing a behavior are not trivial and you have to really understand what you are doing. Therefore forcing users to read up the id of an existing behavior doesn't hurt
* An almost non-existing user base might do some much trickery that they need to be placed before or after a given behavior. Again the same argument as when you replace an existing behaviors apply.

### Plan of Attack

* Make sure we are nowhere using the type name or fully qualified type name as a step id, if any replace those with strings instead of the type name
* Let's obsolete `WellKnownStepIds` constants with message telling users to use stages instead
* update upgrade guide for InsertBefore/After: use stages instead
* Update recoverability sample
* Check docs/samples for usages of InsertBefore/After and WellKnownSteps (e.g. Stream sample)

**Comment by andreasohlund** [comment]
@Particular/nservicebus I'm starting to question the value of the wellknown steps. What would users loose if we stopped to provide them but instead just using the strings?

**Comment by SeanFeldman** [comment]
@andreasohlund the way I read @danielmarbach message, he's talking about NSB users that would have to type in strings, just like in the [highlighted code](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Faults/MoveFaultsToErrorQueueBehavior.cs#L74-L76). This is ok when you know the step name, but if you're trying to figure out those, it's going to be more effort and a small typo will generate unnecessary effort to troubleshoot failure. 

I also have noticed that we're using settings keys as plain strings, and as a transport implementer, those become "magic strings" to know about. NSB user that ties to implement a transport, would have a hard time to know that [this magic string](https://github.com/Particular/NServiceBus/blob/52924ea7272e169efea62ef1ab665b129cadd8a2/src/NServiceBus.Core/ConfigureQueueCreation.cs#L25) represents the setting key for topology creation flag.

**Comment by danielmarbach** [comment]
@seanfeldman exactly!

**Comment by SimonCropp** [comment]
basically what i had to do here https://github.com/Particular/NServiceBus/commit/e721d12297dae945ad0c0674128e6a0d50ab37d1

**Comment by adamralph** [comment]
This doesn't sound like a refactoring.

**Comment by danielmarbach** [comment]
@adamralph Can you make sure you express a bit more why think think it doesn't sound like a refactoring?

**Comment by adamralph** [comment]
@danielmarbach 

It sounds like a functional change:

> This can be a difficult experience for users

If the issue will change the user experience then there must be something functional change.

> I also have noticed that we're using settings keys as plain strings, and as a transport implementer, those become "magic strings" to know about. NSB user that ties to implement a transport, would have a hard time to know that this magic string represents the setting key for topology creation flag.

I presume the proposal is to move away from magic strings, which implies an API change.

**Comment by danielmarbach** [comment]
I think this highlights that we haven't made a decision. Depending on how we solve it, it can be a refactoring or a redesign. An intermediate simple step would be to leave the WellKnownStepIds and extend it with the missing ones. Or more involved story would be to ditch the WellKnownStepIds

**Comment by adamralph** [comment]
Thanks @danielmarbach - marking as a discussion while we refine it.

**Comment by andreasohlund** [comment]
Since replacing and removing is somewhat of an edge case, 99% of the users will add behaviors I propose we

1. Remove the WellKnownStepIds
2. Make sure to not change step ids in patches and minors by dumping them into https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt so that out api approvals will catch any changes

Should we want doco we can write a sample in docs that dumps the step ids just like simoncropp did for the "interface lifecycle " - http://docs.particular.net/samples/startup-shutdown-sequence/

**Comment by bording** [comment]
Even if you're just adding a new behavior, you often need to know the id of a behavior for ordering purposes, for example when calling `InsertAfter` or `InsertBefore`.

Without having some helper class like `WellKnownStep` you have no way of knowing what the ids are.

I like the idea of documenting the ids, but I don't like that being the only way to know what they are, without having to dig through the code and find the behavior classes.

Instead of removing the WellKnownStepIds, I'd prefer to go in the other direction. I think it would be better to remove the ability to pass in an arbitrary string for an id and instead require some sort of Step/Behavior id class.

It's a much better user experience to be able to see the behavior ids in intellisense vs. being forced to go to the docs to look up a magic string.

**Comment by SeanFeldman** [comment]
:+1: to what @bording said. Not in favour of raw strings.

**Comment by andreasohlund** [comment]
>Even if you're just adding a new behavior, you often need to know the id of a behavior for ordering purposes, for example when calling InsertAfter or InsertBefore.

Insert/After is IMO always a smell ( @SzymonPobiega @danielmarbach please chime in) so this is not a good argument. We should get rid of insert after/before since stages has kind of made them moot. 

>Instead of removing the WellKnownStepIds, I'd prefer to go in the other direction. I think it would be better to remove the ability to pass in an arbitrary string for an id and instead require some sort of Step/Behavior id class.

I've thought about this as well but called YAGNI on it since the users can use the pipeline stages to find the slot where they should inject their behavior. If they have to think about going before/after behaviors inside the same stage we've failed IMO. I'm definitely willing to be convinced otherwise.

**Comment by danielmarbach** [comment]
Totally agree with @andreasohlund, `InsertAfter` and `InsertBefore` should no longer be used since we have stages. Most of the time it is an indicator that you are doing something wrong. So by removing the WellKnownStepIds we make it harder to use InsertAfter and Before (In fact we might even debate if we should kill those methods entirely).

Have an automated thing in place which dumps out the ids of the steps should be sufficient enough. Let's face it:

* Extending the pipeline is an advanced thing. Only a small portion of our users actually need to do it. And if they do they mostly only extend which means inheriting from the right strongly typed context in a given stage is enough.
* Only a really small portion of the small portion of the users will replace existing behaviors. Although it is possible, the implications of replacing a behavior are not trivial and you have to really understand what you are doing. Therefore forcing users to read up the id of an existing behavior doesn't hurt
* An almost non-existing user base might do some much trickery that they need to be placed before or after a given behavior. Again the same argument as when you replace an existing behaviors apply.

So I'm :-1: to keep `WellKnownStepIds` and
:-1: to introduce another concept replacing the `WellKnownStepIds`

**Comment by timbussmann** [comment]
> Insert Before/After is IMO always a smell ( @SzymonPobiega @danielmarbach please chime in)

I disagree. From some samples we saw this it's quite common to configure order within the stage. This was often related to retries but also on other behaviors & stages.

I'm all :+1: to replace `WellKnownSteps` since they are quite misleading with the current stages, since they don't state anything about which stage a step is registered at. So it's possible to register a behavior to come before another, although this isn't even possible because of the order of the stages. But until we have a better API (don't we have an issue about removing `WellKnownSteps`?), I think we should add the missing behaviors.

**Comment by andreasohlund** [comment]
>I disagree. From some samples we saw this it's quite common to configure order within the stage. This was often related to retries but also on other behaviors & stages.

Can you give some examples? (I'm not convinced that this is true any more)

**Comment by timbussmann** [comment]
Just checked and it indeed seems like we're using it only in one sample here (+ one in a snippet): https://github.com/Particular/docs.particular.net/blob/master/samples/pipeline/stream-properties/Version_6/Shared/StreamConfig.cs#L36

Thought there were more. From that perspective I see the point in removing the steps. It still feels kinda wrong since we're using that internally because we easily know the required ids. This basically makes our "internal" API more powerful because we can order behaviors within a stage where this is only achievable with a significant effort by the user (or support by us). If we're good with that, I'm ok too with removing the steps. It seems to make sense to "hide" configuration options which couple user behaviors to our internal behaviors, but I don't think we can entirely avoid such scenarios.

**Comment by andreasohlund** [comment]
>it still feels kinda wrong since we're using that internally because we easily know the required ids.

I challenge you to come up with an example in the core where we are using the ID's in a valid way? (last I went through the usages they where all hacks/design smell/workarounds for missing stages)

**Comment by indualagarsamy** [comment]
on the topic of WellKnownStepIds, etc and what's listed on the GH issue description, take this example.
I was trying to replace behavior for IManageMessageFailures. This now has to be done as part of the pipeline. Our version 5 users are not used to doing this in the pipeline for this. They implement a [class that implements IManageMessageFailures](https://github.com/indualagarsamy/CustomFaultManagerMigration/blob/master/Version_5/CustomFaultManager.cs)

In Version 6, they will now have to replace existing pipeline behavior. Without the knowledge of well known things that can be replaced as part of the pipeline, how can the user know what string to replace? While the upgrade guide doco will solve the problem for this use case, I wonder what about the other cases. What are the common cases? Should we just have a good list of pipeline samples for the most common case scenarios for the behavior replacing scenarios? I totally agree about the InsertBefore/After, just like spelunking for the behavior Id to replace, where it should go before or after won't be an easy thing to do either.

**Comment by bording** [comment]
If we do want to remove the `WellKnownSteps` (and the arguments for doing so seem to be winning) then I'd say we should pair that removal with removing the the `InsertAfter` and `InsertBefore` methods. Keeping those around while removing the `WellKnownSteps` seems to be pointing people in the wrong direction since sounds like we don't need them anymore.

**Comment by danielmarbach** [comment]
I agree @bording

On Tuesday, March 8, 2016, Brandon Ording <notifications@github.com> wrote:

> If we do want to remove the WellKnownSteps (and the arguments for doing
> so seem to be winning) then I'd say we should pair that removal with
> removing the the InsertAfter and InsertBefore methods. Keeping those
> around while removing the WellKnownSteps seems to be pointing people in
> the wrong direction since sounds like we don't need them anymore.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus/issues/2783#issuecomment-193527251>
> .
>


-- 
*Don't miss the Async/Await Webinar Series*
*• Learn more <http://go.particular.net/l/27442/2016-02-15/681bjl> →*

**Comment by andreasohlund** [comment]
>Our version 5 users are not used to doing this in the pipeline for this. They implement a class that implements IManageMessageFailures .In Version 6, they will now have to replace existing pipeline behavior. 

I thought the replacement (at least in 95% of the cases) is hooking up to the error notifications http://docs.particular.net/nservicebus/errors/subscribing-to-error-notifications. What is the use case for replacing the steps?

**Comment by indualagarsamy** [comment]
@andreasohlund - The intent is not to subscribe for error notifications, but to actually have a custom error handling policy. Which is what the IManageMessageFailures used to provide. We do that in SC as well when dealing with IAdvancedSatellite.

**Comment by andreasohlund** [comment]
>but to actually have a custom error handling policy

Given that you can have a custom retry policy what's left to "customize"?

**Comment by indualagarsamy** [comment]
You might not want to send the message to the error queue. You might route the message elsewhere. 
Asking the user to subscribe to notifications assumes that the message will end up in the error queue always. The user had control of that in v5.

**Comment by indualagarsamy** [comment]
@andreasohlund - I think we are discussing things specific to https://github.com/Particular/NServiceBus/issues/3563  here. 

Back to this issue, when replacing steps or using the pipeline, it makes sense to document what the well known customizable stages are and to provide adequate scenarios in the pipeline documentation. 

@danielmarbach - the links in the issue description don't work.

**Comment by timbussmann** [comment]
Replacing the MoveFaultsToErrorQueueBehavior is quite a drastic change to NServiceBus. I think replacing steps is always for very special use cases and for advanced users not a common usage scenario. From that perspective It doesn't seem to bad to use magic strings (or move them to the behavior e.g. `MoveFaultsToErrorQueueBehavior.StepId`).

In the end you end up with a much better solution to add a custom behavior catching exceptions before the `MoveFaultsToErrorQueueBehavior` to handle your custom logic and fallback to the existing in case you fail to handle certain failures.

**Comment by danielmarbach** [comment]
So here is a proposal to proceed:

* Make sure we are nowhere using the type name or fully qualified type name as a step id, if any replace those with strings instead of the type name
* Let's get rid of `WellKnownStepIds` constants
* Add an approval test which outputs all step ids and freeze them in the core
* Use the approval test to generate/update the documentation with the ids
* Leave `InsertAfter` and `InsertBefore` as is right know and tackle it as a separate prioritizable item

**Comment by timbussmann** [comment]
:+1: sounds good to me

**Comment by danielmarbach** [comment]
See also https://github.com/Particular/NServiceBus/issues/2838

**Comment by danielmarbach** [comment]
More evidence

https://github.com/Particular/NServiceBus/issues/2843
https://github.com/Particular/NServiceBus/issues/2841

**Comment by danielmarbach** [comment]
Fleshed out the description to reflect arguments for removing the step ids and the latest PoA idea

**Comment by bording** [comment]
> Make sure we are nowhere using the type name or fully qualified type name as a step id, if any replace those with strings instead of the type name

If we are going to do this, why not remove the ability to register a step with a type name altogether? What's the benefit of keeping it?

**Comment by indualagarsamy** [comment]
Going back to the original issue, I think this assumption is somewhat incorrect.

> Extending the pipeline is an advanced thing. Only a small portion of our users actually need to do it. And if they do they mostly only extend which means inheriting from the right strongly typed context in a given stage is enough.

What is this assumption based on? How do we know that only a small portion of our users need this? 
Here's an example.  IManageMessageFailures was a fairly very easy thing to do in v5. To do this in V6, we need to add a behavior, register it using  StepIds and Insert Before and Insert After.
https://github.com/indualagarsamy/CustomFaultManagerMigration/blob/master/Version_6/CustomErrorHandlingBehaviour.cs#L33-L47

>Only a really small portion of the small portion of the users will replace existing behaviors. Although it is possible, the implications of replacing a behavior are not trivial and you have to really understand what you are doing. Therefore forcing users to read up the id of an existing behavior doesn't hurt

Again, how are we assessing impact? While I do agree that when replacing behaviors, its super important to see what the existing behavior is, I don't see how that ties in with a well known Id vs a magic string.  

I think well known constants are still better than magic strings. Can we backlog this to a time where where can remove Steps and rename to Stages, clean up Ids, Remove the need for having to register before / after, at a time after v6 release? In other words, does this need to be done for v6?

**Comment by danielmarbach** [comment]
@indualagarsamy I agree that some part of it doesn't have to be done for v6. Fact is as `WellKnownStepIds` currently stand they are incomplete, not properly obsoleted and therefore wrong. I'd be OK to backtrack on this proposal and then raise another issue to properly add WellKnownStepIds for every behavior we have internally. 

Regarding the question about the assumption. This comes up every time we argue things around the pipeline and behavior. I might be cargo-culting.

**Comment by indualagarsamy** [comment]
>I'd be OK to backtrack on this proposal and then raise another issue to properly add WellKnownStepIds for every behavior we have internally.

@danielmarbach - This sounds good. 
Then we can clean up the pipeline as a well concerted but separate effort.

**Comment by timbussmann** [comment]
What are the implications if we don't consider this for the initial v6 release?

**Comment by SimonCropp** [comment]
@andreasohlund 

> Should we want doco we can write a sample in docs that dumps the step ids just like simoncropp did for the "interface lifecycle 

I dont think that is a "complete" way of documenting it. since step ids can exist in many downstream repos. u would need a sample for every downstream to capture them. also at runtime it is not possible to determine which steps are injected via conditional logic.

I had a look into deriving this stuff from static analysis using mono.cecil. but it is not possible to do in a complete way since the steps registrations API is not build to be friendly to static analysis . 

So we would need to maintain this in doco manually.

**Comment by andreasohlund** [comment]
I think we can obsolete all the wellknown steps and just go with strings since:

* Pipeline extension is an advanced use case
* Out of those that do insertbefore/after/replace is extremely rare so using the correct stage should be enough
* We don't guarantee that we don't change the order of our internal behaviors so users can't relying on it
* To do a replace you need to look at the existing code and most likely get help from us to get it right. In those cases looking up the string ID seems resonable

I propose that we obsolete the existing WellknownSteps and guides users to use a (wait for it) string :scream: 

That seems good enough especially if we're able to kill before/after and replace for vNext.

Bring out the pitch forks! :)

**Comment by timbussmann** [comment]
> I propose that we obsolete the existing WellknownSteps and guides users to use a (wait for it) string :scream:

:+1: let's just call it the "javascript experience" or something like that. No honestly, I agree with your arguments. Using the WellKnownSteps doesn't guarantee anything. We should clearly communicate that inserting before/after or replacing behaviors may even brake between patch releases. It's no braking change to move a behavior to a different stage which has zero impact on the public API).

**Comment by timbussmann** [comment]
closing this as this is done with #3791
