### ISSUE TITLE
Should message serialization check IsControlMessage ?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#2847]
so `DeserializeLogicalMessagesConnector` does a `IsControlMessage` and passes in a  `Enumerable.Empty<LogicalMessage>()`

however `SerializeMessagesBehavior` does not do a `IsControlMessage` where is used to in v5. 

So should `IsControlMessage` be used at the message serialization point or not?

And why the different naming between `SerializeMessagesBehavior` and `DeserializeLogicalMessagesConnector`

**Comment by andreasohlund** [comment]
Since Bus.Return is removed we no longer `send` control messages on the pipeline. We do use them for message driven pub sub, but that hooks into the dispatch part of the pipe, ie Serialize doesn't come into play. I think it's ok to not check on sends.

Receives on the other hand needs to check since control messages go through the receive pipe

Does this make any sense?

**Comment by SimonCropp** [comment]
should the deserialize behavior own that logic?

**Comment by SzymonPobiega** [comment]
@SimonCropp I would say no. Whatever comes to the serialization connector should be deserializable without any checks.
