### ISSUE TITLE
Make it so that it doesn't need ITimeoutState anymore

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#307]
As I see it is also needed to implement ITimeoutState in order to be able to use IHandleTimeouts. This is another restriction like ISagaMessage in the current implementation. I need to reference NSB in my message assemblies.

**Comment by pashute** [comment]
OK, no need. So any class is OK for timeout state?

That is not clear in the Timeout section of the Saga page in the documentation. 

In any case, ITimeoutState is not found in nsb.Saga anymore. 

What is the state class used for if at all. 
Could you please give an example perhaps add it to the page or open a "complex timeouts with state" page?

**Comment by andreasohlund** [comment]
>So any class is OK for timeout state?
That's correct, any class will do

>What is the state class used for if at all. 
It's used to allow state to be passed to timeouts of the same "type" if you need to set multiple of them

I've just added a section to our documentation on this topic with a better explanation and a example

http://docs.particular.net/nservicebus/sagas/#timeout-state

Does this make sense?

**Comment by pashute** [comment]
OK, you pointed me to the wrong link in the documentation.
You meant: Sagas Timeouts here:
http://docs.particular.net/nservicebus/sagas/timeouts

So now there are three issues:

1. The main Sagas article (http://docs.particular.net/nservicebus/sagas/)
when discussing timeouts (and not just at the end of the article) should
have a pointer to Sagas Timeouts (with a link) saying:
  *For more information about setting (requesting) and using timeouts see
Saga Timeouts.*

I already added a pull request there with a correction to the documentation.


2. There are 6 RequestTimeout overrides and no examples in the
documentation. It would be very constructive if various examples could be
given for using the RequestTimeout with the different parameters.

3. The XMLDocs and names of the variables in the code show inconcistent and
confusing information. For example the RequestTimeout(... TimeoutState
timeoutMessage )
So is it a message or a class with state?

Please correct and give the object and the variable a consistent name. You
probably would want to call the class TimeoutExtraInfo or OnTimeoutData, or
TimeoutCustomData
(so that its clear that in this class we are NOT dealing with the settings
of the timeout itself - like when it the timeout should be set, nor why or
how).

2015-05-13 9:54 GMT+03:00 Andreas Öhlund <notifications@github.com>:

**Comment by andreasohlund** [comment]
@pashute sorry for the bad link!

>There are 6 RequestTimeout overrides and no examples in the
documentation. It would be very constructive if various examples could be
given for using the RequestTimeout with the different parameters.

You're right, we'll add some doco that show the 3 relevant one (3 are obsoleted)

>the XMLDocs and names of the variables in the code show inconcistent and
confusing information. For example the RequestTimeout(... TimeoutState
timeoutMessage )
So is it a message or a class with state?

Its a class with state from the user perspective. From an implementation perspective it does get sent as a message but that's not relevant for the end user

I'll make sure xmldocs and parameter names get updated!

Thanks for helping us improve our doco, keep it coming!
