### ISSUE TITLE
Shouldn't MessageProcessingAbortedException be public

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3216]
Don't the transports implementations of `IPushMessages`need to catch this exception ?

It seems the [MSMQ impl](https://github.com/Particular/NServiceBus/blob/a9def8b16c7ac3e428fb5747dbc553517b8505ed/src/NServiceBus.Core/Transports/Msmq/MessagePump.cs#L163-L166) is catching it and ignoring it , is that the expectation ?

**Comment by andreasohlund** [comment]
Correct, @tmasternak started down this path, not sure what the status is

**Comment by tmasternak** [comment]
@johnsimons MessageProcessingAbortedException is an exception used by recoverability features (details [here](https://github.com/Particular/NServiceBus/issues/3044)). Transport (IPushMessage impl) is expected to return message back to the input queue (rollbacking any transactions if applicable). That being said MessageProcessingAbortedException should not be counted for critical errors and circuit braking and that's why it's handled differently. 

This is how it is currently done in [SqlTransport](https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Receiving/MessagePump.cs#L150) but I think it should be made public. I'll create a pull request for that and we can discuss further.

**Comment by johnsimons** [comment]
Thanks @tmasternak, and yes that impl of sqltransport shouts public everywhere :)

**Comment by timbussmann** [comment]
`MessageProcessingAbortedException` has been removed and we use cancellation tokens now: https://github.com/Particular/NServiceBus/pull/3254. I think we can close this one.
