### ISSUE TITLE
Missing newlines in xml

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#3431]
in v5
```
<?xml version="1.0" ?>
<MessageToSend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://tempuri.net/Snippets5.Headers.Writers">
<LargeProperty1>
<Key>2016-02-01_14\1ac6a39a-2a2f-4775-836f-5164cf757ad2</Key>
<HasValue>true</HasValue>
</LargeProperty1>
<LargeProperty2>
<Key>2016-02-01_14\6f940655-a6df-45bb-ae41-bb16ef3821d0</Key>
<HasValue>true</HasValue>
</LargeProperty2>...
```

in v6
```
<?xml version="1.0"?><MessageToSend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://tempuri.net/Snippets6.Headers.Writers"><LargeProperty1><Key>2016-02-01_14\61b3e30f-f0e4-49e9-a509-572152f1f1d2</Key><HasValue>true</HasValue></LargeProperty1><LargeProperty2><Key>2016-02-01_14\4cbcdbe1-8f05-4e68-a2af-0316b63dab0f</Key><HasValue>true</HasValue></LargeProperty2></MessageToSend>
```

from running the v5 and v6 XML sample
![xml](https://cloud.githubusercontent.com/assets/122666/12878452/4a6246b0-ce79-11e5-8903-d90202168d4d.png)

**Comment by andreasohlund** [comment]
@hmemcpy smells like the xdocument change you made?

**Comment by hmemcpy** [comment]
@andreasohlund possible, I don't do any formatting of the XDocument.
But this isn't a wire compat change? In fact, I'd argue this is the more correct output, no arbitrary newlines.

**Comment by danielmarbach** [comment]
@hmemcpy https://github.com/Particular/NServiceBus/commit/853aa43f3dc9eadaa93a0522dffa942be9b81d0a

**Comment by hmemcpy** [comment]
The newline here (https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Serializers/XML/XmlSerialization.cs#L64) was to force nested empty elements to expand properly, if I recall correctly. This has no effect on the overall formatting. In fact, the old printing was not really "pretty", it simply forced `\n` on the closing elements, so it's quite flat actually.

Other than perhaps changing that single `\n\` into `Environment.NewLine`, I'd `wontfix` this, since it doesn't break wire compat (and arguably even more efficient on the wire)

**Comment by danielmarbach** [comment]
I agree with @hmemcpy

**Comment by SimonCropp** [comment]
No problem with a wont fix. I just wanted to ensure it was on purpose.

As long as no one cares that it is slightly harder to debug?

**Comment by hmemcpy** [comment]
@SimonCropp you can always use the XML debug visualizer to pretty print it. Also, it looks like there's a "pretty formatting" checkbox in QueueExplorer. Let's see if anyone complaints :)

**Comment by SimonCropp** [comment]
Ok
