### ISSUE TITLE
Question: FeatureState.Active vs FeatureState.Enabled - Do we need both?

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3446]
Currently in the [Features/SettingsExtensions.cs](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/SettingsExtentions.cs) class, we have 2 methods:  
1. [IsFeatureActive](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/SettingsExtentions.cs#L35)
2. [IsFeatureEnabled](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/SettingsExtentions.cs#L43)

These are confusing. What is Enabled mean, What does Active mean? 
Which one should I use if I want to check if a feature is enabled by the user?

**Comment by danielmarbach** [comment]
@indualagarsamy I see where this is coming from. Internally features go through the following lifecycle:

* Disabled
* Enabled
* Active
* Deactivated

Only features that are enabled or enabled by default eventually get activated by the `FeatureActivator`. Looking at https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/FeatureActivator.cs#L57 we can say that all enabled features will get activated. Is it fair to say that for end-users potentially only the active state is relevant? Since when you do `EnableFeature` it will get activated?

**Comment by andreasohlund** [comment]
Not sure this is correct, an enabled feature can during activation be "deactivated"/"not activated" due to not satisfied dependencies

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Features/FeatureActivator.cs#L198

In short: Enable != activated?

**Comment by danielmarbach** [comment]
@andreasohlund Thanks for clarifying. I missed that line!

**Comment by danielmarbach** [comment]
@andreasohlund changed my comment. Thanks for pointing out

**Comment by danielmarbach** [comment]
@indualagarsamy and I had a quick conversation about the word enabled and active. They are pretty similar for an end-user. Would it make sense to rename the states of features to something like

* Disabled
* Enabled
* Running
* NotRunning

@andreasohlund thoughts?

**Comment by andreasohlund** [comment]
I like it, not sure its important enough for v6 though?

**Comment by indualagarsamy** [comment]
@andreasohlund agreed. The only reason I raised it is because it was confusing to me.

**Comment by andreasohlund** [comment]
Issue raised to track the rename https://github.com/Particular/NServiceBus/issues/4269
