### ISSUE TITLE
Processed_At header is incorrectly set

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus#3450]
While running my sample application (https://github.com/WojcikMike/PubSubSample) and validating results in ServiceInsight i noticed that in headers you can find following value:
"processed_at":"0001-01-01T00:00:00Z",
For every message. 

I verified and there is a test to ensure that ProcessingEnded is set however it doesn't verify to what value. And it is in fact the date above.
https://github.com/Particular/NServiceBus/blob/84165535ba4cf841b2f5b5352f2a3f5e57c3fc0f/src/NServiceBus.AcceptanceTests/Performance/When_message_is_audited.cs#l23

I believe the issue is that below code:
https://github.com/Particular/NServiceBus/blob/bfd6350948aefc37cc30b2eb6869f4f68ff73051/src/NServiceBus.Core/Performance/AuditProcessingStatisticsBehavior.cs#L16-L17

Is executed before the finally block is exectured:
https://github.com/Particular/NServiceBus/blob/b14903ab4955cdd130a27df12d3c686ddc41490f/src/NServiceBus.Core/Performance/Statistics/ProcessingStatisticsBehavior.cs#L24-L31

**Comment by danielmarbach** [comment]
@WojcikMike Are you working on this? If yes can you assign yourself?

**Comment by WojcikMike** [comment]
@danielmarbach I am not working on it. I just created it, but I was busy for the last 2 days. I might have time tomorrow or the day after so if no one will take it, than I can pick it up. If someone else have the availability I don't want to block it.

However from the top of my head I am not sure how to fix it.

**Comment by johnsimons** [comment]
I had a look at solving this issue and it is a bit more complicated then it first looks.

The problem is the following:
1. `ProcessingStatisticsBehavior : Behavior<IIncomingPhysicalMessageContext>` executes first, this initializes the start timestamp
1. We then start a child pipeline that does the auditing
1. as part of the child pipeline, we write the header for the audit message, `AuditProcessingStatisticsBehavior : Behavior<IAuditContext>`
1. Finally we finish `ProcessingStatisticsBehavior : Behavior<IIncomingPhysicalMessageContext>` and write the end timestamp

So as u can see, the end timestamp is written after the audit message has already been created and quite possible dispatched (if no transaction are on).
I am sorry, but at this stage I am not too sure how to proceed with fixing this one, @Particular/nservicebus-maintainers any tips ?

**Comment by danielmarbach** [comment]
@johnsimons The only way I see we can do it is by adding the end processing statistics to `InvokeAuditPipelineBehavior` after we executed the `next` delegate

**Comment by danielmarbach** [comment]
@johnsimons What about this approach?

https://github.com/Particular/NServiceBus/pull/3482
