### ISSUE TITLE
Timeouts exceptions

### ISSUE THREAD

**Issue by weralabaj** [Particular/NServiceBus#3469]
When running version 6 samples with Timeouts, after dispatching a message I get concurrency exception (ERROR NServiceBus.MoveFaultsToErrorQueueBehavior Moving message 'message_id' to the error queue because processing failed due to an exception: exception_type_and_message). => That is most likely core issue.

The user is very likely to experience similar behavior, as what I have in samples is not an extreme case.

To reproduce use the latest version (i.e. version 3 of the SQL Server transport) of samples SQLServer + NHibernate + Outbox (https://github.com/Particular/docs.particular.net/pull/1162) or SQLServer + NHibernate + EF + Outbox (https://github.com/Particular/docs.particular.net/pull/1169).

When Outbox is enabled the timeout message is never delivered. When Outbox is disabled the exception is shown but timeout is delivered. => That part is probably caused by NHibernate bug (potential fix https://github.com/Particular/NServiceBus.NHibernate/pull/154).

Note: the issue was reproduced using SQL Server samples, but is not transport-specific. According to my understanding it's caused by the current TimeoutPoller implementation.

After this one is done we should double-check the samples.

**Comment by danielmarbach** [comment]
@weralabaj would it make sense to open the issue in the SqlServer Transport repo?

**Comment by weralabaj** [comment]
@danielmarbach I think this is the core issue, isn't it? @SzymonPobiega?

**Comment by danielmarbach** [comment]
Sorry that wasn't clear to me based on your description

**Comment by weralabaj** [comment]
Good point, I added clarification.

**Comment by weralabaj** [comment]
@danielmarbach on the other hand - I'm not 100% sure that I'm not doing something wrong in those samples, so might be my fault:/

**Comment by timbussmann** [comment]
I'll have a look at this

**Comment by timbussmann** [comment]
The exception you see is indeed related to the TimeoutPoller, but it's the control message which is handled on the TimeoutDispatcherBehavior which throws the exception. This is indeed the expected behavior because the TimeoutPoller is currently known to query the storage twice immediately and nhibernate TimeoutPersistence had a bug related to that. Not sure if that is already fixed. But in case of "duplicate timeouts" the behavior throws an exception which should cause a retry which then usually succeeds. The sample had retries disabled which caused the message to be forwarded to the errorquueue.

The retry handling of timeout messages has been refactored and you should update to the latest core unstable version. This will use the new mechanism which will use retries independent of the user-config for timeouts. The new mechanism will also no longer send duplicate timeouts when using DTC (which it did before because of the known retries DTC behavior). So the DTC scenario should work.

for the Outbox scenario, this looks weird. Could it be that the satellite pipelines used for timeouts use the same Outbox storage identifier and therefore the dispatched timeout is discarded because the same messageid is reused e.g. here https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs#L34 ?

Also with the sample I noticed that after a while sending Orders from the Sender endpoint fails and tears down the endpoint. Seems like an issue with SQL transport.

**Comment by andreasohlund** [comment]
>The retry handling of timeout messages has been refactored and you should update to the latest core unstable version. This will use the new mechanism which will use retries independent of the user-config for timeouts.

:+1:  cc @MarcinHoppe

**Comment by danielmarbach** [comment]
Who is taking this over? @timbussmann asked for help since he is away until next Tuesday.

**Comment by weralabaj** [comment]
@danielmarbach I'm looking into Nhibernate/SqlServer part of the problem with @SzymonPobiega. But I'm away tomorrow and on Friday :/

**Comment by danielmarbach** [comment]
I mean it is important but not urgent. As long as we make sure it it tracked and analyzed at some point. I unassigned @timbussmann so that other people could pick it up

**Comment by weralabaj** [comment]
Ok, i'll make sure it's not forgotten ;)

**Comment by weralabaj** [comment]
@timbussmann by latest core which version do you mean exactly?

**Comment by MarcinHoppe** [comment]
@weralabaj 6.0.0-unstable1554 should be good.

**Comment by weralabaj** [comment]
I've verified today with Core unstable1568 , SqlTransport unstable0104 and NHibernate pull 154. I'm getting the same exceptions, although I didn't observe the shutdown behaviour that Tim mentioned above.

**Comment by timbussmann** [comment]
@weralabaj I think when switching off outbox you'll still see an exception once which is the concurrency exception which is "working as intended", but we probably shouldn't log it on that level.

Since I'm back again I can pick up investigations soon if none else is working on it.

**Comment by weralabaj** [comment]
@timbussmann @tmasternak has 3 issues to raise, he found out the root causes.
Tomasz, can you include links here?

**Comment by tmasternak** [comment]
The issues are: https://github.com/Particular/NServiceBus/issues/3499, https://github.com/Particular/NServiceBus.NHibernate/issues/161 https://github.com/Particular/NServiceBus/issues/3500. The last one is not directly connected to sample but has been discovered while doing investigation on it.
