### ISSUE TITLE
Make ExpiredTimeoutsPoller intelligently select NextTimeToQuery

### ISSUE THREAD

**Issue by colin-higgins** [Particular/NServiceBus#3545]
In each of the downstream repositories we are duplicating logic to intelligently choose the next time to query if there are timeouts within the next polling window.

If core pulled in a small window of future timeouts, we could eliminate the duplication and choose when to query next in a consistent manner.

https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs#L87

For example, if we pulled back all past timeouts, and also timeouts 10 minutes into the future, we could hold those timeouts in memory and dispatch them at a more accurate time. If there are no future timeouts in a given query, we set the NextTimeToQuery to some very distant date until a new timeout is added.

Once we have reached the end of the in-memory timeouts, we can rely on the add method to tell us when to query next.

cc / @DavidBoike

**Comment by danielmarbach** [comment]
Can you elaborate more your idea?

**Comment by andreasohlund** [comment]
@SzymonPobiega @tmasternak did you raise an issue for the "future of the TM"?

Pretty sure this makes this one moot?

**Comment by tmasternak** [comment]
@andreasohlund https://github.com/Particular/NServiceBus/issues/3532

**Comment by andreasohlund** [comment]
@colin-higgins please review #3532 and reopen this one if needed

**Comment by DavidBoike** [comment]
I'm going to reopen this. #3532 is very fluffy and really doesn't say much aside from we should be able to change the implementation (really focused on the nuts and bolts like features and satellites) after V6.

This issue is about the query mechanism specifically.

In V5 there's a difference between WHEN we query and WHAT we query.

For query parameters (WHAT we query, the date ranges passed to persistence), we start with a date 10 years in the past and then on each subsequent query, we use the date of the latest (highest date) timeout we've seen. Assumption is made we have everything before that already! It's also not obvious to the persister that we're going to dispatch everything you return, so you better only return timeouts that are already due. You can't "work ahead."

For WHEN to run the query:

1. The first query runs on startup.
2. The persister is supposed to return when the next best time to query would be. Generally this is _supposed to be_ the date of the next timeout that is NOT yet due.
  * Azure Storage Persistence isn't doing this right, it's going every second.
3. We wait until that date to query.
4. If the current endpoint instance pushes a new timeout that is before the next query, we reset it to the earlier date.

If timeouts are spaced quickly, this can result in a LOT of queries, which are the most inefficient aspect of timeout management. If you have an unchanging set of timeouts spaced every few seconds, you'll be querying every few seconds. There's no way to pull in the next 30 minutes worth of timeouts, keep them in memory, and then use an in-memory timer to dispatch them at the right moment without requiring a query.

This is especially problematic for Azure Table Storage, where we are basically forced into a partition key of YYYYMMDDHH. A query between two arbitrary times in ATS is really hard and expensive. But you could return the entire hour's worth of data and not require another query until the top of the hour.

**Comment by timbussmann** [comment]
Not sure what your goal is with reopening this issue @DavidBoike? We decided that it is way too much effort to find a "common abstraction" over all timeout persistence options within v6. To not block potential optimization completely we want to ensure that it is possible to fully replace the implementation with something more optimized (e.g. Azure Table Storage). This also allows us to release better solutions as minor releases. From the discussions we had so far, I think we end up with multiple entirely different timeout storage mechanisms instead of some generic architecture which needs to be followed on each persistence option.

**Comment by danielmarbach** [comment]
I agree with @timbussmann Let's close this!
