### ISSUE TITLE
Check System Failover and do not pick any messages

### ISSUE THREAD

**Issue by PialiRoy** [Particular/NServiceBus#3569]
Is there any way that if the system is in failover mode the handler should not pick any of the messages from the queue,
and when it goes to normal mode it should pick and process.

**Comment by danielmarbach** [comment]
@PialiRoy 

Can you explain what you consider failover mode and how you'd detect that an endpoint is in such a failover mode?

**Comment by PialiRoy** [comment]
We have a service which checks the system is in failover mode,so the handler is aware that the system is in failover but still the messages are getting picked up , so can you suggest how to stop messages in Nservicebus to be picked up, if system is in failover mode.

**Comment by danielmarbach** [comment]
@PialiRoy Based on what criteria do you know you have to "pause" and what would be the trigger to restart again?

In the meantime when the endpoint is paused would other systems still be sending messages to the input queue of that endpoint? If the answer is yes how would you deal with SLA? Since the sending endpoint has no knowledge that the endpoint is paused this could eventually lead to huge amount of messages pilling up on the input queue.

**Comment by jeremy001181** [comment]
Hi Daniel 

Yes, the other systems will still be sending message to the queue and the queue will get filled up if no listener picking up

Maybe that the word "pause" isn't quite right. Following is a background of our listener.

Our listener calls a third party api as part of process after receiving a message from queue. The third party api can be down and not available for certain period e.g 15 min. If that happens, at the moment our listener will be continue picking message from queue and try to call the 3rd party api, which it will then failed because the Api is down then the message gets moved to dead letter queue.

And we don't want that, what we are looking for is a solution that messages won't get "lost"and will get processed once the dependency is back up.

What is the best practice in your opinion? Should listener carry on picking messages, and it checks if api is backup or not , if not then do nothing?

**Comment by danielmarbach** [comment]
@jeremy001181 We usually recommend for such integration scenarios to have a dedicated endpoint which calls such a third party API. So for example if you know that your API is sometimes down for roughly 15 min like you said you can tweak the [First Level Retries ](http://docs.particular.net/nservicebus/errors/automatic-retries#first-level-retries) and [Second Level Retries](http://docs.particular.net/nservicebus/errors/automatic-retries#second-level-retries) Settings accordingly. So in your case I would set FLR to maybe one and implement a [custom SLR policy](http://docs.particular.net/nservicebus/errors/automatic-retries#second-level-retries-custom-retry-policy) which does an exponential backoff, or even simpler just configure the SLR period to be greater than 15 min.

**Comment by jeremy001181** [comment]
Thanks for reply

1. For dedicated endpoint approach, if I understand correctly, do you mean following?

My listener -> a dedicated endpoint -> 3rd party Api, if so, lets say the endpoint returns a custom error code 503 when api is down, how my listener should handle it? Mark it completed? Or throw an exception? Retry?

2. Retry approach, 15mins is a guess value, what if the api is down for 16mins , do I lost the message that has already second retired?

**Comment by danielmarbach** [comment]
@jeremy001181 

![untitled diagram 2](https://cloud.githubusercontent.com/assets/174258/14421274/fcf10dba-ffd0-11e5-8189-f53899eb49e5.png)

When the API is down the 3rd integration handler throws. Retry kicks in.

If your API is down longer than your average it will retry until the number of retries is exceeded. When the number of retries is exceeded the message will be moved into the error queue and can be retried manually with ServicePulse for example

**Comment by timbussmann** [comment]
@jeremy001181 it looks like this conversation did not really continue so we're closing this issue for now. If you still haven't found a working solution to your scenario feel free to continue the conversation and then we can reopen this issue.
