### ISSUE TITLE
Unable to replace registered behaviors

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#3574]
Based on @timbussmann's comment in https://github.com/Particular/NServiceBus/issues/3563:

>You can't replace a behavior which is registered in a Feature from `INeedInitialization` because initialization is executed before the features, therefore your custom registration is overwritten again.

>The even bigger problem is, even with a Feature there is currently no way to tell that your feature runs AFTER the StoreFaultsInErrorQueue behavior. Which means you probably still end up running before the behavior setup you want to replace. Since StoreFaultsInErrorQueue there seems to be no way to replace the behavior correctly. I tested it with making the StoreFaultsInErrorQueue feature public and it worked with a custom feature using DependsOn<StoreFaultsInErrorQueue>().

Related Issue: https://github.com/Particular/NServiceBus/issues/3563

**Comment by indualagarsamy** [comment]
@johnsimons @SimonCropp @boblangley @petersgiles - based on our discussion in Engg, I've raised this as a separate issue.

**Comment by indualagarsamy** [comment]
@timbussmann - If the replacing behavior is a problem only for the `MoveFaultsToErrorQueue` behavior, please close this issue.

**Comment by timbussmann** [comment]
replacing behaviors doesn't work for all behaviors which are registered within an **internal** Feature because there is currently no way to ensure that the behavior to be replaced is registered before the behavior which should replace it.

This seems to be a bug the pipeline configuration since the class seems to be designed to track replacements to not rely on order of registration/replacements. I'll have a closer look.

With a quick glance at current develop, these behaviors can't be replaced:
* AttachCausationHeadersBehavior
* AttachCorrelationIdBehavior
* RouteDeferredMessageToTimeoutManagerBehavior
* AuditHostInformationBehavior
* FaultHostInformationBehavior
* AddHostInfoHeadersBehavior
* AuditInvalidLicenseBehavior
* LogErrorOnInvalidLicenseBehavior
* DetermineMessageDurabilityBehavior
* CriticalTimeBehavior
* ReceivePerformanceDiagnosticsBehavior
* ProcessingStatisticsBehavior
* AuditProcessingStatisticsBehavior
* **TransportReceiveToPhysicalMessageProcessingConnector**
* MutateIncomingTransportMessageBehavior
* MutateIncomingMessageBehavior
* InvokeHandlerTerminator
* MutateOutgoingMessageBehavior
* MutateOutgoingTransportMessageBehavior
* AttachSenderRelatedInfoOnMessageBehavior
* ForceImmediateDispatchForOperationsInSuppressedScopeBehavior
* OutgoingPhysicalToRoutingConnector
* RoutingToDispatchConnector
* BatchToDispatchConnector
* ImmediateDispatchTerminator
* **MoveFaultsToErrorQueueBehavior**
* ProcessedMessageCounterBehavior
* UnicastSendRouterConnector
* UnicastReplyRouterConnector
* UnicastPublishRouterConnector
* MulticastPublishRouterBehavior
* ApplyReplyToAddressBehavior
* MessageDrivenSubscribeTerminator
* MessageDrivenUnsubscribeTerminator
* NativeSubscribeTerminator
* NativeUnsubscribeTerminator
* PopulateAutoCorrelationHeadersForRepliesBehavior
* **DeserializeLogicalMessagesConnector**
* **SerializeMessageConnector**
* ApplyStaticHeadersBehavior
* TransactionScopeUnitOfWorkBehavior

**Comment by timbussmann** [comment]
Confirmed this bug with @danielmarbach. This is acutally not an issue with the order or replacements as I initially assumed, but it's a bug with the replacement of steps where the behavior factory isn't correctly overwritten.

on the PipelineModelBuilder we do only replace the `BehaviorType` of a registered step (https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/PipelineModelBuilder.cs#L58). But when we build the pipeline we don't use that type to resolve the behavior in case the behavior was registered with a factory method (https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/RegisterStep.cs#L180). The bug is that we currently don't replace the factory method.

The straightforward fix would be to also make the factoryMethod (https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Pipeline/RegisterStep.cs#L197) on RegisterStep replaceable.
