### ISSUE TITLE
Consider more fluent style routing configuration

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3625]
Based on the saga mapping API, consider suplementing
```
config.UnicastRouting().RouteToEndpoint(typeof(MyCommand), "MyEndpoint");
```
with something like
```
config.UnicastRouting().Route<MyCommand>().To("MyEndpoint");
```

This idea came up when reviewing the new V6 routing APIs.

### Pros

 * It is similar to saga mapping APIs
 * It reads well
 * It requires less typing

### Cons

 * It can't be used when the list of routes comes from outside so it is only a syntactic sugar on top of the "normal" API call
 * It is not prone to errors when somebody forgets the `.To` part like this:

```
config.UnicastRouting().Route<MyCommand>();
```

best thing we could do is throw when starting saying one of the routes is not defined

**Comment by danielmarbach** [comment]
If I understand correctly this is the outcome from the routing TF discussion. Since this is changing the API of routing yet again would it make sense to flesh out the description about the why and then ping the v6 launch TF?

**Comment by SzymonPobiega** [comment]
@danielmarbach this was just an idea. I'll add more description today. This is a syntactic sugar and can be added in 6.X

**Comment by danielmarbach** [comment]
Sorry then my context was wrong. I saw this mentioned as an outcome of the TF meeting so I figured you'd like to do it now

**Comment by SzymonPobiega** [comment]
@danielmarbach this was a suggestion. Weather we should do it now or not, I don't know. Given the fact that we have a lot of stuff that *needs* to be done, I didn't yet feel the need to ping the v6 launch TF. I wanted to document it somewhere and let people chime in.

**Comment by timbussmann** [comment]
Based on the conversations and insights we had on the routing tf I think we discussed these options already and concluded that we don't want a routing api accepting a generic parameter because it doesn't align with the namespace/assembly based routing APIs. For the fluent parts we constantly received feedback that we don't want to introduce more fluent APIs back to the configuration API.

Therefore I'm closing this. Feel free to reopen if you disagree. /cc @SzymonPobiega
