### ISSUE TITLE
Load EndpointInstanceMapping from app.config like log4net

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3634]
With log4net you have the following configuration options:

```
[assembly: log4net.Config.XmlConfigurator(ConfigFileExtension  = "log4net", Watch = true)]
log4net.Config.XmlConfigurator.Configure();
log4net.Config.XmlConfigurator.ConfigureAndWatch(new FileInfo("log4net.config"));
```

Having such a similar API to load message mappings would add value IMHO.
## Examples

```
configuration.UnicastRouting().Mapping.Configure();
configuration.UnicastRouting().Mapping.ConfigureAndWatch(filePath);
configuration.UnicastRouting().Mapping.ConfigureAndWatch(configFileExtension:"routes");
```

**Comment by timbussmann** [comment]
@ramonsmits was this refering the EndpointInstanceMappings (the old routing API in v5) or indeed the endpoint instance mapping provided by the MSMQ transport (which can already be configured with a custom filepath)? It feels like this issue is no longer applicable with the new routing API and can be closed instead. Thoughts?

**Comment by andreasohlund** [comment]
I agree with @timbussmann , please reopen if needed @ramonsmits
