### ISSUE TITLE
Replacing connectors

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#3642]
A while ago we had a discussion about ability to replace **any** behavior in the pipeline, including the connectors. As far as I remember the outcome was to continue supporting replacing of anything. While porting one of the samples I discovered that at least following behaviors:
- TransportReceiveToPhysicalMessageProcessingConnector
- RoutingToDispatchConnector
  are not replaceable due to the fact that `PendingTransportOperations` is internal.

**Comment by andreasohlund** [comment]
In general I would suggest that we do not support replacing anything and only allow users to add new behaviors (ie remove `Replace`, `InsertAfter`, `InsertBefore`)

I'd say we don't have to target v6 with this since we can make the internal things public if needed. Do we have any knowledge of a use case that would require replacing a connector?

**Comment by SzymonPobiega** [comment]
@andreasohlund I just want to make sure we are aligned. I know we explicitly did some effort to allow deserializing connector to be replaceable.

**Comment by andreasohlund** [comment]
yes, I now think we should have added a explicit ext. point to plug in new "deserializers" instead

cc @SimonCropp

**Comment by timbussmann** [comment]
I think even internal behaviors are replaceable if you know its "key".

**Comment by SzymonPobiega** [comment]
@timbussmann the problem is not the behavior being internal but a type which it uses and which is also used by other behaviors.

**Comment by timbussmann** [comment]
`PendingTransportOperations` should probably be public. Is that enough to replace the behaviors?

**Comment by SzymonPobiega** [comment]
@timbussmann I think so but I haven't check in-depth because
 * First I wanted to be sure that replacability is our goal
 * I chose a different (I hope better than replacing connectors) way of implementing what I wanted to achieve

**Comment by danielmarbach** [comment]
Based on the controversial conversations we had in the past we agreed that we publicly made the announcement that every behavior on the pipeline is replaceable and we agreed to stick to that. So if `PendingTransportOperations ` is a blocker it needs to be public

**Comment by timbussmann** [comment]
@Particular/platform-dev-squad this seems to be a blocker for v6 since it's required to be able to replace behaviors.

**Comment by andreasohlund** [comment]
Have we ruled out the option to backtrack and only allow behaviors to be replaced?

@SimonCropp remind me of the usecase to replace the deserialize connector?

**Comment by danielmarbach** [comment]
@andreasohlund http://docs.particular.net/samples/pipeline/multi-serializer/

**Comment by andreasohlund** [comment]
The amount of code the user have to understand (read copy & paste) is quite large. 

http://docs.particular.net/samples/pipeline/multi-serializer/#code-walk-through-behaviors-serialization-behavior

I think we and the users would be better off adding a explicit api to allow users to register multiple serializers instead.

Are there other known connectors that we have replacement scenarios for?

**Comment by adamralph** [comment]
> @Particular/platform-dev-squad this seems to be a blocker for v6 since it's required to be able to replace behaviors.

@Particular/tf-v6-launch-plat-dev can make the V6/non-V6 call.

**Comment by danielmarbach** [comment]
@adamralph No need to ping us. We are on this.

**Comment by adamralph** [comment]
@danielmarbach it was in response to https://github.com/Particular/NServiceBus/issues/3642#issuecomment-205207524

**Comment by danielmarbach** [comment]
When we announced the pipeline at NSBCon we made a promise to our users that all behaviors are replaceable in the pipeline. In V6 we introduced additional strongly typed stages into the pipelines which are by themselfes also Behaviors. Replacing behaviors is non trivial. Replacing stage connectors is even more complex as [stated in the documentation](http://docs.particular.net/nservicebus/pipeline/customizing-v6#advanced-concepts). It is unnecessary to step back from that promise for v6. We can make sure that stage connectors are replaceable by making sure the data used by the stage connectors is publicly available. In future versions when we actually see that more and more customers demand to replace existing connectors and cannot deal with copy pasting existing source code when can always introduce explicit extension points. Since the discussion in this issue moved away from the original description we are going to remove the flag here and raise a much more focused issues as originally intended by @SzymonPobiega 

Discussed with @tmasternak @boblangley in the sync call today

**Comment by danielmarbach** [comment]
Issue raised here https://github.com/Particular/NServiceBus/issues/3659

**Comment by andreasohlund** [comment]
The current stance is that we want to backtrack and not support replacement of connectors so I propose we close this?

**Comment by timbussmann** [comment]
closing this as proposed by @andreasohlund a while ago. It also feels like pdev would be the more suitable place to raise this.
