### ISSUE TITLE
TimeoutManager vulnerable to server time changes

### ISSUE THREAD

**Issue by WojcikMike** [Particular/NServiceBus#3703]
We got information from a customer that due to time change on a server (current time was moved back by about 1 min) a timeout was created effectively in the past. In the current codebase we are calling number of times `DateTime.UtcNow` which make our dates vulnerable to Time change. In our repositories we have number of issues that are touching on that issue like:
* https://github.com/Particular/NServiceBus/issues/3500 - bug regarding inserting Timeout in the past due to FLR
* https://github.com/Particular/NServiceBus/issues/3587 - feature request to use time provider in place of DateTime for better testing
* https://github.com/Particular/NServiceBus.NHibernate/issues/164 - solving this issue in a NH persistance
* https://github.com/Particular/NServiceBus/issues/3300#issuecomment-172504474 - issue related to moving windows and @Scooletz sugestion to change it

Overall there are 2 issues in our current implementation:
* Usage of DateTime.UtcNow that makes our pipeline time dependent (so EndProcessing time can be earlier than StartProcessing etc.)
* Usage of moving window while querying for timeouts (get all timeouts from startSlice till now), which is vulnerable to putting timeouts in the past. Some downstream repos are fixing this issue by pulling all timeouts from time to time.

I would like to raise this issue so that we can think about fixing the issue once and for all. 

cc: @timbussmann @Scooletz 

@Particular/nservicebus-maintainers - please have a look and share your comments

**Comment by timbussmann** [comment]
I don't really see how a time provide would eliminate this issue since they are usually designed for testing purposes and not for gracefully handling system time changes?

If I remember correctly we had multiple discussions around the timeouts design, especially about better native integration. In that case, we could probably eliminate most usages of the current timeout manager implementation anyway without the need to redesign it.

**Comment by WojcikMike** [comment]
@timbussmann were those discussions documented in any place so that I can refer to from the issue?

**Comment by Scooletz** [comment]
Using another approach for moving the `slice` could help. If we queried for everything older than, that would address any time related issues. This is the Raven's approach, mentioned by @WojcikMike above.
If we could go "native" that would solve this problem for any that has a native support for timeouts. Some components might not have it though.

**Comment by timbussmann** [comment]
@WojcikMike I tried to search for it but wasn't able to find it. Maybe @mauroservienti remembers?

> If we could go "native" that would solve this problem for any that has a native support for timeouts. Some components might not have it though.

Supporting native implementations should improve the situation already. That seems to be the way to go anyway and I'm not sure how much should "redesign" the existing solution until then.

**Comment by mauroservienti** [comment]
I don't know what are we talking about here :smile: What should I remember?

**Comment by Scooletz** [comment]
@timbussmann I'd say that the problem of time sync can reoccur anytime. There are people not running `NTP`, just syncing clocks from time to time and this may hit us again. Again, even if we want to go the native path, we need to ensure that every component can support it.

**Comment by timbussmann** [comment]
Would a solution similar to the nhibernate fix work but instead of just using "DateTime.Min till now" as the "query range" use a "DateTime.Min  till Now.Subtract(TimeSpan.FromMinutes(5/10/...)"? this would further reduce the risk of duplicates and find all leftover messages?

**Comment by andreasohlund** [comment]
What's the verdict on this one?

**Comment by timbussmann** [comment]
Afaik both NHibernate and RavenDB will have mechanisms to "cleanup" leftovers outside of the endpoint start logic with the v6.0 release, so that should fix the biggest issue with the `DateTime.UtcNow` usage I think? I think we can close this?

**Comment by danielmarbach** [comment]
The issue description contains to points mentioned:

- Usage of DateTime.UtcNow that makes our pipeline time dependent (so EndProcessing time can be earlier than StartProcessing etc.)

This seems to be a separate issue. I'll raise it for you @WojcikMike 

- Usage of moving window while querying for timeouts (get all timeouts from startSlice till now), which is vulnerable to putting timeouts in the past. Some downstream repos are fixing this issue by pulling all timeouts from time to time.

Talked to @timbussmann. Not sure if we can address this with the current interface defined for the timeout manager. The only way which would bring us closer to not needing to rely on server time would be that the persister needs to checkmark timeouts while processing which opens a pandora box of other issues with transactions. Since we are trying to address native timeouts in the transports I'll close this.

**Comment by danielmarbach** [comment]
Here is the original issues raised by @SimonCropp 

https://github.com/Particular/NServiceBus/issues/3699

**Comment by WojcikMike** [comment]
Thanks @danielmarbach
