### ISSUE TITLE
Automatic sanity-checking of ConfigureHowToFindSaga - IHandleMessages consistency

### ISSUE THREAD

**Issue by dsaf** [Particular/NServiceBus#3704]
It would be nice to have something like AutoMapper's `Mapper.AssertConfigurationIsValid()`.
It's so easy to forget about configuration after implementing an `IHandleMessages` interface.

Understandably there is a limitation to what it can do, but simple presence check is already valuable.
I am probably going to implement this myself, but it will force me to introduce a custom base class deriving from `Saga` since my attempts at reflection were limited by dealing with generics (e.g. `ConfigureMapping<,>(...)` method).

A Roslyn analyzer would be nice to have but a simple invokable method would do as well. Thank you.

**Comment by timbussmann** [comment]
@dsaf thanks for the suggestion, I like that that idea :+1: 

I could see multiple approaches to improve the current situation:
* Roslyn Analyzer
* Provide something like `AssertSagaMessagesAreMapped` in the `NServiceBus.Testing` package
* Provide something like `AssertSagaMessagesAreMapped` in the `NServiceBus` core package

Personally I'd prefer the first two approaches.

**Comment by dsaf** [comment]
I managed to implement something using reflection. This is when I realised that I don't know the precise rules: #3715.

**Comment by timbussmann** [comment]
This should be solved by the v6 saga mapping checks I think? Thoughts @DavidBoike ?

**Comment by DavidBoike** [comment]
@timbussmann Not quite, at least, not for all IHandleMessages.

The Saga infrastructure in NServiceBus 6 and onwards will check that there is a mapping for every message marked as IAmStartedByMessages<T>, but can't do so for all IHandleMessages<T> because a mapping may not be required.

Example: A request response saga, started by MessageA, sends DoSomething to an external endpoint and expects something in response, like a DoSomethingResponse, or maybe a SomethingHappened event. That message could never start the saga, so it would be marked as a IHandleMessages<T>. The external handler would see the SagaId in a headers of the DoSomething message, and know that it came from a saga, and reflect that header back when it sent the response message. The saga would use that auto-correlation to lookup the saga by its SagaId rather than a message mapping.

I'm 100% positive that happens on a context.Reply(), not sure if that is also bounced back if you context.Publish() while handling a Saga-originated message.

**Comment by andreasohlund** [comment]
>Based on that comment, it also seems that a AssertConfigurationIsValid would be basically impossible to implement without larger knowledge of the system?

Based on this , should we close this?

**Comment by DavidBoike** [comment]
The saga analyzers to be released in NServiceBus 7.7 will include multiple analyzers around the ConfigureHowToFindSaga method. It will require there to be a mapping for an `IAmStartedByMessages<T>` and it will actively tell you you don't need one for `IHandleTimeouts<T>`. It will also include a fixer to implement a missing mapping for an IAmStartedByMessages<T> for you. In fact, if you already have your correlation id set, and a property on the message type matches the same property name, it will just fill that in for you.

Unfortunately, as described above, there's no way to assert anything about an `IHandleMessages<T>` without larger knowledge of the system.

Some of the analyzers will start in 7.7 as warnings and be upgraded to errors in NServiceBus 8.

This is the PR targeting master for NServiceBus 8: https://github.com/Particular/NServiceBus/pull/6234
