### ISSUE TITLE
AcceptanceTests Done & Should clauses

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus#3708]
This issue sums up the discussion I had with @timbussmann about responsibilities of `Done` and `Should` clauses in acceptance tests. The main question is if `Should` clause should contain assertions for `Done` conditions. We expressed different points of view:

- **Yes** because it's `Should` responsibilities to gather all the assertions and provide the conditions for successful test execution.
- **No** because it's already checked in `Done`. If this condition fails, a test will hang and timeout. There's no reason to copy the statement to `Should`.

The PR that has started this discussion was: https://github.com/Particular/NServiceBus/pull/3676

@timbussmann @Particular/nservicebus-maintainers thoughts?

**Comment by timbussmann** [comment]
My standpoint:
* `Done` and `Should` are different responsibilities. Just because something is a condition for the test to finish, doesn't say much about actual assertions we want to make about the executed scenario.
* It's perfectly valid to change the parameters/values in `Done` and `Should` independently
* It's easier to see all assertions in one place
* We use the choosen assertion "framework" for all assertions (`Assert`). This is potentially interesting for reporting.

**Comment by andreasohlund** [comment]
what @timbussmann said
