### ISSUE TITLE
Documentation lacking explicit ConfigureHowToFindSaga vs IAmStartedByMessages explanation

### ISSUE THREAD

**Issue by dsaf** [Particular/NServiceBus#3715]
Reading this page http://docs.particular.net/nservicebus/sagas it is not entirely clear to me whether it is mandatory or completely optional to provide a mapping for the message declared via the ```IAmStartedByMessages``` interface(s). It is possible to arrive at an own understanding, but being more explicit here would save time and inspire additional confidence.

Possible scenarios:

```csharp
public class ExampleSaga : Saga<ExampleSagaData>,
    IAmStartedByMessages<A>,
    IHandleMessages<X>,
    IHandleMessages<Y>
{
    protected override void ConfigureHowToFindSaga(SagaPropertyMapper<ExampleSagaData> mapper)
    {
        //A?
        mapper.ConfigureMapping<X>(m => m.Something).ToSaga(s => s.Something);
        mapper.ConfigureMapping<Y>(m => m.Something).ToSaga(s => s.Something);
    }
```

```csharp
public class ExampleSaga : Saga<ExampleSagaData>,
    IAmStartedByMessages<A>,
    IAmStartedByMessages<B>,
    IHandleMessages<X>,
    IHandleMessages<Y>
{
    protected override void ConfigureHowToFindSaga(SagaPropertyMapper<ExampleSagaData> mapper)
    {
        //A? B? A and B?
        mapper.ConfigureMapping<X>(m => m.Something).ToSaga(s => s.Something);
        mapper.ConfigureMapping<Y>(m => m.Something).ToSaga(s => s.Something);
    }
```

Is it:

1) optional and should not be done;
2) optional but best practice to do;
3) mandatory to do in all circumstances;
4) dependant on scenario.

Additionally, regarding ```IHandleMessages``` documentation states:

> Correlation is needed in order to find existing saga instances based on data on the incoming message.

However it doesn't say what would happen if the correlation is missing by mistake: runtime error, no message delivery, message delivery to every saga instance? The "Sagas Not Found" scenario on the other hand is described quite well.

**Comment by andreasohlund** [comment]
v6 will enforce that all messages starting a saga has a mapping (throw an exception if no mapping is found)

we have this note in the doco 

>In Version 6 and above NServiceBus will enforce that all correlated properties have a non default value when the saga instance is persisted.

But I agree that it isn't that clear.  I tried to reword it here:

https://github.com/Particular/docs.particular.net/pull/1463

For messages that doesn't start the saga mappings are optional since they might come in as a result of a bus.Reply to a message that the saga sent. 

In short: Mappings are optional for messages that doesn't start the saga

>However it doesn't say what would happen if the correlation is missing by mistake: runtime error, no message delivery, message delivery to every saga instance? The "Sagas Not Found" scenario on the other hand is described quite well.

You mean if the incoming message wouldn't have a value?

In that case the message prop would have its `default(t)` value and we wouldn't find the message. In v6 this would throw since we require all correlated properties to have a non default value

I've tried to clarify this in the same pull

https://github.com/Particular/docs.particular.net/pull/1463/commits/ccd2d804b49a52d2db9e043a783437a9dc497e00

Thanks for the awesome feedback!

I'm closing this, lets continue the discussion on the pull mentioned above
