### ISSUE TITLE
Holding on to MessageContext

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus#3743]
What happens if I hold on to a message context beyond the life of the handler and try to use it.

i.e.

```CSharp

IMessageHandlerContext savedContext;

public async Task Handle(MyMessage message, IMessageHandlerContext context)
{
    savedContext = context;
    StartTimer(TimeSpan.FromMinutes(2), SomeMethod);
}

private void SomeMethod()
{
   savedContext.Send(new SomeMessage());
}

```

Should we Dispose the message context when the user code should stop using it and throw if attempting to use it when disposed?

**Comment by danielmarbach** [comment]
On the fence. This pretty much violates all design principles out there. Since we are passing in the context as a method parameter and the handler is a short lived object for the scope of the request it is a terrible idea to start a timer and send a message later.

**Comment by timbussmann** [comment]
I proposed MessageHandlerContext to be disposable already in bangkok but it wasn't received to well :D I still think it could make sense to throw an ObjectDisposedException in case someone stores the object for later use.

but when users would code like the snippet you used, I wouldn't be surprised if they would also dispose a context manually because it implements IDisposable.

Maybe we should add some lifetime checks without implementing IDisposable instead? Tbh I don't know where exactly it would throw in your example or how the exception would look like. Even if the code in the sample throws after two minutes, the exception isn't handled and it could take some time to find the issue?

**Comment by danielmarbach** [comment]
Let's add this as a discussion point to https://github.com/Particular/PlatformDevelopment/issues/819 and close this one, ok?
