### ISSUE TITLE
Fail to prepare saga transaction results in circuit-breaker-arming MSMQ receive failure

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus#3757]
### Steps to reproduce:

* Simple saga started by SomeMessage
* Default message processing concurrency
* MSMQ transport, InMemory persistence
* At endpoint startup, do SendLocal of 10-50 SomeMessage

### Exception

Really should fail message processing and invoke retries / error queue, but instead, the MSMQ Receive circuit breaker becomes armed.

```
2016-05-19 12:37:54.839 WARN  NServiceBus.ReceiveWithNativeTransaction MSMQ receive operation failed
System.Transactions.TransactionAbortedException: The transaction has aborted. ---> System.InvalidOperationException: Cannot store a saga. The saga with id '0ace4427-de27-49dd-8896-a60b00d02a83' already has property 'OrderId'.
   at NServiceBus.InMemorySagaPersister.ValidateUniqueProperties(SagaCorrelationProperty correlationProperty, IContainSagaData saga) in C:\Build\src\NServiceBus.Core\Persistence\InMemory\SagaPersister\InMemorySagaPersister.cs:line 126
   at NServiceBus.InMemorySagaPersister.<>c__DisplayClass3_0.<Save>b__0() in C:\Build\src\NServiceBus.Core\Persistence\InMemory\SagaPersister\InMemorySagaPersister.cs:line 72
   at NServiceBus.InMemoryTransaction.Commit() in C:\Build\src\NServiceBus.Core\Persistence\InMemory\InMemoryTransaction.cs:line 15
   at NServiceBus.InMemoryTransactionalSynchronizedStorageAdapter.EnlistmentNotification.Prepare(PreparingEnlistment preparingEnlistment) in C:\Build\src\NServiceBus.Core\Persistence\InMemory\InMemoryTransactionalSynchronizedStorageAdapter.cs:line 79
   --- End of inner exception stack trace ---
   at System.Transactions.TransactionStatePromotedAborted.PromotedTransactionOutcome(InternalTransaction tx)
   at System.Transactions.CommittableTransaction.Commit()
   at System.Transactions.TransactionScope.InternalDispose()
   at System.Transactions.TransactionScope.Dispose()
   at NServiceBus.ReceiveWithTransactionScope.<ReceiveMessage>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\Msmq\ReceiveWithTransactionScope.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MessagePump.<<InnerProcessMessages>b__6_0>d.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs:line 155

```

### Cause

* [TransactionScope of `ReceiveWithTransactionScope`](https://github.com/Particular/NServiceBus/blob/release-6.0.0/src/NServiceBus.Core/Transports/Msmq/ReceiveWithTransactionScope.cs#L22-L56)
* The transaction used by the InMemory persister fails during prepare, essentially because of a concurrency exception, but this failure causes an exception to occur where the TransactionScope in ReceiveWithTransactionScope is disposed, at the end of the using.
* Exception is marshalled through the await into the InnerProcessMessages method of the MessagePump, where it is handled as a generic Exception, so it logs a warning and arms the receiveCircuitBreaker.

@Particular/nservicebus-maintainers I tried to make an acceptance test for this, but the best I could do was a saga that was sent 20 messages and then was expected to increment a counter in saga data to 20. The only failure mode, unfortunately, is a timeout which is kind of annoying.

I thought it could be a unit test, but ReceiveWithTransactionScope requires two message queues, making that pretty difficult.

**Comment by danielmarbach** [comment]
@DavidBoike 

> Calling this method marks the end of the transaction scope. If the TransactionScope object created the transaction and Complete was called on the scope, the TransactionScope object attempts to commit the transaction when this method is called.
> The use of the C# using construction ensures that this method is called even if an exception occurs. Exceptions that occur after calling this method may not affect the transaction. This method also restores the ambient transaction to it original state. A **TransactionAbortedException** is thrown if the transaction is not actually committed.

https://msdn.microsoft.com/en-us/library/system.transactions.transactionscope.dispose(v=vs.110).aspx

I know how to repro it in a unit test. Assigned to me

**Comment by danielmarbach** [comment]
@DavidBoike Thanks for this good repro. Due to the InMemorySagaPersister simulating DTC like behavior and your investigation we found a deal breaker in Core. Like I've shown above `TransactionScope.Dispose` can throw a `TransactionAbortedException`. Unfortunately, we cannot try catch this exception in the receiver and just blindly ignore it because for NonTransient failures this would lead to infinite retries. NServiceBus v5 doesn't have this problem since retry capability is bundled together with the transport receiver. 

@SzymonPobiega checked NHibernate persistence with SQL Server with and without Snapshot isolation and Oracle, I checked RavenDB persistence.

- NHibernate with SQL Server with and without Snapshot isolation is fine since the concurrency exception is thrown when flushing the session
- NHibernate with Oracle throws on `TransactionScope.Dispose `which then triggers the CB
- RavenDB is fine since it throws in the `SaveChanges `call

Currently affected transports are SqlServer and MSMQ

We need to get back to the drawing board, potential solutions and discussion points

### Try catch TransactionAbortedException
Doesn't work with Oracle, can lead to infinite retries, any other custom persister out there supporting TxScope could lead to infinite retries as well

### Augment the responsibility of the TransportTransaction
Move transport transaction into RetryCapability, manage commit, abort etc. there
Means breaking changes for all transports, hinders usage of using statements

### Implement primitive FLR and error queue handling on transport level 

Copy LRU caching etc. to transport and implement primitive FLR and error queue management on transport level

### Revise whole recoverability and error management as a whole

Like discussed several times move the recoverability parts into the transport as well as error management

I'm sure there are potential other ideas

@Particular/sqlserver-transport-maintainers @Particular/nservicebus-maintainers 

// cc @Particular/azure-service-bus-maintainers @Particular/azure-storage-queues-maintainers

**Comment by danielmarbach** [comment]
@DavidBoike @timbussmann and I have been able to write an acceptance test which fails. He will push it soonish. The trick is simple; we wrote an enlistment which does a `ForceRollback` in the prepare phase and hooks that enlistment into the current transaction as a volatile enlistment.

**Comment by timbussmann** [comment]
@danielmarbach @DavidBoike repro PR: #3761

**Comment by danielmarbach** [comment]
Recording: https://drive.google.com/open?id=0Bxf5pxyNKtQVSDE2MVdpVk5Kd1U

## Summary

@SzymonPobiega will talk to @udidahan first and then we'll update the issue with the outcome

**Comment by SzymonPobiega** [comment]
Talked with @udidahan about this over lunch today:
 * Not doing anything does not sound like a good plan
 * It should probably be possible to somehow invoke the recoverability behaviors from the receiver via an additional callback (e.g. apart from `onMessage`, the message pump would also get `onerror` callbacks). Such thing should probably be doable as part of "make core RC-ready" initiative
 * It makes sense to do minimum required to be able to move the recoverability implementations to the transport as part of subsequent transport releases without the need to release core vNext. The recoverability policy definitions (e.g. number of SLRs) should stay in the core
 * A preliminary TF should form and work on definiting the PoA

**Comment by andreasohlund** [comment]
I suggest we get on a call with @udidahan when he's back from Sydney.

**Comment by andreasohlund** [comment]
Call will be schedule with Udi early next week to agree on the POA

**Comment by andreasohlund** [comment]
Spike showing a potentially better api that we want to move towards. 

https://github.com/Particular/NServiceBus/pull/3780

**Comment by andreasohlund** [comment]
Fixed in the new seam

**Comment by mikeminutillo** [comment]
Removed milestone in discussion with @andreasohlund as it was a pre-release bug that was not present in v5.
