### ISSUE TITLE
Async methods should take a CancellationToken

### ISSUE THREAD

**Issue by ppittle** [Particular/NServiceBus#3765]
**Proposal:**

```
public interface IMessageSession
{    
    Task Send(object message, SendOptions options, CancellationToken cancelToken = default(CancellationToken));    
    Task Send<T>(Action<T> messageConstructor, SendOptions options, CancellationToken cancelToken = default(CancellationToken));
    Task Publish(object message, PublishOptions options, CancellationToken cancelToken = default(CancellationToken));
    Task Publish<T>(Action<T> messageConstructor, PublishOptions publishOptions, CancellationToken cancelToken = default(CancellationToken));
    Task Subscribe(Type eventType, SubscribeOptions options, CancellationToken cancelToken = default(CancellationToken));   
    Task Unsubscribe(Type eventType, UnsubscribeOptions options, CancellationToken cancelToken = default(CancellationToken));
}
```

Async methods should generally be cancel-able via the standard `CancellationToken` method parameter convention.  Specifically, `IMessageSession` methods (`Send`, `Publish`, etc) should all have optional `CancellationToken` method parameters.

After some digging I found that there is some support for this, but it's a bit convoluted by registering the token:

```
var options = new SendOptions();
options.RegisterCancellationToken(cancellationToken);
```

While this technically ticks the box of support cancellation, I have an issue with it because this style doesn't follow the established convention and has negative consequences:
1. Tooling Support - Tools like ReSharper will provide coding hints when there's a `CancellationToken` in scope and you're calling a method with an overload that accepts the token.  This tooling helps to promote discovery and encourage proper practice.
2. Discoverability - It was non-trivial to find the `SendOptions.RegisterCancellationToken` method as this wasn't where I'd expect to pass in a CancellationToken.  I only found it by digging through unit test source in the [NServiceBus.Callbacks](https://github.com/Particular/NServiceBus.Callbacks) project.

**Comment by SeanFeldman** [comment]
Related to https://github.com/Particular/NServiceBus/issues/3726

**Comment by danielmarbach** [comment]
@ppittle Thank you very much for taking the time to send in your feedback.

## NServiceBus.Callbacks
Since we moved callbacks out into a dedicated package and we are providing an extension method to start a Request to the receiver side I think we should take your concerns into consideration. We could provide a more "follows the established standards" approach by removing the RegisterCancellationToken method and provide the cancellation token support directly on the request method. At the time when we wrote the callback package, we considered SendOptions THE extension point for all functionality which is passed into the message session and handler context.

See proposal PR

https://github.com/Particular/NServiceBus.Callbacks/pull/27

It is important to note that RegisterCancellationToken extension is only for the callbacks package and doesn't influence the underlying message session calls.

## NServiceBus

That is a tricky one. Like you highlighted we have two pathways: One is async methods on the handler context which are used in the context of a message receive. The other one is `IMessageSession` so essentially message operations outside the scope of a message receive. To be fair we implicitly put cancellation a bit on the back burner since our primary goal of v6 was to move to async first and foremost and not provide cooperative cancellation as of now. That being said the decision is not final. I'll take back your feedback and update this issue when we reached consensus how far we want to go in v6. Does that sound fair?

**Comment by ppittle** [comment]
@danielmarbach, thanks for the clarification; didn't realize that `RegisterCancellationToken` was exclusive to `NServiceBus.Callbacks`.

Re:  NServiceBus, please post the decision; it's great getting such a perspective into the process at Particular.  And just wanted to throw this out there: I'd rather you add CancellationTokens parameters (even optional) in v6 that were *not* fully plumbed than wait for it to be included v7.  If the interface is there I could at least get my wiring in place and be ready to go when you add full cancellation support in a later (hopefully minor ie v6.1) release.

**Comment by danielmarbach** [comment]
@ppittle I raised another issue to track the outcome

https://github.com/Particular/NServiceBus/issues/3785

**Comment by danielmarbach** [comment]
@ppittle we were just debating this again today in our core maintainer sync and we still have difficulties to actually come up with scenarios where cancellation tokens would make sense because there are all kinds of side effects that could happen depending on the transaction mode. Would you be able to highlight here what your needs are for cancellation token?

**Comment by ppittle** [comment]
@danielmarbach - Sorry for the delay.  I circulated this question internally and have the following pieces of feedback.

### Long Running Handler
  I don't recall off hand the name configuration setting, but NSB has a setting in the EndpointConfiguration that controls how long to "hide" a Message once a Handler picks it up before assuming the Handler has died and the Message should become visible again on the Transport so that another Handler can pick it up.  In this case, it would be helpful if NSB included a CancellationToken in the Handle method that signals that NSB is about to execute the retry-policy and start processing the Message again:

    ```
    Task Handle(object Message, IContext context, CancellationToken token)
    {
         // do something that //could// take a long time 
        
         if (token.IsCancelled)
           // NSB is about to retry the message
            throw new TimeoutException();

        context.Send(new DoTheNextThingMessage());
    } 
    ```

### Cancelling I/O
The crux of this scenario is if an underlying Transport/Persistence Api supports CancellationTokens, then I should be able to pass my own CancellationToken (possibly a union of an external token, such as one that is signaled when an Azure Worker Role is shutting down and the "Handler CancellationToken from the example above) to that Api.  For example Azure Blob Storage, has a method [UploadFromStreamAsync](https://msdn.microsoft.com/en-us/library/azure/dn451612.aspx), that takes in a CancellationToken.  This is what I was considering when I opened this issue.

Another aspect of this is shutting down the outgoing pipeline.  If I know I need my Handler to immediately halt, but it's in the process of running through an outbound pipeline, I probably don't want it to continue.

Not sure if this is going to create difficulty around transactionality,  Say, I'm sending a Message with a large payload that will need to be serialized to persistence, the write to the persistence store is started, but then a Cancellation is signaled before the Message is sent on the transport, should the write to the Persistence store be rolled back?

### Context
Adding a bit of context might help your team to think through this issue in a different light.  In a more "traditional" server environment VMs and the processes they host are generally long lived and are not taken down frequently.  My situation is a bit different; I'll be constantly adjusting the number of running processes to match load and running in a cluster environment (ie Azure Fabric) which will automatically balance (read shutdown and re-start) processes to distribute load throughout the cluster.  So Cancellation support will be very material for my environment.

HTH

**Comment by dbelcham** [comment]
@ppittle With NServiceBus in its current state, adding a CancellationToken to the methods would be nothing more than making the surfice of the API adhere to a convention. Once we have support for cancellation within the processing pipeline then adding the CancellationToken will make sense. Until then we aren't going to be taking any action on this.
