### ISSUE TITLE
Split Acceptance Test into relevant for downstream and core only

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#3789]
Split Acceptance Test into relevant for downstream and core only

**Comment by danielmarbach** [comment]
@Particular/nservicebus-maintainers place holder

// cc @SimonCropp

**Comment by andreasohlund** [comment]
Since we now have transport seam tests we're one step closer to not having to distribute any acceptance test at all. (just the acceptance test FX).

Do we agree that this is the end goal?


What other seams should we provide tests for?

* Serializers
* Persisters

**Comment by MarcinHoppe** [comment]
How are we going to run tests that verify different transport + persister combos? We've been recently bitten by SQL + NHibernate tests not being executed regularly.

**Comment by andreasohlund** [comment]
The trend I see is that the persisters will become more of a transport concern( except sagas)

Subscription storage: 

   Sql=should have a native subscription persister
   Msmq=can keep todays pluggable model
   ASQ = should have a native table storage persister

Timeouts:
   Sql=should have a native TM
   Msmq=can keep todays pluggable model
   ASQ=should have a native table storage TM
   ASB = n/a
   Rabbit= not sure, perhaps similar to MSMQ

Outbox: 
   a feature of its own and it would have its own seam tests

So if there are still combos I'd say the relevant persister/transport would have custom acceptance test for those combos? 

I know this is my pipe dream and it will take a long time to get there

**Comment by MarcinHoppe** [comment]
Custom acceptance tests are OK for testing the additional properties that a given combo can offer to the customer (e.g. exactly-once-delivery w/o the DTC).

My way of looking at it is that NServiceBus offers a set of features that works for all supported combinations of transport and persister. If we let each combo maintainer group to implement their custom acceptance tests instead of relying on a common suite, I'm afraid we're creating a lot of work and risk inconsistencies in test coverage.

Or am I misunderstanding what is being proposed here?

I like the general direction of moving certain storage aspects down to the transport level where possible.

**Comment by timbussmann** [comment]
I think this should be handled by https://github.com/Particular/NServiceBus/issues/4457? I propose to close this

**Comment by dbelcham** [comment]
I agree that #4457 covers this. When that work is done there will be a much cleaner delineation between Core-only tests and downstream tests.
