### ISSUE TITLE
Installers cannot be invoked by NServiceBus.Host

### ISSUE THREAD

**Issue by DavidBoike** [Particular/NServiceBus#3807]
Replaces https://github.com/Particular/NServiceBus.NHibernate/issues/197, originally raised by @janpieterz.

When the Host is installed, in order to invoke installers, it [creates an IStartableEndpoint but does not ever call `Start()`](https://github.com/Particular/NServiceBus.Host/blob/release-7.0.0/src/NServiceBus.Hosting.Windows/GenericHost.cs#L66-L94). 

In V5 this worked because the installers [were invoked](https://github.com/Particular/NServiceBus/blob/5.2.14/src/NServiceBus.Core/Installation/InstallationSupport.cs#L46-L78) from an `IWantToRunWhenConfigurationIsComplete` without requiring the endpoint to be started.

In V6, installers are invoked from the [`StartableEndpoint.Start()`](https://github.com/Particular/NServiceBus/blob/6.0.0-Beta4/src/NServiceBus.Core/StartableEndpoint.cs#L43) method, so they never get invoked by the host.

**Comment by bording** [comment]
Taking a quick look at this, it seems like it would be pretty straightforward to move the `RunInstallers()` code from `StartableEndpoint` to `InitializableEndpoint` so that the installers would run when `Create()` was called instead of `Start()`. If we did this, we could also look at not needing to register the installers in the container, though I suppose there could be installers that are depending on DI?

Alternatively, we could break out the `RunInstallers()` code into a separately callable API, which would let the host manually call that to invoke the installers as needed.

@Particular/nservicebus-maintainers thoughts?

**Comment by timbussmann** [comment]
>  it would be pretty straightforward to move the RunInstallers() code from StartableEndpoint to InitializableEndpoint so that the installers would run when Create() was called instead of Start()

sounds good to me at first glance

**Comment by timbussmann** [comment]
this should be fixed with brandon's PR, should we keep that open until beta5 is out to verify it works on the host?

**Comment by andreasohlund** [comment]
Let's verify this locally on the host and close this?

@DavidBoike can you check if the fix is good?

**Comment by DavidBoike** [comment]
Verified it works with NSB.NHibernate beta 4, Host beta 3, and Core #6.0.0-beta.5+2 build from TeamCity. :+1:
