### ISSUE TITLE
Assembly scanning makes startup very slow

### ISSUE THREAD

**Issue by valeriob** [Particular/NServiceBus#3822]
I'm tring to move from 5 to 6, and i disovered that configuration.AssembliesToScan has been removed, now just the act of scanning the bin directory takes 3s on every startup, and it's added on every dev cycle.

For example in my current project it takes 3.8s to run AssemblyScanner.GetScannableAssemblies the first time (a lot of those assembly will be loaded eventually anyway) and 1s the next times, just to handle a very predictable result : 
2 usefull assemblies found (nservicebus.core and myApplication) and 87 skipped ones.

I do not think that using reflection to load modules is a very good idea, you get poor performances, lack of control, and platform depencency (see dotNet Core, and dotnet native). Do you have in mind to move to a more explicit way to load dependencies and modules ? like using the already present ioc container ?

Thanks,
Valerio

**Comment by timbussmann** [comment]
Hey @valeriob,

A reason for the current v6 API was to prevent configuration mistakes from happening. We made the experience that it's very easy to miss required assemblies when using `AssembliesToScan` (since NServiceBus also uses the assembly scanning to load "plugin" packages) which was one of the reasons to switch to an exclude-only approach.

3.8s is quite a while and that's seems to be something we need to look into more closely. Your suggestion regarding present ioc containers is interesting for certain aspects of the assembly scanning like message handler detection but also not something we want to rely on for internal components (that should probably get split up).

> Do you have in mind to move to a more explicit way to load dependencies and modules

As of now there are no concrete plans on changing the current behavior, but this doesn't mean the API can't change if it turns out to be a blocker for certain goals (e.g. .net core) or a huge inconvenience. Also receiving user feedback like yours helps us a lot to validate/challenge our assumptions and rethink our APIs :+1:

**Comment by valeriob** [comment]
Thanks @timbussmann i think the development experience is very important when using nsb and i really appreciated the speedup we got with version 5 and now 6. 
What i would like to avoid is that the samples and small projects are very lean and fast, but when you use nsb in large projects it slows down the dev experience.
I think for the future would be good to have a powerfull fast advanced api (no reflection, full control etc) and on top of it some magic to help new adopters.

I'll try to test more my scenario and give you feedback.

**Comment by timbussmann** [comment]
>  i think the development experience is very important when using nsb

Fully agree with you :+1: 

> I think for the future would be good to have a powerfull fast advanced api (no reflection, full control etc) 

seems perfectly reasonable from a messages/handlers perspective. But there should be a solution which ensures that it's not possible to accidentally exclude NServiceBus assemblies from loading properly. While the new "exclude-only" approach reduces this risk a lot, it comes with the downsides experienced by you.

thanks again for sharing the upgrade experience from your project with us, looking forward to hear more from you!

**Comment by valeriob** [comment]
After a quick test i can say that restoring the method AssembliesToScan reduces my startup cost by 1.5s

![image](https://cloud.githubusercontent.com/assets/1522516/16007051/96e6d9ba-3170-11e6-9d74-2a9190c23038.png)

**Comment by timbussmann** [comment]
@valeriob what's the difference in startup time between release and debug mode on your project?

**Comment by valeriob** [comment]
i could check it out, but i'm trying to improve dev performances.

**Comment by SimonCropp** [comment]
@valeriob so it is not possible for you to speed up startup by using the exclude API?

**Comment by valeriob** [comment]
Well i do not think it's just for me, every not trivial application will get a hit, i just measured it.
The samples are blazing fast, but in a real application things add up :smile: 
I could get the major benefit just focusing nsb to the assemblies it needs to run, where messages and handlers are, and they are not spread around the whole application.

**Comment by danielmarbach** [comment]
With the exclusion API we have a valuable API allowing to tweak the assembly scanning for better performance. With v6 we also exclude assemblies from scanning when it does not reference NServiceBus by default and no longer scan nested folders by default. I think there is everything in place to tweak it to fast startup if required. 

https://docs.particular.net/nservicebus/hosting/assembly-scanning?version=Core_6

Closing this
