### ISSUE TITLE
single saga timeout message being processed by multiple nodes

### ISSUE THREAD

**Issue by Supercide** [Particular/NServiceBus#3829]
Hi 

We have noticed some strange behaviour where timeout messages are being processed by more then one node. AFAIA a single message should only be processed by one node. 

The offending message has the same message id and identical header details apart from the processed by header. this seems to be happening intermittently and we are still looking into the steps to reproduce. We are currently using NServiceBus 5.2.11 with RabbitMQ and MongoDB. 
Has anyone else experienced this?

**Comment by timbussmann** [comment]
Hey @Supercide,

Thanks for reporting this issue. Due to the nature of the the timeout management implementation, there is a low chance of dispatching a timeout multiple times. This is a trade-off we currently can't avoid on transports which don't support DTC to avoid message loss. Can you give us some insights on how often you are receiving duplicate messages (since this should be very rare)?

Are you running multiple instances of the same endpoint? In these scenarios duplicate timeouts can appear more frequently since the timeout storage is queried concurrently by multiple endpoints (which can lead to multiple dispatches of the timeouts).

**Comment by bording** [comment]
To follow up on @timbussmann's comment, when running multiple instances of a single endpoint, duplicate timeout messages are expected. Each instance is running its own timeout poller, and if they both happen to poll at the same time and there is an expired timeout, then they will both send a copy of the timeout message.

Because of this, we recommend that timeout handlers be idempotent, so that they can handle duplicate messages. One way this can be done is by using the [Outbox ](http://docs.particular.net/nservicebus/outbox/)feature. However, the community MongoDB persistences don't support the Outbox, so that won't be an option in your case.

That being said, there is an issue with the timeout poller that can cause it to retry polling too soon in certain cases, and that can cause unintended duplicates even when running a single instance. See #3833 for more information about that.

**Comment by Supercide** [comment]
Hi @timbussmann and @bording  thanks for the speedy replies, apologies for my slow one.

We are indeed running multiple instances of the same endpoint. The frequency is quite often, we see at least 2-3 a day but these are only for the ones that throws an exception when processed more than once. we do however have a high volume of messages flowing through our system so 2-3 is not that big of a number.

Thanks for your recommendations

**Comment by timbussmann** [comment]
Thanks for the update @Supercide. Glad to hear that the amount of duplicates is a manageable amount. Please also not that there is a know issue with some of the persistence options, including MongoDB which have a minor bug which can cause more duplicates than necessary which most like is what you're experiencing. We are working on this issue and try to get that into the MongoDB persistence too, so keep an eye out for updated versions (also, this issue has already been addressed in v6).

**Comment by jsurana** [comment]
@timbussmann I am using NServicebus Core with File version 7.7.4.0. I am having two instances for one handler . I have retry and delayed mechanism as well. So when any exception occurs, both the instances are retrying. How can I avoid this? I want if any exception occurs, only single instance should retry at a time.

**Comment by timbussmann** [comment]
> So when any exception occurs, both the instances are retrying. 

Are you saying that the message to be retried can be retried on any of the two instances, or that the same message is handled by both endpoints at the same time?

**Comment by jsurana** [comment]
@timbussmann  When exception is occurred for a message, it goes for retry. So both the instances are retrying same message which got failed. I want one instance should pick for retry. Is it possible?

**Comment by mauroservienti** [comment]
@jsurana let's continue the conversation at https://github.com/Particular/NServiceBus/issues/6600
