### ISSUE TITLE
IMessageSession and IEndpointInstance

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#3871]
During beta call with a customer, ran into the question of "how to replace an injected `IBus`".
[Documentation](http://docs.particular.net/nservicebus/upgrades/5to6-moving-away-from-ibus#sending-messages-outside-message-handlers) for consistency shows the following way to obtain `IMessageSession`.

```c#
var endpointInstance = await Endpoint.Start(endpointConfiguration).ConfigureAwait(false);
var messageSession = (IMessageSession)endpointInstance;
```

There is a challenge with this approach, it's not intuitive. Type casting is not what we do throughout our API. Perhaps `IMessageSession` should be provided via a method/property? It will also help in the future with guidance if we need deprecate  `IMessageSession`. That guidance would be more difficult when casting is used. Also, casting is leaking [implementation details](https://github.com/Particular/NServiceBus/blob/626b71b6e5f1ab71b2c68be0d2a7cfa66e22fa6b/src/NServiceBus.Core/IEndpointInstance.cs#L8).

@indualagarsamy mentioned that @andreasohlund had this idea before.

@Particular/nservicebus-maintainers should this be changed/addressed?

**Comment by indualagarsamy** [comment]
I think that @andreasohlund wanted to add a .GetMessageSession() method to the IEndpointInstance class. @andreasohlund can you add more details?

**Comment by bording** [comment]
If we want to present the `IMessageSession` as the thing users should care about, then we definitely need to expose a way to get one from the endpoint instance instead of having `IEndpointInstance` directly implement the interface.

**Comment by indualagarsamy** [comment]
@bording - If you're in a web/self hosting environment and you want to keep the IMessageSession around so you can use it in your UI to send messages, then that's a use case that's going to be needed IMO.

**Comment by bording** [comment]
@indualagarsamy I'm not sure there's anything in what I said that would disagree with your statement?

**Comment by danielmarbach** [comment]
So we are going full circle and go back to what we had a few months ago? I remember that we required to get the session explicitly from the endpoint instance (I even showed it in Dallas) and then there was a lot of pushback from @Particular/docs-maintainers that it is just noise. I don't want to imply we shouldn't do it. I also don't want to give the impression I'm passive aggressive or something. Just stating the fact so that we all agree how history looked like.

**Comment by indualagarsamy** [comment]
@bording - I thought you were looking for a strong case. I wasn't disagreeing with you either. Hope my comment is more clear now. 
When I discussed this originally with @SeanFeldman, personally I didn't see a problem with the cast. After all, IEndpointInstance implements IMessageSession and its basic OO,i.e. Liskov substitution principle, to be able to cast a derived interface to its base counterpart. So, do we want to add stuff late in the game, I am not convinced.

**Comment by bording** [comment]
@indualagarsamy Let me try to clarify what I was trying to point out.

Right now our docs are recommending that we take the `IEndpointInstance` returned from `Endpoint.Start` and then cast that to `IMessageSession` before using it. 

However, `IEndpointInstance` is an `IMessageSession`, so there is no reason to cast it. You can do everything directly from the returned type without the cast. The docs don't make this clear at all.

That means that we have 3 ways you can send messages: `IMessageHandlerContext`,  `IMessageSession`, and  `IEndpointInstance`.

There isn't a good story around why you'd need both `IMessageSession`, and `IEndpointInstance` being entry points into "sending messages outside of a handler."

We either need to clarify `IEndpointInstance` vs `IMessageSession` and remove the casting from that spot in the docs (because as that snippet currently exists, there is no reason to do that), or we should actually stop `IEndpointInstance` from inheriting `IMessageSession` and instead expose a way to get to the message session from the endpoint.

**Comment by timbussmann** [comment]
I think `var messageSession = (IMessageSession)endpointInstance;` is an absolute no-go from an API perspective. Aside from my opinion on how the that code looks like, it's also very hard to version an something like this.

As far as I can remember, we didn't follow the `EndpointInstance.Session` path because of the potential changes introduced by the "batched send" API, which we decided a few weeks ago to exclude from 6.0. So it seems fairly valid to pick this discussion up and I'm all :+1: for a property to expose `IMessageSession`

**Comment by danielmarbach** [comment]
@timbussmann previously the API had `GetSession`. @SimonCropp stood up and argued that we should remove it because it is just noise.

**Comment by timbussmann** [comment]
I'm with @bording suggestions here. I think the casting needs to go, I don't mind whether we just change docs or add a property/method (I'd definitely prefer a `Session` property over a `GetSession` method). Personally, I'd prefer the second option.

**Comment by SeanFeldman** [comment]
Doco maintainers are humans as well. The can be mistaken 😉
Casting is causing confusion. We've spent more time debating it on GH issue that it would probably take to address it.

**Comment by andreasohlund** [comment]
We had at least 2 rounds of calls around exposing the session via property/method on endpoint instance and we've always come to the conclusion "yea we should add it, but not now". I don't see anything new added in this discussion to warrant another round of debate?

I propose we just remove the cast from docs since it's not needed?

**Comment by SimonCropp** [comment]
a tweaked the doco about IMessageSession

https://github.com/Particular/docs.particular.net/commit/fe8e8430645e6b78254900ca94aa6e8260694b00

I dont think any more changes need to be made in the core in this area
