### ISSUE TITLE
Make more types public for extendability

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#3908]
This issue is forked based on the discussion in #3821 with this comment https://github.com/Particular/NServiceBus/issues/3821#issuecomment-230432796

We have close our assemblies to expose the bare minimum to operate. Only exposing several interfaces as extension points. I know that this is to expose the least amount of api to prevent breaking changes when applying semver but I think this went too far.

I would like to suggest to open up our assemblies so users are able to extend existing behavior without the need main our internals.

An example is this comment https://github.com/Particular/NServiceBus/issues/3821#issuecomment-230432796 where 

Current implementations types should be open for extension so if we fix anything in our internals that customer don't need to update their cloned copies as is currently required and @yvesgoeleven example is coincidentally a very good example.
Interface `IConvertOutgoingMessagesToBrokeredMessages` is a good start however, the implementation `DefaultBatchedOperationsToBrokeredMessagesConverter` is closed. Why would a user need to clone and maintain that if they need a subtle change like setting a property or adding a header?

On the other hand, you could say that maybe that class has too many responsibilities thus we need more interfaces to split concerns or more interface methods but this that would not solve the 'extend' concern but I would be in favor of applying the Open Close Principle to a lot of our types or give the user more control to reference such types so such types can be wrapped to do pre or post operations.

**Comment by SimonCropp** [comment]
> I would like to suggest to open up our assemblies so users are able to extend existing behavior without the need main our internals. 

Sound like you are talking about the [open close principle](https://en.wikipedia.org/wiki/Open/closed_principle)

Given that approach was recommended in 1988 (well before the existence of package managers) i would recommend caution in putting too much stock in that approach.

**Comment by ramonsmits** [comment]
@SimonCropp I'm sorry, I don't see any what your comment has to do with the concerns I'm raising.

@timbussmann @danielmarbach I see you thumb downed. Can you be a bit more explicit?

**Comment by timbussmann** [comment]
I don't think we should just make internal implementation details public for the sake of extensibility. Having a type public doesn't make the framework more extensible at all but it makes evolving the internal code base much much harder.

If we see reasonable use cases we don't yet support, we should provide specific extensibility points or rethink existing points to accommodate that scenario and not replace arbitrary classes in the framework. That won't end well. I've seen this happening multiple times now, where we have some generic extension points without us really knowing about the potential use cases but making it very hard to apply that to a new design (whereas more specific uses cases could be solved by simple changes). Also the idea of replacing things (e.g. behaviors) has proven to not work well because something is always private and not even code copy&paste works in those scenarios. Changing over-generic APIs is basically impossible because it could always potentially break someone, whereas with specific scenarios, we can document them (as we sometimes do using samples) and make sure we have a proper API for users available.

Since @danielmarbach and me already agree on closing, can other @Particular/nservicebus-maintainers vote on closing the issue or continue on the discussion?

**Comment by ramonsmits** [comment]
@timbussmann Maybe we need more extension points instead of exposing more types but I don't read anything about my concern that a user its currently only option is to fork a repo and keep it up to date. 

Would you state that this is what a user should do, fork a repo? If that is what is deemed the right thing from a maintainers perspective then I'm fine.

Besides that, this approach also makes it hard to work with package managers as @SimonCropp state as now suddenly all downstreams cannot be added anymore as core is custom.

**Comment by danielmarbach** [comment]
Generally you are right @ramonsmits In that case we think it is simpler to let people copy paste code from the repo instead of making a lot more public and hinder ourselves to evolve the framework

**Comment by timbussmann** [comment]
> @timbussmann Maybe we need more extension points instead of exposing more types but I don't read anything about my concern that a user its currently only option is to fork a repo and keep it up to date.

> Would you state that this is what a user should do, fork a repo? If that is what is deemed the right thing from a maintainers perspective then I'm fine.

Before we need more etension points, we need to know what these are intended for, then we can talk about having more extension points. But in general that would be my preferred approach.

Also, I think there are certain points where it just doesn't make sense to bend a framework to your will if it doesn't support a certain feature. I think we're very open against feature requests if we can see the value it generates but also we have to work with priorities and balance tradeoffs. Again, not saying we can't improve on that situation, but just making internal things public, is not going to change anything for the better. Also, making things public essentially bypasses our feature development process.

**Comment by ramonsmits** [comment]
> Also, making things public essentially bypasses our feature development process.

What do you mean by that @timbussmann ?

**Comment by timbussmann** [comment]
> Also, making things public essentially bypasses our feature development process.

if users start to implement valuable features just be replacing public classes all over our codebase, we will completely miss these usage scenarios to tackle this as a real feature which would improve the experience much more.

I'm closing this. From a maintainers perspective we're aligned on the opinion to not make internal classes public but look at specific needs and scenarios instead.
