### ISSUE TITLE
InMemorySagaPersister does respect serialization settings

### ISSUE THREAD

**Issue by tyrotoxin** [Particular/NServiceBus#3994]
InMemorySagaPersister.VersionedSagaEntity.DeepClone uses build-in Newtonsoft Json Serializer and does not respect the endpoint configuration like `config.UseSerialization<NewtonsoftSerializer>();`
This breaks our saga, because we have special serialization logic with attributes, which is not picked up because attributes are defined in the official Newtonsoft.Json assembly, not the NServiceBus.Core.
Example:

    class MyType
    {
        [JsonProperty]
        private readonly string _name;

        [JsonConstructor]
        private MyType() { }
        
        public MyType(string name)
        {
            if (name == null) throw new ArgumentNullException(nameof(name));
            _name =  name;
        }
    }

We use NServiceBus.6.0.0-beta0004

P.S. the NServiceBus.Persistence.AzureStorage.1.0.0-beta0005 does not respect serializer config as well, but it references Newtonsoft.Json v6.0.0.0 instead

**Comment by timbussmann** [comment]
Hey @tyrotoxin 

the `UseSerialization` configuration is only intended to configure the serializer used for message serialization on a transport level, not for persistence. Persistence options will provide a custom API to configure settings (same for AzureStorage).

> This breaks our saga, because we have special serialization logic with attributes

can you elaborate why you're using special serialization logic for saga persistence and how this breaks your sagas?

on a sidenote: InMemoryPersistence is not recommended to use in production

**Comment by tyrotoxin** [comment]
In the sample above the `_name` field does not get serialized and serialized at all, and the private constructor is not called during deserialization (there is another public constructor with arguments which gets called and fails because args are not supplied).

We use in-memory persistence for test purposes only, and here is the thing: changing persistence does not guarantee the use of same serializer what makes testing literally impossible. At the same time we are not going to use Azure Storage Emulator for test purposes, because it's extremely inefficient.
Not using the serializer setting makes sense if a particular persistence type transforms the data into a table-like entity instead of storing a [B]LOB. Is this the case?

**Comment by danielmarbach** [comment]
@tyrotoxin Currently the InMemorySagaPersistence deep clones the saga with using the JSonSerializer to keep an identity object which we can use to associate versions of a given saga data when we do concurrency checks. See [DeepClone](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs#L166). Unfortunately, this will always lead to potential mismatches between a real saga persistence and the InMemory saga persistence. Exposing those settings would not work because we would need to externalize the interned json.net version the core uses which has other potential side effects. Let suppose we would change it to something available in the framework like BinarySerialization (potentially not available in .NET Core) or DataContractSerializer. Now suppose we would use DataContractSerializier and expose the settings over the saga persistence API on the InMemoryExtension points. There would still be a mismatch since you might end up annotating the saga data with Data member attributes just for the sake of InMemoryPersistence which might not have any meaning for another persistence you are using. The only solution I can come up with is to brainstorm on another approach to keep versions associated with saga datas internally.

**Comment by tyrotoxin** [comment]
In our project we use Azure Storage Persistence, so ideally, if Microsoft developed their client (WindowsAzure.Storage package) in a testable way be separating interfaces from actual implementation, we could inject in-memory implementation of the Azure Storage - this would ensure that the same persistence and serialization is used (in NSB terms), but the actual storage is mocked out.

**Comment by timbussmann** [comment]
I'd say the recommendation is to not use serializer specific logic for classes which are persisted. The chances they are compatible across different persistence options is very low and nothing to rely on. Can you switch to a simple DTO with just fields/properties instead of ctor logic and readonly fields instead and move related logic somewhere else?

**Comment by tyrotoxin** [comment]
I'm still not convinced in following such guidelines. Technically, persisted data is no different from a message payload, so why is it possible to configure a serializer for message payload and not possible to configure a serializer for persisted data? Everything mentioned above applies to message payload as well if there is no configurable serializer across all transport types. Can you help me to understand such difference?

**Comment by timbussmann** [comment]
Usually (and so far that holds true for all our supported transports), a transport does not care about the form of it's payload, they are designed to transmit some kind of data and therefore we can allow serializer configuration in the core. Persistence on the other hand may differ, while there are persistence options which don't really care about the data format, others do (e.g. RavenDB), so that's why serialization concern is a persistence specific concern in our current architecture. E.g. so change how a DTO is serialized you may need to use different approaches depending on the persistence you're using (as daniel already described).

I'm not saying it doesn't make sense to allow serializer configuration for certain persistence options, but again, currently this is a persistence concern which is decoupled from the (transport) serializer configuration. It's a valid feature request but I'm still struggling to see the value to gain for the effort to take (again, as daniel already described, if serialiazation is a persistence capability, there is no guaranteed compatibility between different persistence options).

**Comment by ppittle** [comment]
@timbussmann - I agree setting universal serialization options that every persistor should respect/follow might not be appropriate.

Perhaps we should treat this as an enhancement request for In Memory persistence that allows configuring the underlying serializer, preferably using any of the Transport serializer (not sure if the interface exposed by the transport serailizer would be compatible).  

Essentially it would be great to have something like:

```
var config = new EndpointConfiguration("example");

config.UseSerialization<NewtonsoftSerializer>();

config.UsePersistence<InMemoryPersistence>().UseSerializer<NewtonsoftSerializer>();
```

Where `.UseSerializer<NewtonsoftSerializer>()` is the net new.

**Comment by timbussmann** [comment]
@ppittle I could definitely see `config.UsePersistence<InMemoryPersistence>().UseSerializer<NewtonsoftSerializer>();` as a new feature. 
Since we don't recommend using InMemoryPersistence in production environments, this would still mean potential incompatibility between dev and prod environments which makes me wonder what problem is this really going to solve?

**Comment by andreasohlund** [comment]
Would it work to copy paste the existing inmemory persister and create your own "InMemoryJsonSagaPersister" in order to get unstuck? (I can assist if you run into any issues)

**Comment by tyrotoxin** [comment]
Thanks folks for the answers. We are trying to figure out which way we want to go. We can definitely copy-paste existing in-memory persistence code and add reference to Newtosoft.Json NuGet package - this is the easiest solution to support requested feature. However, this will be internal to our company and nobody else will be able to use it if they encounter similar problem - that's why we are asking a lot of questions before making the final decision.

**Comment by danielmarbach** [comment]
Closing as Won't fix. Unfortunately, we don't see this as a priority in the next few months. If you disagree feel free to reopen.
