### ISSUE TITLE
PerformanceMonitorUsersInstaller runs even when not calling EnableInstallers

### ISSUE THREAD

**Issue by distantcam** [Particular/NServiceBus#4036]
How do I turn off PerformanceMonitorUsersInstaller? I'm not calling `EnableInstallers` so it shouldn't be running.

This is in V6.

**Comment by andreasohlund** [comment]
Installers are turned on automatically in if `Debugger.IsAttached`, could that be it?

Wonder if we need a `.DisableInstallers()` that makes sure that they won't run no matter what

**Comment by andreasohlund** [comment]
@distantcam can you confirm?

**Comment by distantcam** [comment]
Yes I can confirm they don't run when not attached to a debugger.

Why are they running when the debugger is attached?

**Comment by andreasohlund** [comment]
>Why are they running when the debugger is attached?

To get "F5" ability for samples :(

This is one thing the "development transport" would address - https://github.com/Particular/NServiceBus/pull/2950 (4:th bullet point)

**Comment by distantcam** [comment]
Don't the samples enable installers anyway? If not they should.

**Comment by andreasohlund** [comment]
They do, but F5 means user code as well and there we have no way to enable it for File=>new project

We do handle this in our bootstrapper though:

https://github.com/Particular/NServiceBus.Bootstrap.WindowsService/blob/develop/src/NServiceBus.Bootstrap.WindowsService/ProgramService.cs#L55

**Comment by distantcam** [comment]
> They do, but F5 means user code as well and there we have no way to enable it for File=>new project

So now they work fine in F5 debug land, but the moment they deploy their system it fails. Works when they try to debug it, fails in production. That's not a good experience.

I can think of two options:

- Disable installers by default, and when the system fails have an error message saying you should enable installers.
- Enable installers by default, and change the config to `DisableInstallers()`.

**Comment by andreasohlund** [comment]
@SimonCropp has some cool plans to pull the install part completely out of the core so that we'll provide script that admins can run at their leisure instead (do we have an issue for this?)

If you combine this with a development transport+ development persistence this becomes a non issue since that will give users starting a nice "F5" experience while making the infra setup needed explicit and visible to the users that have selected a transport and persistence. I think this is the best of both worlds. 

Not sure if its work doing anything in the interim, I rather put the effort into fixing or OPS story once and for all?

**Comment by WilliamBZA** [comment]
I think different behavior between debugger attached and non-debugger attached code paths is a bad idea and we should be actively moving towards removing the behavior differences.

Obvious + repeatable beahvior > F5-ability

**Comment by indualagarsamy** [comment]
@andreasohlund - While I agree with the long term, having this magic happen when debugger is attached is a little confusing. "Thinking I just commented out EnableInstallers, why are the queues being created, is this a bug" type of confusion. I ran into this earlier today. 

How about, in here, we add a INFO or a DEBUG log stating that Installers are being invoked because the debugger is attached and that, the user should either setup proper deployment scripting steps or call EnableInstaller? Thoughts?
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/InitializableEndpoint.cs#L166

**Comment by andreasohlund** [comment]
:+1:

**Comment by andreasohlund** [comment]
@dvdstelt is this fixed in the new external package?

**Comment by andreasohlund** [comment]
Closing this as fixed in v7 since we no longer have any counters in the core
