### ISSUE TITLE
Plans to port to Windows 10 UWP

### ISSUE THREAD

**Issue by pvanroos** [Particular/NServiceBus#4067]
Do you have plans to port to Windows 10 UWP?

**Comment by timbussmann** [comment]
Hi @pvanroos 

As far as I know there are currently no concrete plans in our near-future backlog about Windows UWP but we're looking very closely at .NET Core. What would you use NServiceBus for if it would be available in UWP which isn't currently possible?

**Comment by pvanroos** [comment]
I need a pub/sub solution embedded in a UWP app.  It would be helpful if I could host a hub in my UWP app and then let other apps on the local network subscribe and receive messages.   I could easily achieve this objective using a signalr hub hosted on an Azure API or a Topic in the Azure Service Bus, but that means leaving the local network and go over the Internet.  I was hoping NServiceBus could do this but it doesn't target .NET core yet.

**Comment by timbussmann** [comment]
thanks for giving us some insights into your usage scenario! What kind of transport would you use in your scenario (since MSMQ doesn't seem to be supported by UWP as of now, if I see that correctly)?

As mentioned, UWP support may something which we can directly achieve in case we support .NET Core, so keep an eye out for that :)

**Comment by pvanroos** [comment]
Windows.Networking.Sockets gives me a set of classes to start with but I'd have to write the code to manage the queue, etc.  I don't have the time to build this myself.   UWP offers a lot of opportunity but is still very nascent.  Thanks for the response.
