### ISSUE TITLE
Saga validation does not allow a default value as key in V6

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4123]
I got the following exception when trying to use `0` as the key value:

> System.Exception: We detected that the correlated property 'XXX' on saga 'YYY' does not have a value. 

This is a breaking change compared to V5 where a default value is allowed.

**Comment by andreasohlund** [comment]
We mention this in the doco http://docs.particular.net/nservicebus/sagas/message-correlation

How about we add it to the upgrade guide and there we tell users to use a custom finder if they want to use a default value?

I think the current behavior is correct since a default value is 99/100 times a misstake.

**Comment by ramonsmits** [comment]
Agreed, I don't think there is anything from with it except that it's a breaking change. I looked at the following documents but don't see a list of breaking changes:

- http://docs.particular.net/nservicebus/upgrades/5to6/
- https://github.com/Particular/NServiceBus/releases/tag/untagged-6e66812cfcadba376745

Maybe the overview of breaking changes is somewhere else?

**Comment by andreasohlund** [comment]
I've opened a PR to clarify https://github.com/Particular/docs.particular.net/pull/1884 , please review @ramonsmits 

Should we close this?

**Comment by ramonsmits** [comment]
Closing this as @andreasohlund made a PR.
