### ISSUE TITLE
Can't configure Recoverability from a feature

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#4156]
The new Recoverability configuration mechanism cannot be accessed from a feature (NServiceBus extension).

[Here's](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/bAOlpZBVriI/Y7h5lxp6AwAJ) a user request for that feature.

**Comment by SzymonPobiega** [comment]
@Particular/nservicebus-maintainers what do you think? To me it sounds like a valid use case.

**Comment by danielmarbach** [comment]
@SzymonPobiega When @tmasternak and I designed the API we didn't want it to be additive because of the complexity involved there. There can only be one custom recoverability policy override which is a user-centered override. I see the following possibilities here

1. We make the API additive (probably not before vNext)
1. The author of the Aggregate API hooks into the internals of recoverability and makes it additive for the users of his library
1. The author of Aggregate.NET exposes his own custom extension method on top of the recoverability seam and forces users to specify that

For me the last option is the most viable one. It removes black magic and gives the users the flexibility to opt-in or opt-out from the behavior and makes it on the level of recoverability apparent that a third party library is using its opinionated way of dealing with retries. Something like

```
    configure.Recoverability().DoItMyWay();

    public static class AggregateNetRecoverabilityExtensions
    {
        public static void DoItMyWay(this RecoverabilitySettings recoverability)
        {
            var settings = recoverability.GetSettings();
            // set keys known to aggregate .net

            // override in opinionated way
            recoverability.CustomPolicy((settings, ctx) =>
            {

            });
        }
    }
```

About the reply and sending messages part. Really on the fence here. Replying is a something that has to happen in the pipeline and not a recoverability concern. The only way I think is feasible by having a combination of multiple moving parts for Aggregate.NET. For example have a behavior which intercepts the exceptions and does retries when needed and the recoverability part as shown above.

**Comment by tmasternak** [comment]
> designed the API we didn't want it to be additive because of the complexity involved there.

I think that this is still valid argument especially when thinking about `CustomPolicy` overrides.

For sending messages one approach could be:
 * Provide custom policy to move messages failing with`BusinessException` back to the input queue - this can be done by overriding error queue address
 * Add custom behavior that will send a response to originating endpoint and move the failed message to error queue

**Comment by volak** [comment]
Thanks for looking into my issue - 

I am certainly not afraid of navigating NSB's internals, after all currently in my lib I am overriding default Invoke and Load handlers.  And I also in one place had to use reflection to hack a method stub for CreateSnapshotRegion - I just dont want to go down that route unless necessary.

Creating an extension method off EndpointConfiguration is currently the plan - the library used to work that way until I found that I didn't have access to Container from configuration.

Thats the route I was going down when I created the groups post.  Its not ideal but I'm fine with that.
I just don't want users to forgot to do it because Aggregates handles the retry policy for both NSB dispatch and reading from eventstore.  So if they say they want 5 max retries I currently set that for BOTH NSB and eventstore.  In 6.0 if they forget to call the config extension method they would continue using the default NSB retry while only getting 5 event delivery retries.

As for replying to business exceptions -  
I kinda like the idea of redirecting the message back into the input queue - except if the consumers are kind of overloaded it might delay the response back to the client due to starvation or what not.
The second idea of a custom behavior to send a response then move to error queue would be ideal obviously.  

Is there a way to insert a message directly into an endpoints own local input queue?  I realize now I could use that for both event dispatching from eventstore and error handling in case of BusinessException - solving both these issues.

Again I'm not afraid of getting my hands dirty in the internals of NSB if you can think of a way to do these things thats not in the public api 🌴

**Comment by volak** [comment]
For reference - 

Here is the custom pipeline behavior that is catching BusinessException and replying:
https://github.com/volak/Aggregates.NET/blob/master/src/Aggregates.NET.Domain/Internal/CommandAcceptor.cs

And here is my own pipeline behavior basically overriding NSB's:
https://github.com/volak/Aggregates.NET/blob/master/src/Aggregates.NET/Internal/ExceptionRejector.cs

One thing here is when a message fails I am sending an Error message back to the client (different from a Reject message when BusinessException happens) because often times the client is waiting for a response.

Note that IIncomingContextAccessor is something just for unit tests don't get confused about the properties coming off it it calls directly into IncomingContext

**Comment by danielmarbach** [comment]
Just a quick note about the "not forget part":

You can check in your feature the existance of a your own keys and throw if not present. So your extension method would add a custom key and the feature throws if not present. I know it is not ideal since it is a runtime concern now but better than silently fall back to NSB behavior (under the assumption that is what you'd not like doing)

**Comment by volak** [comment]
So using recoverability options + my existing exceptionrejector I think I can achieve message sending on exceptions.

But I am going to need to either be able to modify message headers in a behavior, or modify message headers before an immediate retry like we can with failed messages https://docs.particular.net/nservicebus/recoverability/configure-error-handling?version=Core_6#error-message-header-customizations

**Comment by danielmarbach** [comment]
@volak I think in your case you have to do it in a behavior because the header customizations are only applied when the message is moved to the error queue

**Comment by volak** [comment]
@SzymonPobiega @danielmarbach @tmasternak I did a complete upgrade of my project, seems so far to be working though it will require more testing.
I went down the recovery extension method + context setting to throw if not set route - that seems to be the best option but endpoint initiation gets a little weird now.

As for sending messages on failure, the updated ExceptionRejector https://github.com/volak/Aggregates.NET/blob/master/src/Aggregates.NET/Internal/ExceptionRejector.cs is going to keep track of retry counts inside itself and send a reply if the message faults on its last attempt.  
The best way if I can suggest a feature would be for NSB to have headers to indicate how many times the message has been retried and if its the last attempt before Delayed retry etc etc.  That would really make this behavior a lot cleaner as I don't trust the _retryRegistry to work in all situations.

Overall though despite a couple snags with replying on message handlers and not having IMessageSession when the features are started upgrading was pretty easy.

Thanks for the help!  You can close this issue if recoverability just isn't going to be put in a feature anytime soon.  I actually wasn't thinking about an additive api - just setting it, the user can override if they want but at least I can set it as its supposed to be automatically.

**Comment by SzymonPobiega** [comment]
@volak `IMessageSession` is not available during feature `Setup` phase by design. You can access it a bit later, in a `FeatureStartupTask`. This is because during feature setup some things required to send a message might not yet be configured. Here's the flow:

 * Determine which features are enabled
 * For each enabled feature determine if the prerequisites are satisfied. If so, mark it for activation
 * Set up the default settings values provided by all the features
 * Activate (set up) features in dependency order. Here you can modify the pipeline, register things in the container or register a feature startup task
 * Start the tasks
