### ISSUE TITLE
Obsolete SendOptions.SetCorrelationId() with WARN

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4170]
There is no scenario where the users would need to change this so we should obsolete the api and remove in the future (separate issue will be raised once we obsolete)

**Comment by danielmarbach** [comment]
💯 This is a dangerous API and really should be removed

**Comment by danielmarbach** [comment]
Should we add this to 6.1.0 milestone?

**Comment by andreasohlund** [comment]
You meant to obsolete with WARN?

**Comment by danielmarbach** [comment]
yep

**Comment by andreasohlund** [comment]
Makes sense, renamed and removed the breaking change flag

**Comment by timbussmann** [comment]
warning is not obsoleting. I know this is nitpicking, but obsoleting will require a major version. Not sure whether we need a new issue for "warn about using SetCorrelationId" but that's the only thing we can address in a v6 timeframe.

**Comment by timbussmann** [comment]
@Particular/nservicebus-maintainers I raised an issue for the v7 milestone to obsolete the method completely. For this issue I was wondering what's the special case to warn about the removal of this method in advance.
* we didn't warn in v5 for most obsoleted methods  in v6
* Does this mean, that for every obsolete in v7 we will add a warning to v6?
  * if no: why would we do it especially for this feature?

note that I'm absolutely not against adding the obsolete, but it seems to be quite inconsistent with how breaking changes were treated before in my experience?

**Comment by danielmarbach** [comment]
@timbussmann yes we are inconsistent. I think the primary cause for being inconsistent is that v6 just happened and we started to obsolete things on the way. I see us doing a bit more structured planning and when we see a functionality doesn't make sense and we want to obsolete it why not start early and mark it with warn in a minor? If we had done a structured approach we could say we are inconsistent. Since we haven't had a structured approach I think it is fair to say we now start to find out what consistency actually means ;)

**Comment by timbussmann** [comment]
I'm not sure we really want to go down the path of "backporting" obsolete warnings. This would mean we have to release 6.n before the 7.0 rc just to add potential obsoletes. I'll add this to the topics list for the next maintainer sync.

**Comment by timbussmann** [comment]
after discussing this with @Particular/nservicebus-maintainers we concluded that we want to go ahead and add a warning in this specific case, without introducing any form of consistent rule. The thoughts on this:
* It doesn't make sense to warn about obsoleted methods in vNext in general. There are many things to consider when trying to define a consistent rule for this approach.
* There's also a difference in moved/changed methods which replace an obsoleted method and the complete removal of functionality.
* In this specific case, we want to stick with a warning, because in essence we would like to remove this API right now, but can't due to SemVer compliance. We think this is a dangerous API and there should be no reason to use it, therefore, already warning about the usage of this API seems to be valid approach.

**Comment by timbussmann** [comment]
closing this based on #4233
