### ISSUE TITLE
External timeout manager ATT has a race condition

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus#4178]
The acceptance test that uses an external timeout manager depends on the fact that a specific message header is attached when the message is dispatched via the `.TimeoutsDispatcher` queue.

If there's a slight delay between them the message is sent and picked up from the `.Timeouts` queue it may happen that the `.Timeouts` satellite dispatches the message directly and the expected message header is not attached.

**Comment by timbussmann** [comment]
hm, I think this is not only an issue for the ATT, but a general issue of delayed messages with very short delays which will cause in immediate dispatch instead of going through the regular delayed message dispatching. I think the main reason was to avoid potential race conditions with adding and reading timeout data from the timeout storage which are very close to the current time, but I think we need to find a better way to fix this in general. Should we reword this issue?

**Comment by MarcinHoppe** [comment]
If we want to change how the Core behaves for very-close-to-expired messages, we need a separate issue to discuss.

This one is about fixing an ATT so that it relies on a different header that is attached even when the timeout is dispatched immediately and not persisted, as in #4176.

**Comment by andreasohlund** [comment]
>This one is about fixing an ATT so that it relies on a different header that is attached even when the timeout is dispatched immediately and not persisted, as in #4176.

Should we raise a new issue for this and close this one?

**Comment by MarcinHoppe** [comment]
I'd keep this open until #4176 is merged. I think it's up to @Particular/nservicebus-maintainers to open up another issue to change timeout dispatching behavior.
