### ISSUE TITLE
MSMQ: Sending multiple messages with different TTBRs in the same transaction is not handled appropriately

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#4185]
When using MSMQ and several messages are sent in a single transaction, MSMQ uses the TimeToBeReceived property of the first message. This is a documented behavior of MSMQ.

See:
https://msdn.microsoft.com/en-us/library/system.messaging.message.timetobereceived(v=vs.110).aspx

However TTBR is an attribute on the message. The user can set different TTBRs on these messages that are being sent out as part of the same transaction, which would be incorrect. However, NServiceBus core allows this incorrect configuration. It should handle this scenario in a proper manner.
 
One possible way is to throw an exception, as the underlying transport does not support this behavior. 

The discussions regarding this issue are in https://github.com/Particular/docs.particular.net/pull/1956

**Comment by danielmarbach** [comment]
@indualagarsamy you are correct. We are allowing to specify the TTBR on the message level at configuration time. Unfortunately there is no way of knowing in which combination messages are going to be used / sent out at runtime. That's why we use a [runtime check to prevent sending ](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MsmqMessageDispatcher.cs#L56) of these messages. Are you saying our runtime check is not working properly?

In the long term @Particular/nservicebus-maintainers thing it would be best to proceed with [soft TTBR](https://github.com/Particular/NServiceBus/issues/3562#issuecomment-250727384)

**Comment by timbussmann** [comment]
> It should handle this scenario in a proper manner.

can you go a bit deeper into the expected behavior?

**Comment by ramonsmits** [comment]
@danielmarbach with soft TTBR you mean that the framework does a check at receive and ignore if expired?

@indualagarsamy The framework already throws an exception if a TTBR value is set on a message. The behavior is as expected for transaction modes TransactionScope and SendsAtomicWithReceive. We already throw in that case with a exception message that this is not allowed.

However, this is not expected when using ReceiveOnly. Each message can be send 'isolated' but that is not happening due to the batched sends to be participating in the transaction. There is already issue #3562 that mentions this.

**Comment by danielmarbach** [comment]
@ramonsmits yes exactly

**Comment by andreasohlund** [comment]
@indualagarsamy given https://github.com/Particular/NServiceBus/issues/4185#issuecomment-251321830

is there something we need to do here or should we close this one?

**Comment by indualagarsamy** [comment]
Closing this issue based on [@danielmarbach's comment](https://github.com/Particular/NServiceBus/issues/4185#issuecomment-251307921)
