### ISSUE TITLE
Ability to allow immediate retries for transports in the acceptance tests

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4194]
Our default Server template in the acceptance tests disable immediate and delayed retries. The tests defined in the core and executed downstream assume only when they enable it again and allow exceptions to happen they are successful. Otherwise the tests assume a retry is a failure condition and fails the acceptance test. This is a problem for ASB since the connection to ASB can be really flaky. ASB assumes it should always be possible to do retries. That assumption in combination with the connection flakiness can lead to random test failures. For example when ASB tries to complete a message with sends with atomic receive under a transaction scope and the broker connection fails a transaction aborted exception is raised. This is not in the control of the transport.They need to call the recoverability seam which ultimately leads to test execution failure for those tests that don't allow retries to happen (which is by default in the server template). 

We need a transport specific way to hook into the ATT framework and treat those exceptions as "normal" behavior, let it retry without making the tests fail. Maybe a recoverability policy override would do it...

**Comment by andreasohlund** [comment]
If this "flakyness" is to be expected should we consider having ASB have some retries on its own like we do in the ravendb sub storage? (due to expected concurrency issues)

https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Subscriptions/SubscriptionPersister.cs#L63

In short: Should ASB really lean on the core retries to deal with this?

**Comment by SeanFeldman** [comment]
> In short: Should ASB really lean on the core retries to deal with this?

Neither. The solution is to use `IConfigureEndpointTestExecution` which is provided by the the ATT framework and allows overriding of the default behaviour. I've applied that to ASB [here](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/f44348296b9c5362cbf971eaa9727bc2a7ed2a99/src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs#L88) and so far we're good.

I'll close the issue since solution is available. The issue that should remain opened is how we communicate our designs internally. 

Personal retrospective on this is a lesson learned: pairing with @danielmarbach to explain what ASB is doing and having him to explain how ATT framework operates in regards to recoverability, helped to identify the true cause of the problem. Solution is now going to fix not just one case in time, but remove the general "flakiness" from ATTs with ASB.

**Comment by SeanFeldman** [comment]
A lesson for @danielmarbach is to cc/mention the people he worked with 😛

**Comment by danielmarbach** [comment]
@seanfeldman you are absolutely correct. Was a bit in a hurry when I wrote it. Will make sure to. Ot do it again (normally I mention people...)

**Comment by SeanFeldman** [comment]
@danielmarbach I know you do. The pairing session we had has absolutely fantastic results. ❤️ it!

**Comment by danielmarbach** [comment]
> In short: Should ASB really lean on the core retries to deal with this?

I still think it would be worth discussing @andreasohlund point

**Comment by SeanFeldman** [comment]
I've interpreted that as a question related to ATTs. If it goes beyond that, absolutely.
