### ISSUE TITLE
InMemoryTimeoutPersistence depends on TimeoutManager

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#4210]
Relates to https://github.com/Particular/NServiceBus/issues/4168

Flesh out a PoA to address this issue

This also affects RavenDB and NHibernate

**Comment by timbussmann** [comment]
having a quick look at the feature, I think it would be possible to just remove the dependsOn. This will result in `InMemoryTimeoutPersister` being registered in the container even when no `TimeoutManager` is used. Since we only register a factory, no instance is created and it shouldn't be used anywhere.

RavenDB seems to register a startup task and some other minor things which we probably don't want to execute when the timeoutmanager is not used.

NH also seems to have some unwanted side effects (https://github.com/Particular/NServiceBus.NHibernate/blob/develop/src/NServiceBus.NHibernate/TimeoutPersisters/NHibernateTimeoutStorage.cs#L37)

**Comment by bording** [comment]
Given that `InMemoryTimeoutPersister` has no point to exist except working with the TimeoutManager, why wouldn't we want it to depend on TimeoutManager?

**Comment by timbussmann** [comment]
I was asking myself too, what would be wrong with the DependsOn and besides the fact, that the dependency is inverse (timeoutmanager depends on a persistence mechanism, not the other way round), I don't see a good reason why we need remove it. Maybe @danielmarbach can provide more info?

**Comment by andreasohlund** [comment]
>I was asking myself too, what would be wrong with the DependsOn

I think the root cause here is that the persistence API is poorly designed. I'd say we should focus on how to improve that for vNext instead? (ie to have an api that doesn't rely on feature dependencies and uses factories instead like the transport seam)

**Comment by timbussmann** [comment]
so it seems there is no immediate action we should take here and this would be addressed with a better design for feature/component dependencies instead?

**Comment by andreasohlund** [comment]
Yea, 👍 to close
