### ISSUE TITLE
SatelliteReceiver required transport transaction mode isn't validated against supported modes

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus#4221]
## Plan of Attack

- Obsolete with warning AddSatelliteReceiver which allows passing in a transaction mode
- Add a check inside the obsoleted AddSatelliteReceiver which throws if the requested transaction mode is different from the main input one
- Add  an API AddSatelliteReceiver which doesn't allow to specify the transaction mode; the core will automatically set the main input queue transaction mode

## Original content

[`FeatureConfigurationContext.AddSatelliteReceiver`](https://github.com/Particular/NServiceBus/blob/8782230efa6edf789d0b471ab8614f2ffe29e03b/src/NServiceBus.Core/Features/FeatureConfigurationContext.cs#L51) lets you pass in an a `requiredTransportTransactionMode`, but when the `TransportReceiver` for the satellite is created in [`StartableEndpoint.CreateReceivers`](https://github.com/Particular/NServiceBus/blob/8782230efa6edf789d0b471ab8614f2ffe29e03b/src/NServiceBus.Core/StartableEndpoint.cs#L113), the required mode isn't validated against the supported transaction modes of the transport.

This means the transport can get a request to run in a transaction mode that it can't support.

**Comment by bording** [comment]
Seems like this should be fixed along with #4213 in 6.1.0.

**Comment by andreasohlund** [comment]
Not sure I agree. A satellite is in complete control of what consistency is needed for the operation(s) its performing. If the operation performed doesn't need transactions (idempotent) why would we force the transactions to be used when not needed just because the endpoint needs them?

**Comment by SeanFeldman** [comment]
@andreasohlund how about the other way around, the endpoint is configured to use a lower transaction mode that satellite is requesting? If an endpoint is running in Receive only mode, and satellite is requesting Atomic mode, it won't work since transport will be adjusted to the endpoint`s configuration.

**Comment by bording** [comment]
@andreasohlund The key assumption there is that a transport can support more than one transaction mode simultaneously. This appears to be an assumption that we don't have validated in a test anywhere, either.

As @SeanFeldman is saying, that assumption isn't true for all transports currently!

**Comment by andreasohlund** [comment]
:+1: to document this using tests.

I'd say a transport should throw at start up when requested to run in a mode or combination of modes that are not supported?

**Comment by danielmarbach** [comment]
I would like to challenge what ASB currently does. Should we discuss this
in call?

**Comment by SeanFeldman** [comment]
Documentation - yes.
Call to explane - yes.
Having a discussion/ conversation - yes.
Challenging - please challenge when teams *know" and disagree, not when they have no clue.

**Comment by yvesgoeleven** [comment]
I'd like to challenge the way we communicate (again).

**Comment by danielmarbach** [comment]
Based on the comments of @yvesgoeleven and @seanfeldman I see that my comment was not well received. Sorry that I stepped on someones foot.

**Comment by danielmarbach** [comment]
I think from a core perspective we haven't put enough thought into how satellites should behave and how autonomous they can be in terms of choosing their own transaction mode. How about I organize a meeting for next week and invite the core maintainers as well as the transport maintainers into a call where we agree on a future direction / common behavior and raise follow up issues after that call? // cc @Particular/azure-service-bus-maintainers @Particular/azure-storage-queues-maintainers @Particular/sqlserver-transport-maintainers @Particular/rabbitmq-transport-maintainers

**Comment by bording** [comment]
@danielmarbach Do you still want to try and organize a call for this?

**Comment by danielmarbach** [comment]
I saw no response until now when I found out that transport maintainers gave a thumbs up. I'll see what I can do

**Comment by danielmarbach** [comment]
We had a call with @bording @timbussmann @SeanFeldman @boblangley this is the outcome and action points:

We concluded that if only it would make sense for a satellite to lower the transaction mode for performance reasons. We think that is not a use case we want to support because the future of satellites is currently not well known. For example, we could envision that you could just build a message pump and a dispatcher yourself by accessing the transport infrastructure. In the light of that we will go ahead with the following:

- Obsolete with warning AddSatellite which allows passing in a transaction mode
- Add a check inside the obsoleted AddSatellite which throws if the requested transaction mode is different from the main input one
- Add  an API AddSatellite which doesn't allow to specify the transaction mode; the core will automatically set the main input queue transaction mode

I'll update the description of this issue.

**Comment by danielmarbach** [comment]
@andreasohlund see https://github.com/Particular/NServiceBus/issues/4221#issuecomment-258182646

**Comment by andreasohlund** [comment]
I'm good with the proposed actions

**Comment by SzymonPobiega** [comment]
@danielmarbach I [this comment] I summarized the problems one would encounter when trying to put together a pump and a dispatcher. I'll prepare a pull that addresses them.
