### ISSUE TITLE
DisableLegacyRetriesSatellite shouldn't have obsolete attribute yet

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus#4238]
When we added the [DisableLegacyRetriesSatellite](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Recoverability/Settings/RecoverabilitySettings.cs#L65) method, we added the obsolete attribute with a warning at the same time.

This leads to a poor experience, because you have to use this method if you don't want the legacy retries queue to be created, but that means you have to have an obsolete warning in your code.

Given that we added this to be used in the migration from v5 to v6, I don't think we should be warning against using it currently.

**Comment by timbussmann** [comment]
based on our discussions around obsolete warnings, I think it doesn't make sense to have this warning around. We're not blocking any use cases in v7 by removing this method as it becomes the default behavior anyway. As for v6, it's a completely valid scenario to use this method. So 👍 to removing it. Since it's only an attribute, we could do that in 6.1, correct?

**Comment by danielmarbach** [comment]
Double checked with BitDiffer and it seems to be OK to remove the attribute

![image](https://cloud.githubusercontent.com/assets/174258/19610980/9fa0606e-97df-11e6-9f1e-6e3d9c3bfb48.png)

**Comment by andreasohlund** [comment]
:+1: to remove
