### ISSUE TITLE
Permissions changed to Everyone/Anonymous on existing queues when installer are run

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4266]
As pointed out in https://github.com/Particular/NServiceBus/issues/3972 we tamper with permissions on existing queues. This means that we wrongly add `Everyone` and `Anonymous` to existing queues. Even though we tell users to not do this in production.

We should instead:

1. If queue doesn't exist => create queue with appropriate permissions
2. If queue exists => log a WARN if the queue has inappropriate permissions

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers given that this bug means us re-configuring queue permissions to conflict with security best practices should we treat this as a patch?

**Comment by andreasohlund** [comment]
The reason we add  `Everyone` and `Anonymous` is to get a better F5 experience so we probably have to do some trickery to figure out if we're setting up queues for prod or for development

**Comment by andreasohlund** [comment]
@gbiellem @ramonsmits what's your thoughts here?

**Comment by andreasohlund** [comment]
@ramonsmits can you confirm that the following is true:

1. User install the endpoint in production, `Everyone`/`Anonymous` permissions is set on the queue
2. User removes those permissions and instead uses his various service accounts
3. Next time the user "/installs" the host or run the installers in a selfhosted endpoint we put `Everyone`/`Anonymous`  back on the queues again

**Comment by ramonsmits** [comment]
@andreasohlund When I created https://github.com/Particular/NServiceBus/issues/3972 the permissions were reset. The [history doesn't show any changes since then](https://github.com/Particular/NServiceBus/commits/master/src/NServiceBus.Core/Transports/Msmq/QueueCreator.cs) so behavior should still be the same.

> 1. User install the endpoint in production, Everyone/Anonymous permissions is set on the queue

Yes, https://github.com/Particular/NServiceBus/blob/6.0.0/src/NServiceBus.Core/Transports/Msmq/QueuePermissions.cs#L62-L63

> 2. User removes those permissions and instead uses his various service accounts
> 3. Next time the user "/installs" the host or run the installers in a selfhosted endpoint we put Everyone/Anonymous back on the queues again

Yes, https://github.com/Particular/NServiceBus/blob/6.0.0/src/NServiceBus.Core/Transports/Msmq/QueueCreator.cs#L43-L58

I did a spike PR to change this behavior which I can migrate to the NServiceBus repo: https://github.com/ramonsmits/NServiceBus/pull/1

**Comment by andreasohlund** [comment]
Go for it!

**Comment by andreasohlund** [comment]
@ramonsmits lets get this going I believe this warrants a patch

**Comment by mauroservienti** [comment]
@Particular/nservicebus-maintainers please raise an issue in PlatDev so that a proper Task Force can be formed to handle this.

**Comment by andreasohlund** [comment]
Fix for 6.1 is now in, will start with a backport to 6.0.3 now

**Comment by andreasohlund** [comment]
https://github.com/Particular/NServiceBus/releases/tag/5.2.20 and https://github.com/Particular/NServiceBus/releases/tag/6.0.3 has been released to fix this
