### ISSUE TITLE
RepeatedFailuresOverTimeCircuitBreaker triggers after a single error

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus#4275]
While working on one of the issues for ASB transport, an issue with circuit breaker was identified. Since circuit breaker in v6 was copied from the core as-is, the same issue is found in core.

[`RepeatedFailuresOverTimeCircuitBreaker`](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/CircuitBreakers/RepeatedFailuresOverTimeCircuitBreaker.cs#L37) indicates that a failure has to be repeated. Circuit breaker should have a few failures prior to arming and scheduling an action. Instead, a single error will arm the trigger.

This could end up in a scenario where a single failure will arm CB and cause it to execute the scheduled action w/o repeated failures.

[Previous major version](https://github.com/Particular/NServiceBus/blob/670d6f60003d87a2a9d7535f06c8017c9fa41d8b/src/NServiceBus.Core/CircuitBreakers/RepeatedFailuresOverTimeCircuitBreaker.cs) also exhibits this behaviour. Is the name incorrect or the behaviour is broker @Particular/nservicebus-maintainers?

**Comment by danielmarbach** [comment]
While the name might be misleading it works as follows: one failure
triggers the timer. If you don't mark success in the time before the
callback of the timer fired it will trigger the critical error. In that
sense it is "repeated failure over time" because the number of failures is
irrelevant while armed. The success is relevant

**Comment by SeanFeldman** [comment]
👍
