### ISSUE TITLE
Add non async handlers

### ISSUE THREAD

**Issue by MeTitus** [Particular/NServiceBus#4296]
No idea why sync handlers were removed altogether but we definitely need them back. There are instance where all and handler is doing is something dumb, with no messages being publish/sent. Without sync handler this is what we get to:

    public class PatientDischargedHandler : IHandleMessages<IPatientDischarged>
    {
        private readonly IPatientInfoRepository _patientInfoRepository;

        public PatientDischargedHandler(IPatientInfoRepository repository)
        {
            _patientInfoRepository = repository;
        }

        public Task Handle(IPatientDischarged message, IMessageHandlerContext context)
        {
            _patientInfoRepository.Delete(message.PatientId);

            return Task.FromResult(true);
        }
    }

Which is something strange to say the least. To make things worse, the method signature does not take a CancellationToken either.

This is what he should be:

    public class PatientDischargedHandler : IHandleMessages<IPatientDischarged>
    {
        private readonly IPatientInfoRepository _patientInfoRepository;

        public PatientDischargedHandler(IPatientInfoRepository repository)
        {
            _patientInfoRepository = repository;
        }

        public async Task HandleAsync(IPatientDischarged message, IMessageHandlerContext context, CancellationToken token)
        {
            await _patientInfoRepository.DeleteAsyn(message.PatientId, token);
        }
    }

**Comment by timbussmann** [comment]
Hi @MeTitus 

As you correctly pointed out, sync handlers only make sense when you're not using the context and only invoke sync APIs. As this is not something we can assume to be the "default" case, we don't provide sync handlers (also because this easily introduces the risk of using blocking waits instead of the async handlers). The current recommendation is, as you already doing correctly, using `return Task.FromResult(0)` or `return Task.CompletedTask`. If you have many handlers like this, you could consider making your own message handler base class, e.g.:

    public abstract class SyncHandler<TMessage> : IHandleMessages<TMessage>
    {
        public Task Handle(TMessage message, IMessageHandlerContext context)
        {
            Handle(message);
            return Task.CompletedTask;
        }

        public abstract void Handle(TMessage message);
    }

and then write your handlers like this:

    public class SyncMessagehandler : SyncHandler<SyncMessage>
    {
        public override void Handle(SyncMessage message)
        {
            // your code
        }
    }

as for the cancellation token, we do not provide cancellation tokens at the moment, because there is nothing we cancel at the moment. Therefore there is no value in passing tokens. This is a topic we are still discussing and it's possible that we will add cancellation token support in the future.

**Comment by MeTitus** [comment]
@timbussmann Yes I could do my own base handler but that's something I wanted to avoid.

**Comment by timbussmann** [comment]
@MeTitus could you elaborate why you want to avoid this in the first place? To me this seems to be a fairly simple solution to your specific scenario. Would you say that it would be less of a pain if we shipped that base class as a part of NServiceBus?

**Comment by MeTitus** [comment]
@timbussmann I just think it would me much nicer if you had followed MS nomenclature for the async methods and had implemented something like this:

    void Handle(T message, IMessageHandlerContext context)
    Task HandleAsync(T message, IMessageHandlerContext context, CancellationToken token)

and even if there is nothing to cancel now, which I find strange given then IO resources we might need to integrate with when handling a message, it would be future proof.

**Comment by timbussmann** [comment]
> I just think it would me much nicer if you had followed MS nomenclature for the async 

That's a perfectly valid opinion, but we had long discussions about this topic internally and came to the conclusion, that we don't want to follow that recommendation. We tried to document our decision and the reasoning here: https://docs.particular.net/nservicebus/upgrades/5to6/async-suffix#other-libraries-with-no-async-suffix. 
There is no black and white on topics like this and we carefully made our decision, fully aware this has up- and downsides. For us, upsides over-weighted the downsides and that's we we ended up with that API. If you're having a bad experience because of this, we're sorry about that and we're happy to help you to make the pain as little as possible, but at the current state the API isn't going to change.

> and even if there is nothing to cancel now, which I find strange given then IO resources we might need to integrate with when handling a message, it would be future proof.

We decided that we don't want to add "fake" cancellation token support just because for the sake of following the guidelines. Our pipeline does currently not attempt to cancel message processing prematurely and there are little use cases where we would actually gain a value by that. 
The good part is, that we can introduce cancellation token support in future releases without breaking changes. So if that need arises, it shouldn't be an issue to switch over to use cancellation tokens. 
Note that it's perfectly valid to create cancellation tokens inside your handler and pass them down to your async resources if you can make use of it, but as the pipeline doesn't cancel processing of "inflight" messages (even when shutting down the endpoint) a token would just be noise. Of course we are very interested to hear about your use case if you find yourself in the need of a cancellation token provided by NSeviceBus.

**Comment by danielmarbach** [comment]
More information about cancellation can be found [here ](https://github.com/Particular/NServiceBus/issues/3765)

Regarding sync vs. async. My coworkers have provided some insights. Another reason why we didn't provide sync overloads is that we need to be async all the way into the usercode. Synchronization is a responsibility of the user code since only the usercode knows where and when synchronization makes sense. This is by far the strongest point why we decided not to provide sync APIs. 

Furthermore we believed that the choice of having to choose between two interfaces (`IHandleMessagesSync` vs. `IHandleMessagesAsync`)  to implement a handler doesn't make the framework more userfriendly. 

Thanks again for your input. Keep it coming!

Closing this since all relevant discussion points have been outlined and we are not changing this.

**Comment by MeTitus** [comment]
@danielmarbach 

"Another reason why we didn't provide sync overloads is that we need to be async all the way into the usercode." this is exactly the reason why this implementation is wrong. You say you need the code to be async but then again you don't even have an overload which accepts CancelationTokens. And look at what @timbussmann said before: 

> as for the cancellation token, we do not provide cancellation tokens at the moment, because there is nothing we cancel at the moment. Therefore there is no value in passing tokens. 

Also about this:

> to implement a handler doesn't make the framework more userfriendly.

Do you really think that providing a different way to work with async methods from what MS does with all the libraries/frameworks will not confuse everybody? Don't take me wrong but you really need to get this sorted out.
