### ISSUE TITLE
Consider providing a custom session-like object for InMemorySagaPersistence

### ISSUE THREAD

**Issue by Scooletz** [Particular/NServiceBus#4318]
Currently, all the saga persisters provide custom extension methods to obtain a session in a saga finder that can be used to query the store:
1. RavenDB: `var session = storageSession.RavenSession();`
1. NHibernate: `var session = storageSession.Session(); `

Should we consider providing one for in-memory persistence to enable queries spanning across the whole store? This could  potentially impact the performance (more locking) or lead to more complex data structures.

This issue is a result of discussions related to the redesigned `InMemorySagaPersister` (https://github.com/Particular/NServiceBus/pull/4300)

/cc @danielmarbach @timbussmann

**Comment by dbelcham** [comment]
Those two examples show how easy it is to expose that kind of data access in the finders if the persister is a wrapper around a data access component. In the case of InMemory, there is no single data access component like that to be exposed. The equivalent of that component is the InMemorySagaPersister itself. So if we were to do this we would probably have to create a container object that housed all the InMemory data similar to how a database holds data for NHibernate, and we'd need to have an object that acts like a lightweight session that could be passed to the custom finder to provide access to that database style container.

**Comment by danielmarbach** [comment]
Why not just make the dictionaries internal and expose it to the session provider for InMemory and then mask it over a high level API?

**Comment by timbussmann** [comment]
I'm a bit concerned that @danielmarbach suggestion will lead us to expose too much of the internals. Even if we wrap the implementation over another API, we need to make sure that we're still compatible with that for future changes. Personally, I don't really see the use case for custom finders in InMemoryPersistence at the moment.

**Comment by Scooletz** [comment]
If we expose dictionaries (probably exposing the primary index, by saga id, is just enough) it's highly likely that a potential finder would use `.Values` which would reintroduce locking of all the buckets. That was the cost we wanted to remove. Enabling finders in my opinion should not impact the performance of the current improved solution.

Now the engineering dream part ;-) Here it comes!
If we provided a new saga finder for this purpose, that returns an expression representing accessing  properties of a message and a saga (like we do for correlation purposes) we could `maybe` create additonal secondary indexes (like the correlation id) and have a lookup instead of scan !

**Comment by danielmarbach** [comment]
Well first of all I agree I don't see much value in a custom finder for InMemory persistence. But we also said it is a production ready persister which we support. So as it is consider a production ready persister when we don't provide custom saga finders it is essentially not fully feature compliant which arguably could be seen as a bug. Creating an API over the internal dictionaries would mean we can make the tradeoffs properly. We could like @Scooletz said internally use Values and expose it as an IEnumerable and then people can write LINQ queries against it with the cost that it will introduce locking. But at least we could say it is feature complete with the caveats that querying against it reduces performance (I think this is a reasonable trade off to make). From that point of view we can always improve the internal implementation if required since the underlying data structures are abstracted away from the users (for example we could copy the data and do other fancy tricks)

**Comment by Scooletz** [comment]
Or we could simply accept `Func<TSagaData, bool>` and disallow iterating on its own.

**Comment by danielmarbach** [comment]
We talked this through in today's maintainer sync and came to the following conclusions.

* Both spikes show that it is possible to create an API which allows to expose data saved in the InMemoryPersistence for usage in the custom saga finders and potentially even other places
* Currently we have no real demand from users to support custom saga finders with InMemoryPersistence
* Implementing it right now means we have to support and maintain it although there is no demand

Based on that we think the spikes show enough meat to implement it anytime in a minor version and we are closing this issue as well as the spikes and won't pursue it right now.
