### ISSUE TITLE
Msmq Subscription storage not working in NSB 6

### ISSUE THREAD

**Issue by valeriob** [Particular/NServiceBus#4340]
I was able to reproduce it on different win10 machines : 
1) Download the sample at https://docs.particular.net/samples/pubsub/
2) Add the following line of code in MyPublisher\Program.cs line 21
 endpointConfiguration.UsePersistence<NServiceBus.Persistence.Legacy.MsmqPersistence, NServiceBus.Persistence.StorageType.Subscriptions>();
2) Run the sample
3) the queue nservicebus.subscriptions is empty

The problem is exactly that, subscriptions are not persisted.

**Comment by mikeminutillo** [comment]
Thanks for raising this @valeriob 

I was able to reproduce this.

It looks like it's related to the [transaction type here](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorageQueue.cs#L45). Changing this transaction type to `Automatic` makes the messages appear in the queue as expected. I don't know what other effects this has though.

In order to acceptance test this, you'd need to start the publisher, then a subscriber, then restart the publisher and publish an event. Then you can assert on whether the subscriber gets the event published.

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers I propose we treat this as a patch?

**Comment by danielmarbach** [comment]
@andreasohlund I agree. Who can lead it?

**Comment by andreasohlund** [comment]
I'll deal with this.

PR with repro here 

https://github.com/Particular/NServiceBus/pull/4343

**Comment by andreasohlund** [comment]
We've just release 6.0.2 with a patch for this https://github.com/Particular/NServiceBus/releases/tag/6.0.2

@valeriob would you be able to update and verify that it fixes the issues?

And huge thanks for taking the time to raise this! ❤️

**Comment by valeriob** [comment]
It's working now :D
Thanks, that was fast !
