### ISSUE TITLE
should TimeoutData.State be a stream so as to avoid the memory loss?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4448]

**Comment by danielmarbach** [comment]
I think ideally it would be a stream, Span<T>, or an ArraySegment yes

**Comment by andreasohlund** [comment]
Just noting that we're going to hit the issue with the persisters actually storing the TimeoutData type  so we need to take that into account when we come up with a POA

Related to https://github.com/Particular/NServiceBus/issues/2169

**Comment by timbussmann** [comment]
@SimonCropp to clarify, do you mean unnecessary memory pressure instead of memory loss (e.g. memory leak)?

I think at that point, using streams won't yield much as the pipeline always works with byte arrays anyway, so there is never a case where we can actually make use of streaming from input to output or similar thing. For streams to gain benefits that would require a major pipeline change .

**Comment by timbussmann** [comment]
ping @SimonCropp 

without pipeline changes I don't see much gained by using streams. Is this something good enough to drive such a change? Otherwise I'd propose to close this.

**Comment by SimonCropp** [comment]
@timbussmann yeah u r correct. I should have done more research prior to raising this
