### ISSUE TITLE
Testing specific saga handler causes NHibernate exception

### ISSUE THREAD

**Issue by scrooby** [Particular/NServiceBus#4456]
I have a saga that I'm attempting to test by sending a message to the saga queue and asserting that the outcome of the saga is as expected.

Below is a simplified example of the first two steps of the saga:

```
public async Task Handle(StartSagaCommand message, IMessageHandlerContext context)
{
    Data.Originator = context.ReplyToAddress;
    Data.OriginalMessageId = message.MessageId.ToString();
    Data.CorrelationId = message.CorrelationId;
    Data.SagaState = "started";

    context.Send(new DoSomethingCommand {
        CorrelationId: message.CorrelationId
    });
}

public async Task Handle(SomethingDoneEvent message, IMessageHandlerContext context)
{
    Data.SagaState = "something done";
    return Task.CompletedTask;
}
```

If I test this by sending a `StartSagaCommand` to the queue, it works fine and I can assert that my `SagaState` gets set to "something done".

However, rightly or wrongly, during development, we've been testing the individual steps of the saga. For example, I create a record in the saga data table, publish a `SomethingDoneEvent` and assert that the saga data is updated. And this is where my problem lies.

Testing a saga handler that _doesn't_ update saga data works fine. However, if the saga handler _does_ update saga data, I receive the following error:

> NHibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect)

We have another saga that has a similar flow of updating saga data which does not receive the above error. However, I've found that the reason that saga works is because that saga has a manual NHibernate mapping class (due to a problem in NHibernate around max length nvarchar fields).

If I add an NHibernate mapping class to my first saga, all the tests work!

Is this an issue? From my probably simplistic view, I don't see a difference between me creating the saga data record, and the record being created by the first step of the saga. Or are we being unreasonable to assume we should be able to test each step of the saga flow without starting from the beginning?

**Comment by dbelcham** [comment]
@scrooby Two questions for you to help guide us to a solution:
1. Can you provide a sample test for us to look at so we can try to determine what the purpose of the testing is?
1. Can you provide us with the class you have that implements `ContainsSagaData`?

@bording and I have talked about this and we have a few ideas but we definitely need some more information to narrow things down.

**Comment by andreasohlund** [comment]
You don't need to assign the originator and the original message id properities since that is handled automatically by NServiceBus. Can you try to remove those just to rule that out?

**Comment by scrooby** [comment]
@dbelcham I've setup a Gist that contains a sample SpecFlow test and the saga data class that is being used: https://gist.github.com/scrooby/b5b27e0009254752f823f8e5486354b6

As I mention in the Gist description, some of the code has been flattened so it's easier to see what's going on. I've run the test and it still results in the same error.

@andreasohlund Removing the manual setting of the two properties didn't help unfortunately. It's good to know that we don't need to set these manually though!

**Comment by dbelcham** [comment]
@scrooby Thanks for the gist. I looked at it and I know it's a simplified repro of what you're doing. Is checking a sagadata property all your "real" test is doing too? I'm asking because I'm wondering if there might be a better approach to how you're writing the test, but that requires some understanding (on my part) of what you're really trying to accomplish with the test.

**Comment by scrooby** [comment]
@dbelcham In that scenario, that's all the test is doing. It is probably our simplest test in the saga since it's just listening for a failure event and updating the state of the saga for auditing/debug purposes. We've found these tests are quite handy since we can write them during development to make sure each step is working. It also means that we don't need to assert each state of the saga in the overall saga test which would run from start to finish.

**Comment by timbussmann** [comment]
There seems to be quite a bit of infrastructure from the testing and sadly I don't see any chance to reproduce the exception with the gist you provided.

Is there any chance that tests run in parallel or your test setup generates the same saga id multiple times which could cause in the exception you're experiencing?

Also, is the endpoint you're publishing the event from also the endpoint which handles the event? In that case, you also might run into race conditions as you stop the endpoint immediately after publishing the event.

**Comment by scrooby** [comment]
@timbussmann I'm running the test on it's own, from my local machine, so it won't be running in parallel with any other tests. The test uses AutoFixture to build a new saga data object each time, so the id should be different with each run.

The endpoint that the event is published from is built from the test project whereas the saga process runs separately, with it's own endpoint instance.

**Comment by dbelcham** [comment]
@scrooby Based on what you've provided thus far, it seems like the NHibernate Session is picking up the Dapper changes you make to the saga data in the database. I'm not sure we can be clear on how or why since we don't really recommend setting up tests in the manner you've shown.

If all you're wanting to do is test the failure handler's changes to the saga data, why do you need to spin up the entire endpoint? Why couldn't you take a more traditional unit testing approach to this verification? Not only that, but as @timbussmann pointed out, sending the message and then immediately shutting down the endpoint could (not sure if that is the case here) make some really odd things happen in your test.

I created a gist here (https://gist.github.com/dbelcham/6e92540022a4ac938e1deb38b875a442) that outlines my thoughts on a simpler set of tests. It uses raw NUnit but I think you can see what I'm getting at. The reason I'm suggesting this is that there's no reason for you to be testing the entire message pipeline. We have unit tests that verify that the saga data is properly loaded from and persisted to the database. By creating raw insert to the database to setup your scenarios you're also exposing your tests to the possibility of breaking if/when we make changes to the underlying persistence store mechanisms.

If you do test more than just saga data state changes, take a look at [our docs on testing](https://docs.particular.net/nservicebus/testing/) and consider using the [NServiceBus.Testing](https://github.com/Particular/NServiceBus.Testing) package. This package allows for verification of messages being sent and other handy checks as part of a pipeline.

**Comment by scrooby** [comment]
@dbelcham We do already have unit tests around each handler of the saga, but I do think there is some value in also testing from a higher level by sending in a message at a particular point in the saga flow.

1. In the case where we're dealing with events, it ensures that our message endpoint mappings are correct
2. We script our saga data tables manually, so the tests make sure the structure is working correctly
3. We keep an audit of messages we have handled, we assert against that to make sure that a) the message has completed successfully and b) that the auditing is working correctly

Some of those would be covered by the test which tests from start to finish, however, by having tests at each step, we can identify the location of a failure faster. Also, some of the error flows are also quite difficult to test end-to-end since sometimes the only way to trigger an error is infrastructure related, a database connection failure for example.

**Comment by timbussmann** [comment]
@scrooby I'm having a hard time to locate the problem you're facing with the available information and at that point I'm not sure how to go further on this. To me this looks like an issue with your testing infrastructure and setup, not like an issue which can occur on a regular endpoint outside your test harness.

If you can provide us with a working repro sample which is able to demonstrate the exception in the simplest possible way, we're happy to have a closer a look at this.

**Comment by scrooby** [comment]
@timbussmann I've created a repro sample: https://github.com/scrooby/NServiceBusNHibernateErrorExample

It may well be a side affect of something with our testing infrastructure, I'd just like to establish if that is the case or whether there's an issue that's causing this.

**Comment by dbelcham** [comment]
@scrooby I've been looking into this and I can reproduce your error. I'm trying to get to the bottom of it with some of the @Particular/nhibernate-persistence-maintainers

**Comment by dbelcham** [comment]
@scrooby the @Particular/nhibernate-persistence-maintainers took a look at this and found the root of your problem. In your Dapper SQL statement you use `GETUTCDATE()` to fill the `SagaStateUpdatedDate` column. This is what is causing NHibernate to throw errors further down the stream.

Probably the simplest fix for you is to pass a C# `DateTime` value to that part of the SQL statement instead of the `GETUTCDATE()` call.

Let us know if this works for you.

**Comment by scrooby** [comment]
@dbelcham thanks for investigating, it look like that's done the trick!

Just out of interest, do you know why using one of the date functions would have caused this error? It seems pretty odd, particularly as it's not done directly through NHibernate.

**Comment by dbelcham** [comment]
@scrooby Maybe @MarcinHoppe can clarify, but my understanding is that it was to do with how NHibernate was scripting the creation of the table (driven by the data that `GETUTCDATE()` creates) and how that differed from what NHibernate was doing with the `DateTime` type during the Update.

**Comment by ramonsmits** [comment]
Without reading into the issue you get this OCC issue probably because you are inserting a datetime with milliseconds. NHibernate datatime chops off the milliseconds when writing to the database. When you update a record it will add an OCC check in the WHERE clause which will now have a non matching datetime values. This results in 0 rows being updated and then you get this error.

**Comment by MarcinHoppe** [comment]
I couldn't have said it better myself. This is exactly what is happening.

**Comment by scrooby** [comment]
@dbelcham / @ramonsmits I see, that makes sense. I'm not at all familiar with NHibernate so thanks for clarifying.

I'll close the issue off. Really appreciate you investigating this one and finding the problem, thanks!
