### ISSUE TITLE
Registering a mutator from withing a feature does not work

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#4463]
## Who's affected
* All customers registering mutators in Features.

## Symptoms

So this code works in 6.0 but fails in 6.1.2
```
public class LogicalThreadContextFeature : Feature
{
    internal LogicalThreadContextFeature()
    {
        EnableByDefault();
    }

    protected override void Setup(FeatureConfigurationContext context)
    {
        context.Container.ConfigureComponent(typeof(LogicalThreadContextMutator), DependencyLifecycle.InstancePerCall);
    }
}
```

So in 6.0 the `LogicalThreadContextMutator.MutateOutgoing` will be executed, in 6.1.2 it will never be executed

Repro: https://github.com/Particular/BugsRepro/tree/master/MutatorInFeature

Raise in google groups https://groups.google.com/forum/#!topic/particularsoftware/VSIipYBABAs

**Comment by SimonCropp** [comment]
to narrow the range a little. it works on 6.0.6 but fails on 6.1.0

**Comment by bording** [comment]
Yeah, it's a known change, side effect of #4253.  See https://github.com/Particular/NServiceBus/pull/4253#issuecomment-267448882 and further comments.

It can be worked around by using https://docs.particular.net/nservicebus/lifecycle/ineedinitialization to register the mutator instead of a feature.

When this came up before, @danielmarbach and looked and didn't see that we've said registering mutators inside a feature was supported, according to the docs, so the workaround seemed reasonable.

**Comment by timbussmann** [comment]
we discussed this on the @Particular/nservicebus-maintainers weekly sync and came up with different options which I'll try to summarize here:

* Allow mutator registration in features Potential approaches are:
  * Instead of within a feature itself, move the logic which resolves and configures mutators after all features have been set up. This might conflict with the idea of treating mutators as an optional feature which therefore should only rely on the feature APIs. This might still be a suitable workaround which probably needs to be removed later on.
  * Instead of configuring the mutator behavior at endpoint startup time, we can use some lazy-loading approach to call `BuildAll` for the mutators on the first behavior invocation. This requires no changes outside the feature/behavior API but the lazy initialization adds processing time to the first message.
* The current registration API is quite low level and instead, the mutator feature should provide a better API in the first place. Once we move away from public container usage, this is a step we need to make anyway and it yields several other benefits. By adding a better API, it's much better documented where and how it is usable. We can document the new API (which doesn't allow mutator registration from features) and remove the RegisterComponent documentation for v6 which make it more clear, that this is not intended usage.
* Document that this is a non-intended usage of mutator registration and recommend to register mutators in the endpoint configuration or to use a custom behavior instead. In the future it's going to be very likely that we're not going to support mutator registration from within features as we want to remove container usages, so users need to adapt anyway. There are enough workarounds available to bypass the mutator registration limitation.

There were quite a lot of pros and cons to each of those options. Here is what we came up with as a proposal on how to move forward:
* Allow mutator registration from features for now, as the API looks like this should be possible. This can be released as a (non-critical) patch release for 6.1.
* Introduce a better mutator registration API in the next minor and remove documentation of the RegisterComponent approach, so that users are guided towards the new API which won't allow mutator registration in features (the RegisterComponent approach would continue to work in this major version though). (this can be handled via a different issue)

thoughts @SimonCropp ?

**Comment by SimonCropp** [comment]
> Allow mutator registration from features for now, as the API looks like this should be possible. This can be released as a (non-critical) patch release for 6.1.

Looks good.

> Introduce a better mutator registration API in the next minor and remove documentation of the RegisterComponent approach

also looks good

>  won't allow mutator registration in features 

dont understand  why mutators would not be supported from within a feature. but happy to discuss on the new issue

**Comment by danielmarbach** [comment]
@SimonCropp see #4466

**Comment by bording** [comment]
@danielmarbach I see you added this to the 6.2.0 milestone. Should we be considering putting this change out as a 6.1.x as well? That seems to be what we agreed on in the sync meeting.

**Comment by timbussmann** [comment]
reopening based on @bording comment and the discusses approach. I'll cherrypick @danielmarbach PR against develop and raise a new issue for the new API.

**Comment by timbussmann** [comment]
backport raised in #4477, issue regarding the API changes raised in #4478.
