### ISSUE TITLE
Customize assembly scanning

### ISSUE THREAD

**Issue by slahn** [Particular/NServiceBus#4471]
One of our send-only endpoints is hosted in an appdomain we don't control.
Our assembly is not in the base directory of this app domain, and we can't put it there (reliably).

We only need to scan two non-core assemblies: One with messages, and one with a custom behavior.
These assemblies are not on disk at all, but are loaded into the AppDomain.
In v5, we could manually specify the assemblies to scan, and this worked fine.

In v6, our messages are not discovered.
This seems to result in some other fun bugs, like NullReferenceExceptions when sending, but even if those are fixed, we still can't use v6 unless we can get our messages discovered.

I have two suggestions: 
 - Supply Assembly types to NServiceBus when configuring, like in v5 
 - NServiceBus scans assemblies already in the AppDomain

I'm happy to help with implementing either of these, and tests for the functionality.
(this is related to #4446 in that it's a regression from v5, but a different use case).

**Comment by danielmarbach** [comment]
Hi @slahn 

Thanks for raising the issue including the willingness to jump in helping us out. Would it be possible for you to send me a simple repro solution so that I can have a look at the assembly scanning NullReference issue you are facing? Because such an exception is definitely not helpful and we need to improve.

About your two suggestions:

I do not think we are going back to support an inclusion model. In the past, we had two many caveats with this model that's why we moved away. Certainly, I'm happy to raise it in the internal discussions again and keep you updated.

About including assemblies in the AppDomain. We had this functionality already built, but it was never exposed. See https://github.com/Particular/NServiceBus/commit/29728d13ca17c4f8793e2e8b6fd18dd84daa0476 
@SimonCropp @andreasohlund any ideas why we removed it from the public surface? I removed it because it was no longer exposed to any settings. I'd be OK to bring this back as a public setting in 6.2 or so

Do you have a necessity to jump on v6 asap? If yes I might be able to provide you a workaround (with lots of strings attached though)

**Comment by andreasohlund** [comment]
>any ideas why we removed it from the public surface?

Sorry, nothing comes to mind

**Comment by slahn** [comment]
We'll probably be fine keeping the send-only endpoint at v5. We do that in production currently.
I'm working on a minimal repro of the exception and will post that as a separate issue.

My dream solution here would be to be able to replace an IAssemblyLocator in the endpoint, so we could avoid hitting disk at all. But scanning types already in the AppDomain should solve our issue - as long as we can still provide an exclude list for those types as well.

**Comment by danielmarbach** [comment]
Hi @slahn 

https://github.com/Particular/NServiceBus/pull/4485 will bring back the possibility to scan types in the AppDomain. This will be available in 6.2. Or you OK with me closing this issue?
