### ISSUE TITLE
Cannot override reply-to address in V5

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#4476]
The [documented way](https://docs.particular.net/nservicebus/messaging/send-a-message?version=core_5#influencing-the-reply-behavior) of overriding reply-to header does not work in V5 (at least it does not work in MSMQ and SQL transport).

The reason for this is the code in core always sets the reply-to address in the `DeliveryOptions` to `Configure.PublicReturnAddress` and the transport code treats that field with higher priority than the value in the headers dictionary.

**Comment by SzymonPobiega** [comment]
Discussed that with @andreasohlund and concluded we'll close with "won't fix" bug given that this is documented, what should we do with the documentation? The same feature in V6 works correctly.

**Comment by timbussmann** [comment]
> what should we do with the documentation? 

can we just remove the documentation for v5?

**Comment by SzymonPobiega** [comment]
Yes, we can. This would effectively mean that this feature is V6-only

**Comment by timbussmann** [comment]
@SzymonPobiega is this doc invalid too: https://docs.particular.net/nservicebus/messaging/reply-to-a-message?version=core_5 ?

**Comment by SzymonPobiega** [comment]
@timbussmann the "influencing reply to behavior" part is invalid, too.

**Comment by timbussmann** [comment]
docs PR raised here: https://github.com/Particular/docs.particular.net/pull/2447
att for v6 for the reply options raised here https://github.com/Particular/NServiceBus/issues/4482

Since @SzymonPobiega and @andreasohlund already thought that through and decided to not fix it, I'm closing this. Please feel free raise your voice if you disagree with this approach.
