### ISSUE TITLE
Should we provide a routing API accepting machine names for MSMQ?

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#4500]
As we want to get rid of our usages of ConfigurationSections, MessageEndpointMappings finally needs to go. We already have a code first routing API but this API is more restrictive as it doesn't accept transport addresses (e.g. for MSMQ something like "sales@machine-A").

This limitation was added in order to better support sender-side distribution but it was also argued, that hard coding machine names into code is a bad idea in general. MessageEndpointMappings continued (and continue) to work with transport addresses which also makes sense in regards that they are config based and don't require a rebuild in case of address changes. Once we remove MessageEndpointMappings, the only way to specify a machine name for MSMQ endpoints would be using the instance mapping file, which requires a new XML configuration file which can specify the machine name of an endpoint instance.

So the current situation with the next major (which would remove MessageEndpointMapings), MSMQ users need to switch to the code first API and additionally add the instance mapping file to specify the machine name. This is quite a bit of effort in case you're not using scaled out MSMQ endpoints (as the instance mapping file is only providing the machine name information). I expect quite a large amount of users running into this migration scenario as it's very likely to use multiple machines with MSMQ.

While I agree that hard-coding a machine name doesn't seem to be a good idea, should there be an easier way for users to configure MSMQ routing when not using sender-side distribution? An API allowing a machine name could always read the parameter from a custom app config key, done by the user. E.g. something like `routing.RouteToEndpoint(typeof(MyMessage), "sales", machinenameFromAppConfig);` (we have the ability to scope routing APIs to a specific transport, so that no other transport could make use of this option).

Thoughts @Particular/nservicebus-maintainers @WilliamBZA (also pinging the routing taskforce which was involved in this decisions back then @DavidBoike @bording @SzymonPobiega)

**Comment by bording** [comment]
Adding an overload of `RouteToEndpoint` that accepts a machine name seems a bit too much like it's mixing the logical and physical aspects of routing, though maybe that's not such a terrible thing?

What about the idea of having a code based way to apply the mapping? For example, you'd have:

```csharp
routing.RouteToEndpoint(typeof(MyMessage), "sales");
routing.MapEndpointToMachine("sales", "machinename");
```
That would maintain the idea of both logical and physical, but maybe there's not value in that?

**Comment by DavidBoike** [comment]
@bording I actually like that better. At least then you could load some values from your own database and run through the MapEndpointToMachine in a loop.

**Comment by timbussmann** [comment]
I like @bording suggestion 👍 given those arguments, we would be able to register an endpoint instance which will be resolved when we resolve the logical sales route. The only downside would be potential conflicts in case somebody mixes this up with the instance mapping file, but that doesn't seem to make any sense.

**Comment by cremor** [comment]
I tried to implement code based physical routing for MSMQ today. I agree that a new simple API would be good.

But it is already possible to do it now with a `Feature`, isn't it? Because in my test project it worked when I just used the code sample from the [Routing system extensibility points documentation page](https://docs.particular.net/nservicebus/messaging/routing-extensibility#routing-apis-physical-routing) and extended it with some custom settings as documented [here](https://docs.particular.net/nservicebus/pipeline/features#enabling-disabling-and-activation-prerequisites).

**Comment by timbussmann** [comment]
Hey @cremor 
Yes, exactly, the APIs are already available but they are a little bit hidden because we feel that they are non-trivial to use and most likely are just used as an integration point to plug in your custom routing data provider (e.g. read it from a database) instead of being part of the regular endpoint configuration routine. What were your thoughts with the API you used (and the related documentation)? Is there some API you missed?

**Comment by cremor** [comment]
@timbussmann The API itself is fine in my opinion. But I'd like to have a bit better documentation. For example, if you have never created a NServiceBus `Feature` before, it is not clear that the code shown [here](https://docs.particular.net/nservicebus/messaging/routing-extensibility#routing-apis-physical-routing) has to be put in a `Feature` class.

And not related to this issue, but more towards `Feature` documentation: The [documentation page](https://docs.particular.net/nservicebus/pipeline/features) shows how to use settings in a `Feature` but doesn't show how to apply them from outside. Since this is done with an extension method (`GetSettings`) that is in a sepereate namespace (`NServiceBus.Configuration.AdvanceExtensibility`) it isn't very discoverable. I had to go into the NServiceBus source itself and use the find references function of Visual Studio to find it.

**Comment by timbussmann** [comment]
thanks for the feedback @cremor 👍 
btw. the code you linked to can also be invoked from the endpointConfiguration directly in case you exchange the settings.Get with settings.GetOrCreate. The reason why we didn't make this more public yet is that we generally dislike the approach of users go through the settings to access APIs as this is, as you said, hard to discover and even harder to version properly. The reason we have no better API yet is that we weren't able to come up with a easy to use API we would like to publish instead so this API is currently in some kind of limbo state where it will remain in the core but likely be accessed slightly different in the future.

> The documentation page shows how to use settings in a Feature but doesn't show how to apply them from outside. Since this is done with an extension method (GetSettings) that is in a sepereate namespace 

thanks for pointing that out, will try to address this in the feature doc 👍

**Comment by timbussmann** [comment]
as with the proposed code changes in #4510 I'm closing this issue. This has been raised in pdev (https://github.com/Particular/PlatformDevelopment/issues/1169) to review the current routing API in general and from an upgrade perspective. This approach should address all concerns raised in the issue description.
