### ISSUE TITLE
Move InMemory persistence to a separate package

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4739]
Since it's dangerous to use and we now have the learning transport and saga persister in the core to help users getting started.
There are a few cases in which InMemory might be a good fit, but to avoid any confusion, moving it to a dedicated package is the best way to go. 
We've decided to rename the InMemory persistence to Non-Durable to better convey its intent.
Doco available [here](https://docs.particular.net/persistence/non-durable/).

**Comment by bording** [comment]
At this point what are the use cases for InMemory persistence? Would it make more sense to get rid of it instead?

**Comment by dbelcham** [comment]
That's a good question. In the past we've said that it is not a production ready persistence, and it isn't since it lacks a number of important features. If it's not "production ready" then in my eyes it's a testing/development persistence. If that's the case, where does it fit in that world considering the Learning persistence?

**Comment by cremor** [comment]
I'd like to present a case where I use InMemory persistence in production:

I use it exactly as [documented](https://docs.particular.net/nservicebus/persistence/in-memory): In a "lightweight client not interested in durability across restarts". To be exact, I have it enabled only for two storage types: Timeouts and subscriptions.

Regarding timeouts: The endpoint where I use InMemory persistence only receives change notification events. It doesn't matter if they don't live through restarts of the endpoint because then the endpoint needs to reload all data anyway. If InMemory persistence would be gone, I'd have to disable delayed retries.

Regarding subscriptions: I don't really need to store subscriptions in the endpoint since it doesn't publish any events. But I couldn't figure out a way to have this lightweight endpoint subscribe to events from other endpoints and don't require a subscription storage at the same time (using MSMQ). If I don't configure a subscription storage, an exception is thrown at startup. If I disable the `MessageDrivenSubscriptions` feature I don't get the exception but I also can't subscribe to events of other endpoints. If InMemory persistence would be gone, I'd have to use MSMQ subscription persistence instead. This would be worse in my opinion because it would create a queue that is never used. Maybe an option to disable publishing of events, but still enables subscribing to events of other endpoints would be a good idea?

**Comment by andreasohlund** [comment]
@cremor this has been targeted for v8 and we're moving this to a separate package since there are some production scenarios for volatile storage like you mention
