### ISSUE TITLE
How do I (de)register behaviors in a transport?

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#4804]
When we were working on V6, we decided to not allow the transports register behaviors. We considered this a violation of the transport seam, based on the assumption that the transport should only receive messages.

The reality verified this assumption. It seems like for various reasons it makes sense to access the pipeline in a transport. Most of these cases are related to different release cycles of the core and the transports: the transports want/need to evolve much faster. Sometimes being able to replace/add/remove behaviors of the core is the only way to make progress. [This issue](https://github.com/Particular/NServiceBus.RabbitMQ/pull/393) in RabbitMQ repo is an example where we need to choice to either "hack" the core by enabling features in an unsupported place or have RabbitMQ features leak to all endpoints in the app domain. 

We should try to address this design issue in one of the upcoming major releases to allow easier evolution of the transports.

**Comment by bording** [comment]
@SzymonPobiega I'm still not sure I see an actual problem here. If you have more than one endpoint in the same process, and they are using the same transport, then you want the behavior modification applied to each endpoint.

If you're instead using different transports in the same process, then you should configure assembly scanning to exclude the transport assembly that isn't relevant for that endpoint. You'll need to be doing that anyway to ensure handlers for one endpoint aren't picked up by another endpoint, etc.

**Comment by SzymonPobiega** [comment]
@bording excluding the transport assembly sounds like a good compromise for me! ❤️
