### ISSUE TITLE
Message delivered twice if the handler is long-running

### ISSUE THREAD

**Issue by dmytro-gokun** [Particular/NServiceBus#4878]
[NServiceBusBug.zip](https://github.com/Particular/NServiceBus/files/1183020/NServiceBusBug.zip)

Hi,

we are using NServiceBus over MSMQ. One of our command handlers is compute-bound and long running. What happens is that after ~1 minute of the handler processing a message, it gets called again with the same message. Please check the attached solution for the distilled code.

Either we're doing something wrong here (what?) or there is a bug in NServiceBus. Any help is appreciated.

Dmytro.

**Comment by bording** [comment]
Hi @dmytro-gokun,

It's always nice to get sample code demonstrating the problem being reported, so thanks for that!

The issue you're seeing is expected behavior. By default, the transaction timeout value is going to be 1 minute, so that lines up perfectly with what you are seeing. The message takes too long to process, causing the transaction to roll back, which returns the message to the queue.

If you know that your processing time is going to be exceeding 1 minute consistently, then you should increase the timeout value by using the the `TransactionScopeOptions` API, as demonstrated here: https://docs.particular.net/transports/transactions#controlling-transaction-scope-options-transaction-timeout.

**Comment by dmytro-gokun** [comment]
Hi @bording ,

thank you for the quick reply. The thing that confused me was that NServiceBus did not produce any logs about the fact that transaction timed out. Also, I did not find this information in the documentation.

The thing is that the compute task is really heavy and may take several hours to complete ...
Is this okay to have transactions lasting for several hours?
Is this behavior MSMQ-specific? Or does it also apply to RabbitMQ and Azure storage Queues (is there any place in the docs which describes this)?

Dmytro.

**Comment by bording** [comment]
I suspect the reason you didn't see any log information is that from the standpoint of NServiceBus, it hasn't observed that the transaction can't be committed because it is still in the middle of processing your message.

However, from the point of view of MSMQ itself, it sees that the transaction has been rolled back, so the message is released from the queue. Since NServiceBus 6 has concurrency enabled by default, that means the newly re-queued message gets picked up and starts a second processing attempt while the first one is still running. If you were to set the maximum concurrency to one message at a time, you'd see that the message doesn't start processing again until after the first attempt finishes and fails because the transaction can't be committed.

If you're talking about a process that will be taking hours, then trying to execute it from inside a handler is not going to be a good idea. The default maximum timeout value enforced by `System.Transactions.TransactionScope` is 10 minutes. 

We do support several different transaction modes, which are documented here: https://docs.particular.net/transports/transactions. The chart indicates the supported modes for each transport.

In general, if you have a long-running process, we recommend offloading the actual work to some other process that can be kicked off by sending a message. You can use a [Saga](https://docs.particular.net/nservicebus/sagas/) to coordinate this work.

We do have a sample that demonstrates the recommend approach: https://docs.particular.net/samples/azure/azure-service-bus-long-running/

While that is using Azure Service Bus, the overall design of the approach is applicable to any NServiceBus system.

**Comment by dmytro-gokun** [comment]
@bording Thank you for the answer. It's more clear to me now.

**Comment by mauroservienti** [comment]
@dmytro-gokun I wrote a blog post about handling long running processes when messaging and transactions are involved. The approach it's very similar to what @bording suggested with the Azure sample, but it's not based on Azure.

http://milestone.topics.it/2016/12/20/the-case-of-nservicebus-long-running-handlers-ocr-processing.html
