### ISSUE TITLE
Access retryCount via IMessageHandlerContext?

### ISSUE THREAD

**Issue by adammodlin** [Particular/NServiceBus#5089]
Is it possible/planned to access the current retryCount via the IMessageHandlerContext? If not, is there another way to access this either via the message headers or some other mechanism?

**Comment by andreasohlund** [comment]
There is a header for the delayed retries but I have a hunch that you might be wanting  a https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy?version=core_7

Can you share some more details on the use case for this?

**Comment by adammodlin** [comment]
Absolutely - we use a relational database to track the status of items as they progress through our workflow not unlike a saga. However, we're not using sagas for this specific use case.

We would like to update the status in our table to say something like "submitting job - retry 1", "submitting job - retry 2", etc. Right now, we only know once it hits the handler or once an exception is thrown so we're not able to show the user how many times it's tried to retry.

I didn't see how creating a customer recoverability policy would allow us to access the current retry within the handler. I see there is an ErrorContext but I think that is different from the IMessageHandlerContext and don't see how that would relate unless they share a property bag or something.

**Comment by dbelcham** [comment]
@adammodlin Are you looking for the immediate retry count or the delayed retry count? I would think that the immediate retry is going to be unhelpful since it usually (this does vary depending on the transport) happens inside a tight loop.  Because of that the retry count goes from 0 => `NumberOfRetries` almost instantaneously.

The delayed retry count happens much slower and might be a better value to look at the header for. https://docs.particular.net/nservicebus/messaging/headers?version=core_7#retries-handling-headers-nservicebus-retries

We also have some retry info being exposed from our new Real Time Monitoring capabilities. You might want to look at that too. https://particular.net/real-time-monitoring

**Comment by adammodlin** [comment]
Perfect, I think the delayed retry count in the header is exactly what we are looking for. I assumed there was a property there but am not developing this code personally so wasn't able to take a look. Thank you!
