### ISSUE TITLE
Synchronous Endpoint.Start throws exception.

### ISSUE THREAD

**Issue by SamuelCox** [Particular/NServiceBus#5108]
Hi, 
I am trying to start an endpoint with a valid configuration inside of ConfigureServices in an ASP.net Core project, but an exception is thrown. If I move it into an async method it works fine.

To reproduce:
Add following code to an empty asp.net core webapi project (i.e the one vs2017 creates for you)
   
 `var endpointConfiguration = new EndpointConfiguration("LifeManager.Rest");`
            `endpointConfiguration.UseTransport<RabbitMQTransport>().ConnectionString(Configuration["RabbitMqConnectionString"])
                .UseConventionalRoutingTopology();`
`            endpointConfiguration.UsePersistence<InMemoryPersistence>();`
`            endpointConfiguration.LicensePath(Configuration["NServiceBusLicense"]);`

`            var endpoint = Endpoint.Start(endpointConfiguration).GetAwaiter().GetResult();`

Start the project. An exception will be thrown with the following error:

RabbitMQ.Client.Exceptions.OperationInterruptedException: 'The AMQP operation was interrupted: AMQP close-reason, initiated by Peer, code=404, text="NOT_FOUND - no queue 'LifeManager.Rest' in vhost '/'", classId=60, methodId=20

I'm using NServicebus.RabbitMQ version 5.0.0 beta 0032, and NServicebus version 7.0.0 beta0012

I'm aware I'm using betas, but its the only way to use nservicebus with .net core. Moving this to an async method seems to work fine, so I'm thinking it's a bug.

**Comment by bording** [comment]
@SamuelCox The error you're seeing is because a queue for the endpoint hasn't been created in the broker. Looking at your endpoint configuration code, you haven't included a call to the EnableInstallers API: https://docs.particular.net/nservicebus/operations/installers?version=core_7

If you're familiar with previous versions of NServiceBus, we made a change in version 7 that means we never call that automatically for you: https://docs.particular.net/nservicebus/upgrades/6to7/#installers

Based on that call being missing, I suspect that the difference you observed between a sync and an async method is a coincidence..

**Comment by SamuelCox** [comment]
Yeah, that fixes it. Thanks.
