### ISSUE TITLE
How to specify port for one endpoint

### ISSUE THREAD

**Issue by bruceliu2008** [Particular/NServiceBus#5118]
Hi,
    I am accessing NServiceBus, I managed to run the pubsub sample, I am curious that it didn't require to specify any port for any endpoint, if the subscriber is in another server, how it can discover the messages published from another server?

Thanks,
Bruce

**Comment by andreasohlund** [comment]
Hi @bruceliu2008 , I assume that you're talking about https://docs.particular.net/samples/pubsub/ 

This sample is using the MSMQ transport, MSMQ is a federated transport meaning that it's installed on each machine where you would run NServiceBUs endpoints.

https://docs.particular.net/transports/#types-of-transports-bus-transports

This means that you always connects locally to it with no additional connection info is needed. For things like RabbitMQ/SqlServer etc you would need to specify a connection string since they are "broker" style transports.

Does this make sense?

Side note: As you start to distribute your endpoints across machines you do need to start providing NServiceBus with details on where each endpoint is physically located, see https://docs.particular.net/transports/msmq/routing for more details.

Does this help?

**Comment by bruceliu2008** [comment]
Hi @andreasohlund,
    Thanks for the reply.
    If the transport is SQL Server, in server1 we publish one message, how the subcriber in server2 knows the message? Does NSB pull the data from database? or are there any other pushing mechanism between publisher and subrciber directly?
    I checked your last link, seems no sample about specifying port of an endpoint instance.

Thanks,
Bruce

**Comment by timbussmann** [comment]
> If the transport is SQL Server, in server1 we publish one message, how the subcriber in server2 knows the message?

for SQL transport, all endpoints need to connect to the same SQL server in order to communicate with each other. If you're interested in more details, check out the SQL transport doco page here: https://docs.particular.net/transports/sql/#how-it-works

> or are there any other pushing mechanism between publisher and subrciber directly?

can you specify your question? Publish/subscribe is something handled by the transport for you. Depending on the transport, the actual mechanisms may vary but that's usually not that interesting as NServiceBus handles this for you.

> I checked your last link, seems no sample about specifying port of an endpoint instance.

MSMQ shouldn't require you to configure ports. Are you experiencing any issues with using `the MSMQ transport?

**Comment by bruceliu2008** [comment]
I contacted one of the architects a few years ago, he said MSMQ is not recommended and SQL Server is good because its AlwaysOn feature can improve availability. So I am more interested in Sql server transport.
"These tables are polled periodically to see if messages need to be processed by the endpoints." So seems it is not a inherently pushing mechanism for SQL Server transport?


Thanks,

**Comment by timbussmann** [comment]
> MSMQ is not recommended and SQL Server is good because its AlwaysOn feature can improve availability.

All transports have their specific pros and cons to consider in regards to your individual requirements. MSMQ also can be a very valuable option when availability is a key concern as it does not introduce a single point of failure (as SQL server when not using any high-availability options).

> So seems it is not a inherently pushing mechanism for SQL Server transport?

This is correct. Endpoints poll the SQL server for new messages.

Does this answer your questions?

**Comment by andreasohlund** [comment]
@bruceliu2008 we're going to close this issue since it seems that your questions have been answered. Feel free to open a discussion on our [discussion group](https://discuss.particular.net) or ping us on [Gitter](https://gitter.im/Particular/NServiceBus) if you have further questions.

**Comment by bruceliu2008** [comment]
ok, thanks for the clarifications.
