### ISSUE TITLE
Expose raw Dictionary<string,object> for custom diagnostics writing

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5159]
https://docs.particular.net/nservicebus/hosting/?version=core_7#startup-diagnostics-writing-to-other-targets

when writing to structured loggers (eg serilog and seq) there are scenarios where having the raw objects is more helpful than the serialized string

**Comment by SimonCropp** [comment]
here is a workaround for serilog if anyone else needs it in the interim 

```

class WriteStartupDiagnostics : FeatureStartupTask
{
    public WriteStartupDiagnostics(ReadOnlySettings settings)
    {
        this.settings = settings;
    }

    protected override Task OnStart(IMessageSession session)
    {
        var diagnosticEntries = settings.Get<StartupDiagnosticEntries>();
        var field = diagnosticEntries.GetType().GetField("entries",BindingFlags.Instance| BindingFlags.NonPublic);
        var entries = (List<StartupDiagnosticEntries.StartupDiagnosticEntry>)field.GetValue(diagnosticEntries);

        var dictionary = entries
            .OrderBy(e => e.Name)
            .ToDictionary(e => e.Name, e => e.Data);
        Log.Warning("StartupDiagnostics: {@Entries}", dictionary);
        return Task.CompletedTask;
    }

    protected override Task OnStop(IMessageSession session)
    {
        return Task.CompletedTask;
    }

    ReadOnlySettings settings;
}

public class StartupDiagnosticsFeature :
    Feature
{
    public StartupDiagnosticsFeature()
    {
        EnableByDefault();
    }
    protected override void Setup(FeatureConfigurationContext context)
    {
        context.RegisterStartupTask(new WriteStartupDiagnostics(context.Settings));
    }
}
```

**Comment by danielmarbach** [comment]
@SimonCropp the payload you get is already a structured data structure. In this case it is json. Instead of exposing the internals I see two options in your case:

- Log the already structured string
- Use the [exposed type](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Hosting/StartupDiagnostics/StartupDiagnosticEntries.cs#L27) to deserialize the json into a list of those objects and then write out that list to serilog

I'm guessing you have already considered option one and deemed it not a good solution because you are using the ability of serilog to interpret the structured log with different formats. What do you think about option 2?

**Comment by SimonCropp** [comment]
> Log the already structured string

so this results in seq/serilog treating the json "as a string", and as such it is encoded and essentially corrupted. it also means seq cant render it as structured json, not can it be queries using seqs structured query language

> Use the exposed type to deserialize the json into a list of those objects and then write out that list to serilog

it cannot be deserialized since is is a `Dicionary<string,object> ` and hence the object value looses type information on serialization

**Comment by SimonCropp** [comment]
also this is done in a small (21K) NSB utils library, that is re-used by many projects. so even if we could deserialize, i would prefer not to push a dependency on json.net on all consuming applications

**Comment by danielmarbach** [comment]
@SimonCropp thanks for the clarification. @Particular/nservicebus-maintainers see the comments above.

**Comment by timbussmann** [comment]
Simon's argument make sense to me. I think it would certainly possible to add another API to register a custom writer, receiving the dictionary instead of the serialized output so it can handle serialization itself.

However, the startup diagnostics feature is something we're trying to get more experience with as of now. We're already a bit concerned in case of custom writers using today's APIs as this could make it more difficult to access the diagnostic files as part of our support process. We'll add this issue to our feature backlog so it can be considered for upcoming maintenance releases.
