### ISSUE TITLE
Question/issue with Timeouts <= 1 sec

### ISSUE THREAD

**Issue by matrosovalexei** [Particular/NServiceBus#5169]
I noticed usage of DelayDeliveryWith TimeSpan <= 1 sec doesn't cause a message to be sent to the Timeout queue, and instead it goes straight to the RouteExpiredTimeoutTo queue. I could not find documentation of this behavior, however came across this line:

https://github.com/Particular/NServiceBus/blob/0f98734ad3efc93f7da684de578bd87d8617b881/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs#L61

Could you please explain the reasoning behind it? Thank you!

**Comment by timbussmann** [comment]
Hey @matrosovalexei 

Usualy, the TimeoutManager stores messages into a database which is then queried by a dedicated background task to fetch the timeouts from the storage to dispatch them to their destination queues. This query mechanism queries the timeouts with an expiry date in the range of "the last time the query ran" to the current time. Due to latency when storing data in the persistence, timeouts with a very short expiry date have a risk of being skipped in race conditions, e.g. (simplified):

1. 00:00 - store timeout with expiry date 00:01 (not committed yet)
2. 00:01 - query all timeouts with expiry date xx:xx to 00:01
3. 00:02 - database transaction commits
4. 00:04 - query all timeouts with expiry date  00:01 (exklusive)  to 00:04 -> inserted timeout is skipped.

note that a skipped timeout is not lost as there are mechanisms to check for skipped timeouts from time to time, but it will significantly delay them (from their originally planned time). By dispatching very short timeouts right away we can minimize this risks.

Do you encounter any issues with that behavior @matrosovalexei ?

**Comment by matrosovalexei** [comment]
Thank you for the explanation @timbussmann!

We had 1 sec timeouts for some messages in order to let previous distributed transaction fully commit before starting the processing. Therefore discovered that such a short timeout didn't work. I need to review and refactor the business process implementation to get rid of situations like that, though at the moment a bit longer timeout will do.

**Comment by timbussmann** [comment]
@matrosovalexei what kind of timing issues are you running into with the distributed transactions? NServiceBus should only send outgoing messages once the transaction is commited, therefore a regular `Send` or `SendLocal` should work fine?

**Comment by matrosovalexei** [comment]
During an MSMQ message processing some changes are committed to MsSql DB and a new message is sent to the same endpoint. When processing of the next message starts, sometimes (rarely, but happens) the previous DB transaction is not yet fully committed and reading rows from the DB yields previous version of the data. That is due to the eventual consistency aspect of distributed transactions. Waiting for a very short period of time is enough to let both parts of the distributed transaction to settle down.
TransportTransactionMode is set to TransactionScope.

**Comment by timbussmann** [comment]
@matrosovalexei thanks for sharing some details about the issue 👍 Have you considered the following options:
* If you're able to detect that you read old data (that might be tricky though), you can just throw an exception and let NServiceBus retries make sure that the message will be retried again shortly.
* You could lower the transaction mode to ensure that the database commits are completed before completing the transport transaction. In that case, your code which isn't using DTC anymore would have to be able to deal with retries in case the send operation fails, but you wouldn't be exposed to this issue.
