### ISSUE TITLE
TransportTests do not invoke PreStartupChecks

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus#5229]
As mentioned in https://github.com/Particular/NServiceBus/pull/5110#issuecomment-412654523, PreStartupChecks are not currently tested in the TransportTests.

Is this something that we should be invoking as part of these tests, or are we okay with those not being tested?

**Comment by andreasohlund** [comment]
Sounds reasonable to me to add them, perhaps with an option for the transport to opt-out if needed? Or to know if it's running "under test"

Given that #5110 makes changes to how we test the transport start up sequence would it make sense to include this in 7.1 since we have to change and re-test anyway?

**Comment by timbussmann** [comment]
@andreasohlund the 7.1 timeframe is already closed.
