### ISSUE TITLE
Expose the new notifications API on the FeatureStartupContext

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus#5293]
based on this discussion: https://github.com/Particular/docs.particular.net/issues/4080

**Comment by timbussmann** [comment]
shall we close this based on https://github.com/Particular/NServiceBus/pull/5449 @andreasohlund ?

**Comment by SeanFeldman** [comment]
Tim an I have discussed this. What the original issue was about is the need to wire code for the notifications for each endpoint that would need to perform an action on failed messages. Customers that want to automate this process would rather drop an assembly with a feature rather than having to explicitly add the registration and modify each endpoint project to include a reference to the shared logic executed with notification callback. Are we saying that customers with multiple endpoints should be doing so rather than us providing a convenient way to streamline registration w/o modifying each endpoint? @andreasohlund @timbussmann

**Comment by andreasohlund** [comment]
I see what you mean now. I guess technically you can create a feature that also implements `INeedInitialization` to get the drop in behaviour? would that be to clunky?

**Comment by timbussmann** [comment]
+1 on using `INeedInitialization` for such a scenario. Generally there is currently no way we can mirror all the configuration options in a feature setup and I don't see a specific reason why the notifications themselves would be a special exception from this.

I think this issue was initially raised based on the idea of exposing the general notifications infrastructure API (Subscribe<T>+Raise(T)) to the public but I don't think that's a good idea atm.

**Comment by SeanFeldman** [comment]
I'm absolutely OK with closing an issue when there's an outlined workaround or a way to help with implementing what's required.

Bringing the option of [`INeedInitialization`](https://docs.particular.net/nservicebus/lifecycle/ineedinitialization) that receives `EndpointConfiguration` should be mentioned in the issue description (which I'll do). It's closing an issue w/o a spelled out option that I'm against. Thank you.
