### ISSUE TITLE
Publishing events with MSMQ transport inside a transaction scope does not work with ravendb subscription persistence

### ISSUE THREAD

**Issue by valeriob** [Particular/NServiceBus#5295]
Hi,
this scenario used to work in previous version of nservicebus (4 and 5), we encountered it while upgrading to version 7.
Using MSMQ subscription storage this code works, but it does not using RavenDb Subscription persistence: 

```
using (var scope = new TransactionScope(TransactionScopeOption.RequiresNew, TimeSpan.MaxValue))
{
    endpointInstance.Send(new Command1()).GetAwaiter().GetResult();
    Assert.AreEqual(queue.GetAllMessages().Count(), 0);

    endpointInstance.Publish(new Event1()).GetAwaiter().GetResult();
    Assert.AreEqual(queue.GetAllMessages().Count(), 0);

    scope.Complete();
}

Assert.AreEqual(queue.GetAllMessages().Count(), 2);
```

The repro is here, just run the two test, the one with msmq subscription works, the one with ravendb does not.
Strange thing is that commands behave correctly (they do not get published until the scope is compled), while events get published right away ignoring the scope

https://github.com/onitgroup/Repro_NServiceBus_1

Thanks

**Comment by SzymonPobiega** [comment]
Hi @valeriob 

I looked at your repo and the problem is that you don't tell the `TransactionScope` to use async flow (via `TransactionScopeAsyncFlowOption.Enabled` flag). The MSMQ persister is not async so your `Publish` calls are executed on the same thread as created the transaction scope -> everything works correctly.

RavenDB persister is `async` which means that the continuation after reading the subscribers is executed on a different thread pool thread than the original one which created the transaction scope. That continuation invokes the `Publish` but at this point the `Transaction.Current` is `null` so MSMQ message dispatcher does not enlist in the transaction.

`TransactionScopeAsyncFlowOption.Enabled` should fix it.

**Comment by valeriob** [comment]
Thanks @SzymonPobiega this worked !
