### ISSUE TITLE
Event handlers and throttling

### ISSUE THREAD

**Issue by imperugo** [Particular/NServiceBus#5318]
Hi, 
I've a question about a behaviour I've to handle in my application. Before explaining the "problem" let me list the packages and the environments:

**Packages:**
- NServicebus v7.1.6
- NServiceBus.RabbitMQ v5.0.1
- Hangfire.AspNetCore v1.6.21

**Environment:**
ASP.NET Core 2.2 hosted with Docker into AWS ECS.

**Scope**
The scope of the application is to fetch information from a third party application, verify/aggregate data and finally send an HTTP call to an API.
This is executed with the following steps:

- An hangfire jobs runs every hour in order to fetch all the changed information since the last run;
- Each job verifies, normalizes the data and finally sends a set of commands;
- Few handlers catch the commands, send the HTTP request to the APIs and finally publish an event;
- The event subscriber got the event and do some internal stuff;

Up to speed everything works correctly except for the first run.
With the first run the jobs send something like 30000 commands into the queue. Because of network and other systems not managed by me, it takes something like 8-9 hours in order to process all these messages.

That's not a big problem except for two things:

- Event subscribers don't get the event till all messages are processed (so the first event message is catched after 9 hours more or less);
- The APIs we are calling has throttling system, it means I can send just 1000 calls for minutes, after that I've to wait.

My questions ares:

- Is there a way I can receive the event notification also if there are lot of messages into the queue?
- Which is the best way to handle the throttling?

Just adding my colleague @abarducci 
Thanks in advice

**Comment by mikeminutillo** [comment]
Hi @imperugo 

The best way to ensure your events get handled is to move their handlers to a different endpoint. This will cause the events to get routed to a different queue and they can be processed in parallel to the original batch of commands.

We have a sample that shows how to handle [throttling message processing](https://docs.particular.net/samples/throttling/). The basic idea is to detect when throttling is happening and then delay incoming messages to be processed later. 

For 30,000 commands you might want to find an alternative mechanism. Maybe running the endpoint in short bursts. Otherwise the commands are going to cycle around the queue a lot of times before they get processed.

**Comment by mikeminutillo** [comment]
@imperugo @abarducci does my answer help to get you unstuck? Is there any other information we can provide?

**Comment by imperugo** [comment]
Hi @mikeminutillo 
thanks for the feedback. Your answer is clear, we are working on it.

👍
