### ISSUE TITLE
How can you repopulate Azure Service Bus queues from NServiceBus 6.x sagas in DB persistence?

### ISSUE THREAD

**Issue by adammodlin** [Particular/NServiceBus#5407]
Is there a way to recover from a disaster (service bus deleted, queues accidentally deleted) from the Sagas? I have a system that's using SQL for persistence and Azure Service Bus for messaging. We've had scenarios where our messaging has been deleted/died/corrupted. We have some custom code and logic looking at our business data to repopulate queues but it seems like there's probably a better way using NServiceBus. Apologies if this isn't the correct avenue to ask the question.

**Comment by adammodlin** [comment]
Tagging @csmithk since I'm working with her on this.

**Comment by SzymonPobiega** [comment]
Not sure I understand you question. Are you looking to generate messages based on the current state of the sagas?

**Comment by adammodlin** [comment]
Yes, exactly. I'd like to be able to re-populate our service bus queues with messages based on the state of our sagas.

**Comment by SzymonPobiega** [comment]
I am afraid there is no direct support in NServiceBus for such scenarios. I see two options here:
- implement the logic for re-population in the saga code
- implement the logic for re-population is a stand-alone solution

In the first option you would have to introduce another technical message e.g. "RecoverMessages" and add a handler for it in the saga code. Then deploy the new saga code and send the "RecoverMessages" message to all the saga instances. 

The second approach is to just create a code that loads the saga data directly one-by-one and executes the re-population logic.

The second variant requires a bit more code because you need to manually query the saga data table and deserialize the saga data but I guess it would be have better performance and be more deterministic i.e. you would execute the whole process as part of a service window and have more control over when the process starts and ends.

Saga data in case of SQL Persistence is simply serialized via JSON.NET library so it should not be a big problem to deserialize it in the custom code.

**Comment by adammodlin** [comment]
Thanks @SzymonPobiega, I'll this a shot.
