### ISSUE TITLE
Assembly full name not sufficient in Diagnostics

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#5522]
FullName is the assembly name version, which is often not the version people want to know about. for example for nsb 7.2 it gives 

```
"NServiceBus.Core, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c", 
```

i suspect `AssemblyFileVersion` would be more useful

relevant code

```
settings.AddStartupDiagnosticsSection("AssemblyScanning", new
{
    Assemblies = scannableAssemblies.Assemblies.Select(a => a.FullName),
    scannableAssemblies.ErrorsThrownDuringScanning,
    scannableAssemblies.SkippedFiles
});
```

**Comment by WilliamBZA** [comment]
Thanks @SimonCropp, I'll drive this internally and make sure we get something done here.

**Comment by SimonCropp** [comment]
@andreasohlund thanks. can you link to the change in doco

**Comment by andreasohlund** [comment]
We don't really have any doco on individual fields since the idea is to "just send us the entire file if something is bad" but I guess it makes sense to update the sample content here https://docs.particular.net/nservicebus/hosting/startup-diagnostics#sample-content ? 

Was that what you had in mind?

**Comment by SimonCropp** [comment]
* (being the person who came up with that idea and implemented it)... that feature was meant to also provide information to consumers when they debug. "just send us the entire file if something is bad" was just a first step, with the intent of extending it to users to use for debugging in the future. leaving it as "just send us the entire file if something is bad" is leaving a valuable debugging feature un-used by customers.
 * at my current client we use this feature and log the structure to SEQ when an endpoint starts. So we care about the structure, especially since we do some cleanup on the json. there are likely other users who are doing similar.

**Comment by andreasohlund** [comment]
So you propose that we make the structure documented and "supported", by supported I guess you would want us to follow semver as well regarding changes? (Ie this change would have be done differently with a new node instead of changing the string to `{ FullName: "...", "FileVersion": "...."}`

**Comment by SimonCropp** [comment]
i dont think the contents needs to be part of the semver contract. 

i think exposing the types so people can deserialize would be good

better doco, and including changes to the structure in release notes, would be nice.

also allowing access to the info without needing reflection would be good https://github.com/NServiceBusExtensions/NServiceBus.Serilog/blob/master/src/NServiceBus.Serilog/StartupDiagnostics/StartupDiagnosticsReader.cs

**Comment by andreasohlund** [comment]
>i dont think the contents needs to be part of the semver contract.

👍 

>i think exposing the types so people can deserialize would be good

This would be more tricky since we treat all public types as "following semver" so the best I can think of is a separate nuget? 😬 

>also allowing access to the info without needing reflection would be good

Looking at the use case I wonder if it would be better to allow external things like `NServiceBus.Serilog` to "register" additional diagnostics writers instead of [reading and writing in a feature startup task that is done currently](https://github.com/NServiceBusExtensions/NServiceBus.Serilog/blob/master/src/NServiceBus.Serilog/StartupDiagnostics/WriteStartupDiagnostics.cs)?
