### ISSUE TITLE
Get message instance in OnMessageSentToErrorQueue FailedMessage

### ISSUE THREAD

**Issue by carl-berg** [Particular/NServiceBus#5552]
I have a scenario where i would like to publish an event when a specific message was moved to the error queue. I would also like to extract a property from the message.

I attempted to solve it by a configuration like this
```csharp
endpointConfiguration
    .Recoverability()
    .Failed(settings => settings.OnMessageSentToErrorQueue(failedMessage => 
        MovedToErrorQueue(failedMessage, () => _endpointInstance)));

private async Task MovedToErrorQueue(FailedMessage failedMessage, Func<IEndpointInstance> getEndpointInstance)
{
    if (SomehowGetMessageFrom(failedMessage) is MyCommand command)
     {
        await getEndpointInstance().Publish(new MyCommandDeliveryFailedEvent(command.id));
     }
}
```

however the `FailedMessage` type seems a bit sparse and i'm not sure how i would go about extracting message data from that so my next attempt was to add a behavior like this
```csharp
private class AddMyPropToHeader : Behavior<IIncomingLogicalMessageContext>
{
    public override async Task Invoke(IIncomingLogicalMessageContext context, Func<Task> next)
    {
        if (context.Message.Instance is MyCommand command)
        {
            context.Headers.Add("My_Command_Id", command.Id.ToString());
        }

        await next().ConfigureAwait(false);
    }
}
```
... to the pipeline and in the error handler pick this header up from `FailedMessage.Headers` but the custom header i added is not available there so it seems my only option now is for the sender of the message to add the header, which seems like a somewhat ugly solution... Is that correct or is there perhaps a better way?

**Comment by andreasohlund** [comment]
Since a message can fail due to the payload being corrected means that we can't provide the deserialized message in that part of the pipeline. Your approach to adding a header won't work either since we roll all changes to the message back before sending it to the error queue.

The solution is to add a similar behaviour to the outgoing pipeline of the sending endpoint instead so that all outgoing messages will have the command id as a header, that way it will be available on the message. Does that make sense?

Side note: 

Publishing the `MyCommandDeliveryFailedEvent` as you do might cause a false positive since it will happen outside of the receive transaction and not rollback should something fail when the message is moved to the error queue. That might be ok depending on what's supposed to happen when that event is triggered?

**Comment by carl-berg** [comment]
Yeah i understand the reasoning. I sort of wish that if the message actually was deserialized successfully, that i could get access to it. The workaround i've added is to append the header on the sender side instead but that solution doesn't feel as clean to me, but i guess it will have to do.

The actual case i'm trying so solve is an http request in a message handler that gets retried (if it fails) until the message gets moved to the error queue and when that happens i want to publish an event so that another service can pick it up and create a user notification that the request failed.

**Comment by andreasohlund** [comment]
>The workaround i've added is to append the header on the sender side instead but that solution doesn't feel as clean to me, but i guess it will have to do.

I would argue that this might be a better design since the command id feels like a infrastructure level concern and that's where headers shine and having it added to the outgoing message might help when things end up in the error queue etc.

You could go one step further and use this as your conversation id to get better tracability across message conversations and make tools like ServiceInsight allow you to view the message flow for those "conversations"

see https://docs.particular.net/nservicebus/messaging/headers#messaging-interaction-headers-nservicebus-conversationid

Hope this helps

**Comment by carl-berg** [comment]
I see your point. Even though getting access to the message would be a simpler solution it's not always something that is going to work since it is dependent on the message being successfully serialized so using headers, even though a little more cumbersome to implement might be a more solid solution. I might add a little custom logic round `config.CustomConversationIdStrategy` and an interface for messages where i want to use a custom conversation id. Thanks for the help.

**Comment by carl-berg** [comment]
I have a follow up question on this @andreasohlund... 

After digging in to `ConversationId` a bit I think, how it works is that the first message in a chain can set the conversationId-header but in my case the `Id` I would like to set as `ConversationId` is not created in the first message so therefore i cannot use `ConversationId` in that way. Is that correct, and if so, is there a better way?

**Comment by andreasohlund** [comment]
That is correct, conversation id can only be set on the first message. Can you elaborate on the use case you have and why it's not available on the first message?

Side note; I think this discussion is better suited for https://discuss.particular.net/ to get a wider audience would you mind post this there?

**Comment by andreasohlund** [comment]
@carl-berg please post on https://discuss.particular.net/ if you want to digg deeper into this
