### ISSUE TITLE
Message Behaviors are resolved on endpoint start

### ISSUE THREAD

**Issue by karolus888** [Particular/NServiceBus#5737]
Previously, message behaviors (i.e IOutgoingPhysicalMessageContext) were resolved just before sending message, which allowed us to place context specific information (i.e. from HttpContext) into the message .

After this breaking change:
https://github.com/Particular/NServiceBus/commit/74b3111676e0bad0758fb1d470862f417657dc49
message outgoing behaviours are always resolved on endpoint start which, in my opinion, does not make much sense. 
Context specific information is not available then, which causes unexpected behaviour in our applications.

**Comment by timbussmann** [comment]
> message outgoing behaviours are always resolved on endpoint start which, in my opinion, does not make much sense.

one of the multiple reasons this was done was to ensure the pipeline is buildable at startup time instead of running into runtime errors. This ensures that the endpoint starts up with functional and complete pipelines. It also reduces message processing time for the first messages as not all the caches have to be created upon the first message, increasing this message processing time noticeably.

Keep in mind, that behaviors are resolved as singletons, therefore relying on DI to resolve context-specific information is not really supported, see this note from the docs (https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors):

> Behaviors are only created once and the same instance is reused on every invocation of the pipeline. Consequently, every behavior dependency will also behave as a singleton, even if a different option was specified when registering it in dependency injection. Furthermore, the behavior and all dependencies called during the invocation phase must be concurrency-safe and possibly stateless. Storing state in a behavior instance should be avoided since it will cause the state to be shared across all message handling sessions. This could lead to unwanted side effects.

if you want to share context-specific information into the current pipeline context, you can use the `context` and set values via `context.Extensions.Set/Get` that is available to all behaviors further down the pipeline.

**Comment by karolus888** [comment]
Thank you very much for quick response. I wasn't aware that behaviours are Singleton. In my case this context information is injected via DI. 
As I understand I can use `context.Builder.Build<>` then and it will resolve scoped dependency?

**Comment by timbussmann** [comment]
> As I understand I can use context.Builder.Build<> then and it will resolve scoped dependency?

yes that should work correctly if you resolve within the behavior's `Invoke` method. NServiceBus opens a dedicated scope for every message.
