### ISSUE TITLE
Delay retries max delay cap of 24 hours is enforced incorrectly

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#5842]
### Symptoms

Failing message is delayed even though more than 24 hours have passed since the first retry attempt. According to https://docs.particular.net/nservicebus/recoverability/#delayed-retries the message should be moved automatically to the `error` if it fails more than 24 hours after the initial attempt (or the first retry attempt, it is not clear).

As a result, a message can be subject to delayed retries for much longer than 24 hours (e.g. 90 hours in case of 6 hours delay increment) before it is visible in SercicePulse.

### Who's affected

All users of NServiceBus

**Comment by andreasohlund** [comment]
As part of researching and reproducing this, we gave come to the conclusion that it's better to instead change [the documentation](https://docs.particular.net/nservicebus/recoverability/#delayed-retries) to instead match the current behaviour which is to cap the time **between two consecutive delayed retries** to 24 hours.

The reasoning is a follows:

- The current behaviour has existed since v6 which was releases 2016-10-11
- We've had no reports of customers getting into trouble because of this, on the contrary, the user that reported this actually wanted to retry for more than 24h and is happy that the current behaviour exists
- Continuing on the above fixing the "bug" will likely break some customers that currently rely on this behaviour
- The customers that actually are exposed to a potential infinite loop are the ones that have a [ fully customized recoverability policy](https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy#implement-a-custom-policy-full-customization) that isn't making use of incremental delays and is continuously asking for delays less than 24h. This likely explains why we haven't heard of any issues with this and given that we always log for every retry attempt we believe that it's unlikely that users will be affected by this in real production scenarios without noticing it since there will at least be one log entry per 24h.

Based on the above we believe that the risk of causing issues for customers is too high to warrant changing the behaviour.
