### ISSUE TITLE
Question: Configuring EndpointConfiguration using data from external source

### ISSUE THREAD

**Issue by kimbell** [Particular/NServiceBus#5980]
I'm in the process of modernizing a bunch of internal infrastructure code so that it works better in the ASP.NET Core ecosystem. NServiceBus is not something I have worked with, so I'm trying to figure out the best way to customize endpoint configuration. 

In our ecosystem we have multiple applications sending messages to the same endpoint. We have a central 'discovery service' where we can get hold of the endpoint name. In the existing libraries that originate from the .NET Framework era, they use a blocking call during application startup together with static values to have the data available when they initialize the `EndpointConfiguration`

In the new packages, I'm using an `IHostedService `to make the call to the discovery service. Since the `UseNServiceBus` call is basically setting up an `IHostedService`, ordering the startup of these IHostedServices should allow me to ensure the data is available when NServiceBus is set up. The question is then how can I make this data available to the initialization process. 

I've done a lot of digging in the source code, and come up with some crazy ideas. As I discovered the level of assembly scanning being used, they became bad ideas as well. I explored `INeedInitialization`, `IWantToRunBeforeConfigurationIsFinalized` and had a look at the feature system. Types implementing these interfaces don't support constructor arguments, so there is no nice way of injecting information from the container. 

We are currently using 7.x, and I see there is a lot of changes for version 8. 
Any changes that might help me?
Any idea when 8 will be released? 

Appreciate any pointers.

**Comment by DavidBoike** [comment]
Hi @kimbell,

I'm having a bit of trouble following what you're trying to do. It sounds like you're trying to separate the call to the discovery service from the setup of the EndpointConfiguration in order to optimize startup time so you aren't blocking on the discovery service in the `.UseNServiceBus()` call. Unfortunately this sounds like a super-complex premature optimization. The `.UseNServiceBus()` call is going to happen within, I would assume, within the first 500ms of an app's startup procedure. I don't think there's much you can do to give the discovery service a head start, and you should just call it inside the `.UseNServiceBus()` call.

Of course I might be missing something, in which I'd love to see some code to get a better idea of what you're up to.

Yes we are getting started on NServiceBus 8 but major versions for us are more about deferred breaking changes than adding features. We don't set release dates and I have no idea when it will be released.

**Comment by kimbell** [comment]
Our discovery service exposes information over REST. In our new packages, we use the `IHttpClientFactory` infrastructure to access information. This infrastructure is not available in the `UseNServiceBus` since the code is running before the `IServiceProvider` has been created. 

I've made some headway, and think I have come up with a solution that will work for us. We have copied the hosting code that uses an `IHostedService` to start the endpoint, and we have our own version of `HostAwareMessageSession`. This allows us to create the endpoint after the `IServiceProvider` has been created. 

Another challenge we discovered is that when the endpoint is created, it adds a bunch of types to the `IServiceCollection`. The idea is that we create (but not start) one endpoint with as much functionality set up as possible during the `ConfigureServices` stage; that gets stuff into DI. When we have information from our registry, we create and start a second instance that becomes the source for `IMessageSession`. We can add some API so code can check if things are ready before they try to send messages. 

We have also been playing around with a custom container. It will check the main `IServiceProvider` first, then a 'local' `IServiceProvider` for the endpoint. This is not perfect and has it's flaws since types cannot depend on types between containers. It may be enough for our use.

**Comment by danielmarbach** [comment]
@kimbell 

> I've made some headway, and think I have come up with a solution that will work for us. We have copied the hosting code that uses an IHostedService to start the endpoint, and we have our own version of HostAwareMessageSession. This allows us to create the endpoint after the IServiceProvider has been created.

for more advanced hosting scenarios this is the way to go. Because then you can inject other dependencies into the constructor of the hosted service that bootstraps your customized endpoint. 

It is also the better solution than violating [MS DI principles](https://docs.microsoft.com/en-us/dotnet/core/extensions/dependency-injection-guidelines#recommendations) and trying to build an intermediate service provider during `UseNServiceBus` which would be this pattern

```
hostBuilder
    .UseNServiceBus(hostContext => 
    {
        var tempServiceCollection = new ServiceCollection();
        tempServiceCollection.AddSingleton<FetchSomethingFromHttp>();

        var tempServiceProvider = tempServiceCollection.BuildServiceProvider();

        var cecb = tempServiceProvider.GetRequiredService<FetchSomethingFromHttp>();

        cecb.DoSomething();
    });
```

additionally, this would be problematic because you don't have a true async entry point which would force you do to sync over async 💩 

For the rest of the discussion you seem to hint that you are attempting to do multi endpoint hosting. Here is a longer comment about this from me

https://github.com/Particular/NServiceBus.Extensions.Hosting/issues/27#issuecomment-673317841

**Comment by kimbell** [comment]
I don't want multiple endpoints, but I have to fiddle things to get things registered in DI. 

I create one endpoint that is used to get things registered in DI; this endpoint is not started. 
In my hosted service, I create and start the actual endpoint; I can now use information from external systems.
If I didn't create the first endpoint, this would try to add stuff to a DI container that is already baked and things would not work. 

 So far things seem to work as expected.

**Comment by kimbell** [comment]
Our two step method of setting up the endpoint has worked for long time without any issues. The main issue was related to getting things into DI. The surrounding architecture has changed since then, so we don't depend on an external source anymore. Now we have been able to simplify things by using the standard functionality.

If you find yourself in the same situation, some creative coding can get you around the problem.
