### ISSUE TITLE
Generic Saga appears to crash NSB0018 analyser fix

### ISSUE THREAD

**Issue by antmeehan** [Particular/NServiceBus#6399]
Using NServiceBus v7.7.3 and the following code:

```cs
public class ScheduledNotificationData : ContainSagaData
{
	public Guid SourceId { get; set; }

	public DateTime? CancelledDateTime
	{
		get; set;
	}
}
public class ScheduledNotification<T> : Saga<ScheduledNotificationData> where T : INotificationCommand
{
	protected override void ConfigureHowToFindSaga(SagaPropertyMapper<ScheduledNotificationData> mapper)
	{
		mapper.ConfigureMapping<ScheduleCommandCommand<T>>(command => command.Command.Notification.SourceId)
			.ToSaga(saga => saga.SourceId);
	}
}
```

The `ConfigureHowToFindSaga` method gets a suggestion for the NSB0018 analyser. When opening the shortcut menu, the `RewriteConfigureHowToFindSagaFixer` crashes with the following stack trace:

```
System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at NServiceBus.Core.Analyzer.RewriteConfigureHowToFindSagaFixer.<>c__DisplayClass4_0.<RegisterCodeFixesAsync>b__0(Int32 i)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at NServiceBus.Core.Analyzer.RewriteConfigureHowToFindSagaFixer.<>c__DisplayClass4_0.<RegisterCodeFixesAsync>b__1(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.DocumentChangeAction.GetChangedDocumentAsync(CancellationToken cancellationToken)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

**Comment by DavidBoike** [comment]
Hi @antmeehan,

Yep, the generic type hoodwinked the code fix. The fix for our master branch (which will eventually be NServiceBus 8) is here: https://github.com/Particular/NServiceBus/pull/6400

The reason that we didn't catch this is because it's hard to get good use cases for generic types in sagas and we generally recommend you don't do it.

That said, does your saga actually work? I don't even know how the saga infrastructure will treat a mapping for a generic type. In the docs for [designing messages](https://docs.particular.net/nservicebus/messaging/messages-events-commands#designing-messages) we say:

> Generic message definitions (e.g. `MyMessage<T>`) are not supported. It is recommended to use dedicated, simple types for each message or to use inheritance to reuse shared message characteristics.

So based on that I'm not sure if we'll release a patch for NServiceBus 7.7 or not. Unless there's something I'm missing, which is definitely possible.

I'd love to hear more (and see more code) about this generic class use case and how it works to inform future decisions.

**Comment by antmeehan** [comment]
Hi @DavidBoike. Thanks for the speedy reply (and fix!).

Yes it turns out that my saga in this current state doesn't work at all 🤦 . Perhaps it's worth adding another rule in the analysers to ensure the message type isn't generic?

Definitely doesn't need a 7.7 patch 😄

My motivation for this saga was adding cancellation support for a set of 4 commands which were sent using delayed delivery.

I had used generics since the only differences between my four sagas (if implemented separately) was the type of message that started the saga and had to be published after a timeout. I'll probably refactor so the saga can simply be started by any of the four different message types (since the timeout and cancel are identical).

For reference, here's the full (incorrect) implementation:

```cs
public class ScheduledNotificationData<TCommand> : ContainSagaData
{
	public Guid SourceId { get; set; }

	public ScheduleCommandCommand<TCommand> Command{ get; set; }
	public DateTime ScheduleAt { get; set; }

	public DateTime? CancelledDateTime
	{
		get; set;
	}
}

public class ScheduledNotificationTimeout
{

}


public class ScheduledNotification<TCommand> : Saga<ScheduledNotificationData<TCommand>>,
	IAmStartedByMessages<ScheduleCommandCommand<TCommand>>,
	IHandleMessages<CancelScheduledSendNotification>,
	IHandleTimeouts<ScheduledNotificationTimeout>
	where TCommand : INotificationCommand
{
	private readonly ILog _log;

	public ScheduledNotification(ILog log)
	{
		_log = log;
	}

	public Task Handle(ScheduleCommandCommand<TCommand> command, IMessageHandlerContext context)
	{
		Data.Command = command;
		Data.ScheduleAt = command.ScheduleAt;
		return Task.CompletedTask;
	}

	public Task Handle(CancelScheduledSendNotification message, IMessageHandlerContext context)
	{
		_log.Info($"Notification {Data.SourceId} requested to be cancelled");
		Data.CancelledDateTime = DateTime.Now;

		MarkAsComplete();

		return Task.CompletedTask;
	}

	public async Task Timeout(ScheduledNotificationTimeout state, IMessageHandlerContext context)
	{
		if (Data.CancelledDateTime.HasValue)
		{
			_log.Warn($"Notification {Data.SourceId} was requested to be cancelled, but still received timeout - ignoring");
			MarkAsComplete();
			return;
		}

		var options = new SendOptions();
		options.DoNotDeliverBefore(Data.ScheduleAt);
		await context.Send(Data.Command, options).ConfigureAwait(false);
	}
	protected override void ConfigureHowToFindSaga(SagaPropertyMapper<ScheduledNotificationData<TCommand>> mapper)
	{
		mapper.MapSaga(saga => saga.SourceId)
		.ToMessage<ScheduleCommandCommand<TCommand>>(command => command.Command.Notification.SourceId)
		.ToMessage<CancelScheduledSendNotification>(command => command.SourceId);
	}

}
```

And here are the delayed delivery handlers I was trying to add cancellation support to (I've sanitised some command names):

```cs
public class ScheduleCommandCommandHandler<TCommand> : IHandleMessages<ScheduleCommandCommand<TCommand>>
    {
        public async Task Handle(ScheduleCommandCommand<TCommand> message, IMessageHandlerContext context)
        {
            var options = new SendOptions();
            options.DoNotDeliverBefore(message.ScheduleAt);
            await context.Send(message.Command, options).ConfigureAwait(false);
        }
    }

    public class ScheduleACommandCommandHandler : ScheduleCommandCommandHandler<ACommand> {}
    public class ScheduleBCommandCommandHandler : ScheduleCommandCommandHandler<BCommand> {}
    public class ScheduleCCommandCommandHandler : ScheduleCommandCommandHandler<DCommand> {}
    public class ScheduleECommandCommandHandler : ScheduleCommandCommandHandler<ECommand> { }
```

Thanks again.

**Comment by DavidBoike** [comment]
Interesting to get a look at your use case. And yes, it's possible InMemoryPersistence is being more forgiving.

I agree that we have a lot more analyzers we could/should add, and we'll probably end up doing that in minor releases after NServiceBus 8. I was part of the effort that created the saga analyzers, but that was scoped as a sagas-specific release so we focused on that instead of things that might be more applicable to all handlers. But I think there's a saga-specific thing we could have a diagnostic on at some point, so I've raised https://github.com/Particular/NServiceBus/issues/6402 to capture that.

I think you're probably on the right track to have one saga accept multiple starting messages (all of which could implement some interface or something) and 1 cancellation message, and have the logic of the saga able to figure out what to do after the timeout, rather than trying to twist generics into doing your logic for you.
