### ISSUE TITLE
Include the list of discovered message types in the diagnostics file

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus#6522]
This would be helpful when troubleshooting custom conventions (https://discuss.particular.net/t/list-all-the-messages-discovered-for-events-messages-and-commands-when-using-custom-convetions/3150/2)

**Comment by DavidBoike** [comment]
This seems to have existed since at least NServiceBus 7.2.0 (which [would have existed](https://github.com/Particular/NServiceBus/releases/7.2.0) at the time this issue was open) as shown in https://github.com/Particular/NServiceBus/commit/e454e5813afcd4e15856e3c054e1743068b78132 (you have to expand the large diff for EndpointCreator.cs) but even then the code that adds the diagnostic section seems to have been just moved from a different file so it seems to predate even NServiceBus 7.2.0.

In any case I just ran a test endpoint with NServiceBus 8.0.2 and this was part of the diagnostics file:

```json
  "Messages": {
    "CustomConventionUsed": false,
    "MessageConventions": [
      "NServiceBus Marker Interfaces"
    ],
    "NumberOfMessagesFoundAtStartup": 3,
    "Messages": [
      "EndpointStartVsCreate.Program+MyMsg",
      "EndpointStartVsCreate.Program+MyCmd",
      "EndpointStartVsCreate.Program+MyEvt"
    ]
  }
```
