### ISSUE TITLE
Support for automatic rate limiting based on message type

### ISSUE THREAD

**Issue by Asopus** [Particular/NServiceBus#6551]
Hi 

I recently looked into the [automatic rate limiting feature](https://docs.particular.net/nservicebus/recoverability/#automatic-rate-limiting) and it works great!

The only thing I miss is the ability to define the rate limit settings for a specific message type so that the feature also becomes useful for endpoints that process many different message types. The API could perhaps look something like this:

```csharp
endpointConfiguration.Recoverability().OnConsecutiveFailures<MyCommand>(10,
    new RateLimitSettings(
        timeToWaitBetweenThrottledAttempts: TimeSpan.FromSeconds(5),
        onRateLimitStarted: () => Console.Out.WriteLineAsync("Rate limiting started"),
        onRateLimitEnded: () => Console.Out.WriteLineAsync("Rate limiting stopped")));
```

This way, different settings can apply to different kinds of messages while the message types that don't have rate limit settings defined remain unaffected.

Is this something that can be supported in the future?

**Comment by andreasohlund** [comment]
Hi @Asopus, thanks for reaching out. NServiceBus has no way to selectively dequeue messages since that isn't usually supported by the queuing infrastructure we run on top of (at least I haven't seen anyone do). 

This means that we can go to a more fine-grained level than the queue when we are throttling since we have no way of knowing what the next message in the queue will be without actually reading it and thereby defeating the purpose of the rate-limiting in the first place.

So the solution is to move those specific messages(or groups of them) to a separate queue+endpoint to be able to configure the rate-limiting specifically for them. 

Does this make sense?

**Comment by Asopus** [comment]
Hello @andreasohlund 

Thanks for providing a solution and explanation.
For now this will suffice for me so I'll close this issue.
