### ISSUE TITLE
ServiceProvider is not scoped in outgoing behaviors hosted in the Generic Host

### ISSUE THREAD

**Issue by sylvaingirardbe** [Particular/NServiceBus#6944]
#### Description
The ServiceProvider in behaviors seems not to be scoped (throwing Cannot resolve scoped service ‘ITerminalContext’ from root provider) when you host your endpoint in the Generic Host. I used the sample regarding DI found here: https://docs.particular.net/samples/dependency-injection/aspnetcore/ and modified it a little bit to reproduce the issue. This repro can be found here: https://github.com/sylvaingirardbe/nsb-scoped-di-repro. Dennis van der Stelt provided a link to the multi-tenant sample here: https://discuss.particular.net/t/use-data-from-message-handler-in-a-behavior/3755 and this basically is the use case I had in mind, except for a few terminological changes and running it in a Generic Host. 

**Note:** that this only seems to be the case for outgoing contexts.

#### Expected behavior
The service should be resolved for the correct scope.

#### Actual behavior
Throws an exception

#### Versions
![image](https://github.com/Particular/NServiceBus/assets/1567350/c47c6efe-b27b-4262-98d1-d145ccd4c144)

### Steps to reproduce

https://github.com/sylvaingirardbe/nsb-scoped-di-repro

#### Workarounds
A whole lot of intrusive code to manage UoW data.

**Comment by sylvaingirardbe** [comment]
Thanks for the detailed explanation. Seeing it like this makes it obvious that it's the root container at that moment.

What I was trying to solve is that incoming http requests contain a terminal code in the headers that needs to be propagated to any outgoing message as a result of that http request. The terminal code is set on the ITerminalContext in a piece of middleware. The idea was to use this context to add the terminal code automatically to outgoing messages. 

Thanks for your suggestions.

**Comment by danielmarbach** [comment]
@sylvaingirardbe In that case it might be most effective to leverage [NServiceBus OpenTelemetry](https://docs.particular.net/nservicebus/operations/opentelemetry) support. You have multiple options available that fall into the category of "ambient state" mentioned above. 

As an example, you could have your own ActivitySource that starts an activity and set the terminal code on the activity source based on the HTTP header as a tag. You can then use that tag to then set the outgoing message header inside a behavior, since that activity should be visible inside the behavior. This sample gives you a hint how to do it

https://docs.particular.net/samples/open-telemetry/customizing/

You would need a combination of custom activity source, `Activity.Current.SetTag` and `Activity.Current.GetTagItem`. This also has the benefit of the terminal code being visible in your monitoring solution on the trace for the current process. 

https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md

Depending on how far you want the terminal code to propagate, you can also use the [baggage API](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.setbaggage?view=net-8.0). Things added to the baggage are transferred across process boundaries. NServiceBus also adds information on the bag automatically to a specific header that will contain a concatenated list of the bag items and extracts them on the receiving end back from that header into the baggage. The ASP.NET Core integration for OpenTelementry has an [enrichment capability](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/README.md#enrich) that allows you to automatically enrich activities based on the httpRequest. You can use that to set the baggage, which will then automatically propagate out over NServiceBus as mentioned above. 

Be aware that Baggage has two occurrences. Once as part of System.Diagnostics and one as [part of OpenTelemetry](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#baggage-api) and they are not the same. See this discussion

https://github.com/RehanSaeed/Serilog.Enrichers.Span/issues/164

NServiceBus currently [propagates `Activity.Current.Baggage` keys and values to the header](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/OpenTelemetry/Tracing/ContextPropagation.cs#L24) called [baggage](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Headers.cs#L251).

(*) Of course you can also use the same enrichment capability to set a tag (which would only apply for the current processes) but then you would still need to propagate that to the outgoing message headers manually as mentioned above.

**Comment by danielmarbach** [comment]
Another option that falls into ambient state category would be to use the HttpContextAccessor directly in the outgoing behavior and then map the terminal code HTTP header there directly to the message header when the HttpContext is not null and the header is there.

**Comment by sylvaingirardbe** [comment]
> @sylvaingirardbe If it is about correlation according to the terminal value, you could leverage [NServiceBus OpenTelemetry](https://docs.particular.net/nservicebus/operations/opentelemetry) support. You have multiple options available that fall into the category of "ambient state" mentioned above.
> 
> As an example, you could have your own ActivitySource that starts an activity and set the terminal code on the activity source based on the HTTP header as a tag. You can then use that tag to then set the outgoing message header inside a behavior, since that activity should be visible inside the behavior. This sample gives you a hint how to do it
> 
> https://docs.particular.net/samples/open-telemetry/customizing/
> 
> You would need a combination of custom activity source, `Activity.Current.SetTag` and `Activity.Current.GetTagItem`. This also has the benefit of the terminal code being visible in your monitoring solution on the trace for the current process.
> 
> https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md
> 
> Depending on how far you want the terminal code to propagate, you can also use the [baggage API](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.setbaggage?view=net-8.0). Things added to the baggage are transferred across process boundaries. NServiceBus also adds information on the bag automatically to a specific header that will contain a concatenated list of the bag items and extracts them on the receiving end back from that header into the baggage. The ASP.NET Core integration for OpenTelementry has an [enrichment capability](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Instrumentation.AspNetCore/README.md#enrich) that allows you to automatically enrich activities based on the httpRequest. You can use that to set the baggage, which will then automatically propagate out over NServiceBus as mentioned above.
> 
> Be aware that Baggage has two occurrences. Once as part of System.Diagnostics and one as [part of OpenTelemetry](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md#baggage-api) and they are not the same. See this discussion
> 
> [RehanSaeed/Serilog.Enrichers.Span#164](https://github.com/RehanSaeed/Serilog.Enrichers.Span/issues/164)
> 
> NServiceBus currently [propagates `Activity.Current.Baggage` keys and values to the header](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/OpenTelemetry/Tracing/ContextPropagation.cs#L24) called [baggage](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Headers.cs#L251).
> 
> (*) Of course you can also use the same enrichment capability to set a tag (which would only apply for the current processes) but then you would still need to propagate that to the outgoing message headers manually as mentioned above.

That's quite ingenious but it's not merely about correlation. We're using the terminal code to filter data and check against the user's claims so I'm not feeling too comfortable to use opentelemetry for this, for some reason.

**Comment by sylvaingirardbe** [comment]
> Another option that falls into ambient state category would be to use the HttpContextAccessor directly in the outgoing behavior and then map the terminal code HTTP header there directly to the message header when the HttpContext is not null and the header is there.

Yep, thought about that and that might actually be the cleanest atm.

**Comment by danielmarbach** [comment]
> That's quite ingenious but it's not merely about correlation. We're using the terminal code to filter data and check against the user's claims so I'm not feeling too comfortable to use opentelemetry for this, for some reason.

I can understand that. I was more coming from the angle of having the terminal code within the traces might be super helpful anyway and then it would automatically float across boundaries too if you want that to happen.

**Comment by danielmarbach** [comment]
@sylvaingirardbe based on your investigations do you have any suggestions on how we could make the documentation a bit clearer?

**Comment by sylvaingirardbe** [comment]
I see that it is implicitly documented [here](https://docs.particular.net/nservicebus/dependency-injection/child-lifetime). I'd explicitly state the fact that this is not the case when you send a message with an IMessageSession instance. And maybe add such a case in the UoW example.

**Comment by danielmarbach** [comment]
Raised https://github.com/Particular/docs.particular.net/pull/6486. Closing
